### PR TITLE
Fixes in 2019/mills

### PR DESCRIPTION
**Pull request by xexyl**
Format fixes and typo fixes in README.md. Some of the typo fixes were
very subtle (like a ' outside of `` where it should be in) but I
probably missed some as there are many terms I'm unfamiliar with. I'll
have to go through this file again but it's a good start.

Add to .gitignore file name referenced README.md.

I believe this completes the first pass of formatting and typos in 2019 
entries (I haven't really looked at the year README.md files).

### CODE REVIEW

**Comment by xexyl** [comment]
> I believe this completes the first pass of formatting and typos in 2019 entries (I haven't really looked at the year README.md files).

I could be wrong here of course.

Time to do other things for a bit .. hope to do more later but not sure what year - possibly 2018 if I haven't done that yet (I have this vague memory I did). If I haven't done 2020 (I don't think I did) then that's also another possibility.

**Comment by xexyl** [comment]
So far doing good with my game: 13 pull requests already!

**Comment by lcn2** [comment]
README

**Comment by xexyl** [comment]
> README

Happy to help!

**Pull request merged**
