### PR TITLE
Add alternative code for 1984/mullender for all!

### PR DESCRIPTION
**Pull request by xexyl**
Add alternative code for 1984/mullender for all!

Now anyone can enjoy 1984/mullender! This was a slight change to code
originally suggested in the faq (which was also updated, see below) made
for modern systems (since CPUs are much faster nowadays the duration for
usleep was much too long so one could not really enjoy the entry).

Updated bugs.md to remove this entry from the bugs.md file.

Also updated faq.md with another item. Unfortunately I had already added
another entry to faq.md and had failed to commit it before doing this
change (and adding it to the faq): how to get X11 entries (or actually
any X11 application) to work in macOS Mountain Lion and beyond. This is
why that faq entry is on this branch. It was not intended but it felt
like this change should be on its own branch / in a separate pull
request. I did not want to temporarily modify faq.md simply for this. I
have more changes to faq.md to make but that'll be on another branch so
that I have these changes there as well.

### CODE REVIEW

**Comment by xexyl** [comment]
This is I think really cool and you'll quite like this ... and I agree with you: it's one of the coolest entries ever.

**Comment by lcn2** [comment]
:-)

**Comment by xexyl** [comment]
> :-)

Very funny reply! I laughed out loud .. thanks. Can really use that!

**Comment by xexyl** [comment]
I actually have an even better improvement for this one .. I'll do another pull request in a bit (I hope). It'll make it easier to modify it for systems with different CPUs plus it'll be possible to make it so that one can just see how it works with different sleep durations. I do have to write that quick question in the typo issue too.

I just remembered as well I have a comment to look at in issue #3!

I'll try doing these all soon.

**Pull request merged**
