### PR TITLE
Add 1998/dloweneil alt code + formatting

### PR DESCRIPTION
**Pull request by xexyl**
The alt code should feel more at home for vi(m) users with movements. With the exception of the drop key (d in the original) you can use the original keys as well. Keys to drop the letter in alt version j or space, whichever you prefer. Also you can quit the game gracefully (q). That was something the author(s)? noted as something they wish they could have done but due to contest size restrictions they could not.

The README.md file has been format and typo checked and this should complete the review of this entry.

### CODE REVIEW

**Comment by xexyl** [comment]
I believe that I very possibly won't be able to finish 1998 today. It was one of those days. I should be able to finish it tomorrow if I can't by chance squeeze it in today. But for now I must head off. I will be back for a little bit but I don't know if I'll get any other entry done.

**Comment by lcn2** [comment]
Best wishes and thanks for your efforts today.

**Comment by xexyl** [comment]
> Best wishes 

And you too my good friend! Hope you're sleeping well!

> and thanks for your efforts today.

.. and you're most welcome as well! I hope to finish 1998 today. Unsure how that'll go but I aim for it. I have some fixes to the FAQ though just some things that popped out reading a new question's answer. I'll of course go over everything later on before publication to the winner repo. Depending on if (and when) I finish 1998 I might start working on 2000.

Fortunately, as noted before, many entries need minimal work and some don't need any work at all. Unfortunately (but also fortunately in other way :-) :-) ) the later years have more winning entries so it'll take a tad bit longer. Still with the speed I am managing this I think it's very likely that I will finish it before the end of the year and maybe with a bit of time to spare!

**Comment by xexyl** [comment]
As far as the FAQ see commit https://github.com/ioccc-src/temp-test-ioccc/pull/1399/commits/be04376fa6b294f4d9aa396edaba989af4417193. I'll make a comment in issue #3 and include some additional comments I've thought of to consider.

**Pull request merged**
