### PR TITLE
Fix 2019/karns/Makefile

### PR DESCRIPTION
**Pull request by xexyl**
The variable is OPT, not COPT.

### CODE REVIEW

**Review by lcn2 — COMMENTED** [review]
good catch @xexyl, thanks!

**Comment by xexyl** [comment]
> good catch @xexyl, thanks!

From memory the other repo had at one point in the example Makefile the variable `COPT` so I probably ended up doing it because of that. I know now it does not use `COPT` but `OPT` but I am pretty sure I remember seeing `COPT` at one point.

Thanks.

**Comment by lcn2** [comment]
> > good catch @xexyl, thanks!
> 
> From memory the other repo had at one point in the example Makefile the variable `COPT` so I probably ended up doing it because of that. I know now it does not use `COPT` but `OPT` but I am pretty sure I remember seeing `COPT` at one point.
> 
> Thanks.

The [Makefile.example](https://github.com/ioccc-src/mkiocccentry/blob/master/Makefile.example) over there also uses `OPT`.

**Comment by xexyl** [comment]
> > > good catch @xexyl, thanks!
> 
> > 
> 
> > From memory the other repo had at one point in the example Makefile the variable `COPT` so I probably ended up doing it because of that. I know now it does not use `COPT` but `OPT` but I am pretty sure I remember seeing `COPT` at one point.
> 
> > 
> 
> > Thanks.
> 
> 
> 
> The [Makefile.example](https://github.com/ioccc-src/mkiocccentry/blob/master/Makefile.example) over there also uses `OPT`.

It certainly does now anyway. Not sure if it always did. I can probably check when at the laptop tomorrow as I have copies of repo that aren't up to date. 

Anyway at least it's resolved now. Could have easily been missed since that was only during the forcing in case someone tried to override it. 

I found it quite by accident when working on the guidelines. 

Well anyway will do more tomorrow. Good night!

**Pull request merged**
