### PR TITLE
Typo fix and add stat to README.html

### PR DESCRIPTION
**Pull request by xexyl**
An additional stat added was how many days between the fork and the great fork merge.

Typo fix and grammar fix, as best as my tired eyes can see. Rebuilt html file and it seems good, again with my tired eyes.

Fun fact: I made the first pull request and I also made the last pull request in this repo (unless someone plays a very dirty trick)!

### CODE REVIEW

**Comment by xexyl** [comment]
I think when this is merged you can archive this repo! I only went down to the definitions of the words, making them quote blocks instead. I didn't go beyond that.

Once this is merged I will pull on my end (for archival purposes) and then delete my fork and re-fork the winner repo. After that I can fix the issues in guidelines and rules .. but most likely not today: very tired and have other things I have to take care of too. I got three of the issues over in the other repo taken care of too which leaves only one top priority issue remaining (but I need clarification before I can take care of that one).

**Comment by xexyl** [comment]
Oh I forgot to mention the stat so before this goes read-only: it was a total of 833 (!!) days of work on this repo!

**Review by lcn2 — APPROVED** [review]
Thanks 👍

**Comment by xexyl** [comment]
> Thanks 👍

You are welcome ... I guess you'll be archiving this soon? Well no need to reply on my behalf. I think we're in good shape with that file though I still wonder if it maybe would be nice to have those stats somewhere on the website.

**Comment by xexyl** [comment]
Going to delete my fork here so I can get the winner repo: then I can do fixes later (tomorrow hopefully).

**Pull request merged**
