### PR TITLE
Fix make clobber in 2020/yang

### PR DESCRIPTION
**Pull request by xexyl**
The file wrongcoded is now removed.

This should fix the make www step of verify_entry_files which allows all 
of it to complete (should because I did not test make www but the direct
command that is run on 2020/yang now exits 0).

### CODE REVIEW

**Comment by xexyl** [comment]
I hope to look at the comments from yesterday - in a bit - but I'm not sure if I will until tomorrow. I will probably get to some but not sure about all but at least some fixes are in. Tomorrow I hope will be a more productive day. For now I'm afk a while.

**Comment by xexyl** [comment]
Strangely make www still does not work .. hmm.

**Comment by xexyl** [comment]
Ah .. I see. Another make clobber needs to be fixed.

**Comment by lcn2** [comment]
it was right to code the makefile to clobber wrongcoded 😁, thanks @xexyl

**Comment by xexyl** [comment]
> it was right to code the makefile to clobber wrongcoded 😁, thanks @xexyl

But was it right to code something that was wrongcoded at all? Maybe it was wrongly coded wrongcoded. But that would imply that it's rightcoded! Or perhaps it was leftcoded when the text should read right to left or in this wrong to right? Or was it right to wrong? I'm so confused! :-)

Anyway you're welcome.

**Pull request merged**
