### PR TITLE
Fix top level .gitignore - add .sw[a-z]

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]

**Comment by lcn2** [comment]
Good infrastructure improvements, @xexyl, thank you 🙏.

**Comment by xexyl** [comment]
> Good infrastructure improvements, @xexyl, thank you 🙏.

Speaking of such .. I hope your infrastructure replacement situation is resolved soon if not already.

**Comment by lcn2** [comment]
> > Good infrastructure improvements, @xexyl, thank you 🙏.
> 
> 
> 
> Speaking of such .. I hope your infrastructure replacement situation is resolved soon if not already.

Our internet infrastructure is now stable and in reasonable shape (thanks for asking).

Monitoring showed a few minor issues that were easy to address.  We continue to monitor the situation, but expect to have to correct matters less and less. 

One matter that needs to be addressed is that a now core server's disk is now 73% full.  There are some "almost identical but not quote" duplicate data sets that need to be cleaned out.  Duplications that cans about because sine services needed to be consolidated. Hopefully that will free up enough space to drop the usage to near 60%.  This cleanup needs to happen in the next month or so.

**Comment by xexyl** [comment]
> > > Good infrastructure improvements, @xexyl, thank you 🙏.
> > 
> > 
> > Speaking of such .. I hope your infrastructure replacement situation is resolved soon if not already.
> 
> Our internet infrastructure is now stable and in reasonable shape (thanks for asking).
> 

Of course! I know how frustrating it can be.

> Monitoring showed a few minor issues that were easy to address. We continue to monitor the situation, but expect to have to correct matters less and less.
> 

Good that they're being worked out. 

I still need to sort out the fedora box sooner than later but anaconda annoys me so much but I think that might be what I will have to do. If I can get better sleep it might help a bit - but probably only a bit. The fact the system only sometimes enters the boot menu (when pressing the right key at POST) is both very odd and extremely frustrating since it requires repeatedly rebooting just to get the 'live system' up (which I hate compared to the old way). I was able to get the md raids set up there - kind of. Oddly they are missing a disk. Then the disks that are there are 'busy' so it makes it hard to do certain things. And lvm seems to not want to be activated either though it's been a while since I've had to do that manually. I probably need to reread on that part but this is why I've thought for some time of just reinstalling - since it's all backed up anyway. But then there's the issue of anaconda not supporting md+lvm. Or if it does it certainly does not show it well. With all that's going on it's pretty easy to see why I haven't really addressed it. Still with fedora life cycle i'll have to do it in a couple months if not sooner I'd expect.


> One matter that needs to be addressed is that a now core server's disk is now 73% full. There are some "almost identical but not quote" duplicate data sets that need to be cleaned out. Duplications that cans about because sine services needed to be consolidated. Hopefully that will free up enough space to drop the usage to near 60%. This cleanup needs to happen in the next month or so.

I know that problem a lot. I had the same with the backup volume on the server. Had to repeatedly clear out old backups. It was hard to find the right config for bacula (there are other things too including an `rsync` of most filesystems). But I finally got a 4TB RDX cartridge and that has helped a lot.

**Pull request merged**
