### PR TITLE
Improve thanks-for-fixes up through 1992

### PR DESCRIPTION
**Pull request by xexyl**
For each YYYY header it is a link to the respective index.html page.
 
For each entry the index.html file for the entry is in the section name
of the entry (it used to not be a link there but rather in another line
with the source code on the same line). The source code is in a 
subsection (that is the index.html is '#' and source code is '##') below
the index.html link.

(The rest of the years might happen later today or it might not happen 
until another day due to a timing conflict here.)

### CODE REVIEW

**Comment by xexyl** [comment]
I was hoping to finish this today but that might not happen .. for obvious reasons that you know about .. :-) (and also :-( )


You might enjoy the Makefile! :-) (check it out!)

**Comment by xexyl** [comment]
Just did 1993 and 1994 but I'm too tired to continue today. If you like how it looks and you think you can finish them that'd be helpful. Or if you have a way you'd like it to be done instead that's also okay. Unsure if I can do more tomorrow but I'm done for the day here. I'm thrilled I got the things in that I did but it's very possible I won't get anything done until at least Sunday.

**Comment by lcn2** [comment]
Thank you 🙏 and best wishes on your upcoming medical "adventures" @xexyl

**Comment by lcn2** [comment]
We considered rejecting this pull request, but decided instead to fix it afterwards. 

Please do not use the HTML construct "**<a name="string></a>**" as those are no longer part of the HTML 5 standard. 

Some browsers will still recognize them, but will not in the future.

We will modify the file to remove these deprecated HTML elements.

**Comment by xexyl** [comment]
> Thank you 🙏 and best wishes on your upcoming medical "adventures" @xexyl 

Thank you very much!

**Comment by xexyl** [comment]
As far as the anchor element: that is a pandoc issue. 

Anyway hopefully I will be able to do more in a few days.

**Pull request merged**
