### PR TITLE
Fixes / updates to 2020/kurdyukov4

### PR DESCRIPTION
**Pull request by xexyl**
Instead of relying on curl to obtain the text files just add them to the
repo.

Typo fixes.

Formatting fixes.

Added what on Middle-earth lámatyávë is to the README.md so that people
may enjoy the award title a bit better. From Morgoth's Ring, volume X of
the wonderful set History of Middle-earth (HoMe), one of many things
that were edited and published by the late Christopher Tolkien, heir and
literary executor of the great Tolkien.

### CODE REVIEW

**Comment by xexyl** [comment]
... leaving for the day .. will do more tomorrow.

**Comment by lcn2** [comment]
!ignore

**Comment by xexyl** [comment]
> !ignore

I was hoping for a Tolkien reply :-) ... but of course I did have to update `.gitignore` too so this works just as well.

Happy to help!

**Comment by xexyl** [comment]
> > !ignore
> 
> I was hoping for a Tolkien reply :-) ... but of course I did have to update `.gitignore` too so this works just as well.
> 
> Happy to help!

BTW: I know you've read HoMe .. did you read History of the Hobbit too ? And did you finish the book I told you about, th one Christopher blessed before he died, The Nature of Middle-earth ?

**Pull request merged**
