### PR TITLE
Additions and fixes to 2015/endoh3

### PR DESCRIPTION
**Pull request by xexyl**
Fixed Makefile so that make ; ./prog will work.

He provided additional source files that do different things. See the README.md for details and how to run (try section). He said that there should be a tarball with other source files but I don't see it and he doesn't have a download. I'll ask him for it later.

Updated .gitignore.

### CODE REVIEW

**Comment by xexyl** [comment]
Very slow day .. not sure if I'll get much more done. In the meantime I have to take a break and the first thing to do is very fun: have to clean up cat sick! :-) ... 

I hope to do more later even if not much but I do hope to do more than just a bit. However I might very well need to be downstairs with my poor doggie (or doggies) more today after her surgery ...

We'll see.

**Comment by lcn2** [comment]
nice

**Comment by xexyl** [comment]
> nice

Yes I think so too. Wonder why these files aren't in the archive though. I'll try and note this in the respective thread (think it was issue #3) to have you put it on the todo list - to contact him later on after we get things in order.

**Comment by lcn2** [comment]
> > nice
> 
> 
> 
> Yes I think so too. Wonder why these files aren't in the archive though. I'll try and note this in the respective thread (think it was issue #3) to have you put it on the todo list - to contact him later on after we get things in order.

Feel free to suggest something for the TODO set as a comm in issue #3

**Comment by xexyl** [comment]
> > > nice
> > 
> > 
> > Yes I think so too. Wonder why these files aren't in the archive though. I'll try and note this in the respective thread (think it was issue #3) to have you put it on the todo list - to contact him later on after we get things in order.
> 
> Feel free to suggest something for the TODO set as a comm in issue #3

I will in time .. thanks for the reminder! I am [testing things in GitHub](https://github.com/xexyl/md-tests) especially markdown generation so hopefully I can make an faq.md file. I think I have a good indication of what I need so I hope to work on this soon. Reason being I want to add a section on macOS wrt X11.

Sorry you're awake at this hour though :( I slept in till 3 which is nice. Hope you can get back to sleep soon! Unless of course you got a good amount of sleep ...

**Comment by xexyl** [comment]
> > > > nice
> > > 
> > > 
> > > Yes I think so too. Wonder why these files aren't in the archive though. I'll try and note this in the respective thread (think it was issue #3) to have you put it on the todo list - to contact him later on after we get things in order.
> > 
> > 
> > Feel free to suggest something for the TODO set as a comm in issue #3
> 
> I will in time .. thanks for the reminder! I am [testing things in GitHub](https://github.com/xexyl/md-tests) especially markdown generation so hopefully I can make an faq.md file. I think I have a good indication of what I need so I hope to work on this soon. Reason being I want to add a section on macOS wrt X11.
> 
> Sorry you're awake at this hour though :( I slept in till 3 which is nice. Hope you can get back to sleep soon! Unless of course you got a good amount of sleep ...

Done in comment https://github.com/ioccc-src/temp-test-ioccc/issues/3#issuecomment-1490123146. I'm sure I'll add more later! Once you've done this if you let me know I'll delete that comment.

Thank you!

**Pull request merged**
