### PR TITLE
Fixes to 2000/primenum

### PR DESCRIPTION
**Pull request by xexyl**
The entry does not do what one might expect so add a note about this.

Fixed commands to try.

Format fixes.

Make main() void again as part of redefinition of INABIAF.

### CODE REVIEW

**Comment by xexyl** [comment]
31 pull requests!

**Comment by xexyl** [comment]
Irony: the 31st pull request is for an entry called primenum!

.. that actually was NOT intentional but I wish it was ....

**Comment by lcn2** [comment]
23209

**Comment by xexyl** [comment]
> 23209

23227!

**Pull request merged**
