### PR TITLE
Add note to guidelines about forced warnings

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Really afk now and when back I have other things to do.

**Comment by lcn2** [comment]
When we accept this 6th PR, we accept the previous 5 PRs.  This is perhaps because while each PR might modify different files, the subsequent PR starts from the commit number of the previous PR?

**Comment by xexyl** [comment]
> When we accept this 6th PR, we accept the previous 5 PRs. This is perhaps because while each PR might modify different files, the subsequent PR starts from the commit number of the previous PR?

Or maybe it is because I do it in subsequent branches. But one would think that HERE it would only merge in what was committed. This seems like a problem with GitHub but maybe there is a solution to it.

On the other hand it does not seem to merge in commits of pull requests that I end up closing so if there ever is a problem again it might be good to have me close it. It's worth a go at least. Maybe I can do it differently, the pull requests, but the way I have done it is what I know.

**Comment by xexyl** [comment]
> > > When we accept this 6th PR, we accept the previous 5 PRs. This is perhaps because while each PR might modify different files, the subsequent PR starts from the commit number of the previous PR?
> > 
> > 
> > Or maybe it is because I do it in subsequent branches. But one would think that HERE it would only merge in what was committed. This seems like a problem with GitHub but maybe there is a solution to it.
> > On the other hand it does not seem to merge in commits of pull requests that I end up closing so if there ever is a problem again it might be good to have me close it. It's worth a go at least. Maybe I can do it differently, the pull requests, but the way I have done it is what I know.
> 
> You raise an interesting point.
> 
> If two people were to issue PRs, say both editing different files, we would expect the PRs to not chain ⛓️‍💥.
> 
> Here is a **guess as to what might be happening to PRs from you**:
> 
> Now assume you were to issue a PR against the master branch at commit X, creating for them a new branch and then producing commit Y. Now you produce a new 2nd PR. And though that new PR might modify completely different files, it is a PR that **starts at commit Y** producing commit Z. If we process the 2nd PR, we jump from commit X to commit Z and this in effect process the 1st PR.
> 
> No instead of starting the 2nd PR from commit Y (the end point of the first PR) you were to revert back to commit X before starting the 2nd PR. Then the "different 2nd PR" would produce commit Y' not commit Z.
> 
> Would GitHub view the "**different 2nd PR**" as if you were two different people and not "chain" both PRs? Our guess is **NO**, because both your 1st PR and the latter (2nd **OR** the "**different 2nd PR**") came from your **same forked repo**. The 2 PRs, regardless, will be "chained" because of the way GitHub does PRs from a forked repo.
> 
> But the above is just a guess. And no, it would **NOT** be reasonable to ask you to fork a completely different repo just to issue a new PR ‼️. Here we are simply speculating that the reason PRs chain is because of repos at the GitHub level, not commits at the git level.

Yes I believe very much this is a problem with GitHub, not `git` itself. The question is why. And indeed it's not reasonable to have multiple copies of the fork (only allowed to fork once of a repo btw if you didn't know). Even if I could though it would be extremely problematic because how would it handle more than one pull request adjusting one or more of the same files? It would be totally out of sync and would cause major conflicts.

Even so the question of why this is happening is a mystery. Unfortunately it is also a problem. I suggest that in the future that if a pull request needs to be modified you should let me modify it first (which you've of course done sometimes) and in the case of one that needs to be closed (rare but happens from time to time, as expected with life, the universe and everything) you ask me to close it, as that never seems to merge those in.

But that makes the mystery even more odd! Because why does it not work when you close it but it does work when I close it? It makes no sense!

**Comment by lcn2** [comment]
> Even so the question of why this is happening is a mystery. Unfortunately it is also a problem. I suggest that in the future that if a pull request needs to be modified you should let me modify it first (which you've of course done sometimes) and in the case of one that needs to be closed (rare but happens from time to time, as expected with life, the universe and everything) you ask me to close it, as that never seems to merge those in.

Unfortunately when we receive the occasional PR in the post-**Great Fork Merge** era, we believe we will need to often modify the effect of PRs that we are given.  We do **NOT** expect people to understand many of the nuances of tests and practices and conventions, nor do we expect people who want to _improve or fix_ something to do so.  We expect to have to fix, correct, add to, improve, complete the result of someone PR.  That is OK, it just means that sometimes we will have to modify a PR we are given.

**Pull request merged**
