### PR TITLE
Move INABIAF to bugs.md in 1980s entries

### PR DESCRIPTION
**Pull request by xexyl**
Having to click on the links in each README.md file will have to be done
to verify the links work but it appears to be in the form of:

    /bugs.md#YYYYauthor-readmemd

### CODE REVIEW

**Comment by xexyl** [comment]
Okay now this is incredibly ironic and very funny: the 1989/fubar entry is .. FUBAR! It doesn't work, the link! :-) :-)

**Comment by xexyl** [comment]
The problem is that I clicked on the link in inspect element and went to it and then copy pasted the `#..` part and `git diff` shows no difference. So I'm not sure what is wrong here.

Another option I guess is that we add a bunch of anchors in the bugs.md file like `<a name="1984-laman"></a>` etc.

What do you think? I'll hold off until we can come up with a better idea of what is wanted/needed.

**Comment by lcn2** [comment]
.. on the run .. but pleased to see the updates @xexyl

**Comment by xexyl** [comment]
> .. on the run .. but pleased to see the updates @xexyl 

Safe travels!

**Pull request merged**
