### PR TITLE
Reorder FAQ table of contents, adding new sections

### PR DESCRIPTION
**Pull request by xexyl**
New sections were added. Not all anchors work yet. The questions/answers are not yet in the right order. That is the next step.

Instead of relying on having to manually add numbers use ordered lists. The sections are in unordered lists so we have control over the number. The downside with this is with the long file it is harder to find the section one is in but as each question/answer has a jump to the top that should be worth the gain of not having to manually edit every question (in the table of contents as well as the question/answers) every time a question is moved to another place (or a new one is added) above others.

Another downside is minor: it does not allow for 0 as html lists do not start with 0 but 1.

Another thing that has to be done is to make sure that the html lint is correct. That can be done once this is merged. Any thing that needs to be fixed can then be fixed.

### CODE REVIEW

**Comment by xexyl** [comment]
I was trying to do the moving of questions but that has to happen another time. Have other things to do first but at least this is in now.

If I have time later today I will try doing this but otherwise it'll have to be tomorrow morning.

**Comment by xexyl** [comment]
I think this is all I'll do for the day. I'll write in the relevant issue about what I've done and what to do next.

**Review by lcn2 — APPROVED** [review]
Willing to have a look at this PR and see what might need to be done from there.

**Comment by xexyl** [comment]
Thanks!

Hopefully it works out. 

Back tomorrow. 

Have a great night!

**Comment by xexyl** [comment]
Some work certainly has to be done though. I wanted what I had done in as it seemed okay so far and it's so error prone unfortunately. 

Anyway good night!

**Pull request merged**
