### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**
Add my middle name to the handle to match my full name.

### CODE REVIEW

**Comment by xexyl** [comment]
You might get a laugh out of commit e6d146bb002085f3f3b395a5f6e138e61d4c29c7 and in particular the second and third part of:

    Not that this is a double negative but on the subject of language a
    couple fun facts about double negatives: in standard Spanish and Polish
    they are used AND it was not until after the 16th century that they were
    frowned up on in English.
    
    Question: if !! (not not) cancels out the ! (meaning it's not negative
    or rather it's true) is !!! (not not not or false) a not (false), a
    double not (true) or a triple not (false) ? :-)
    
    [0] Actually in this case it should be one or more alternatives but this
    is either a mistake in OED or me being too literal (which is very
    possible). 'Possibility' would be a better word to use as would 'choice'
    (but there are certainly other, uh, choices).

but probably esp the second part.

Anyway I think it's a useful change.

**Comment by lcn2** [comment]
This was a complex merge.  See commit 0af0de488554abf0db13e063a05ee1a83bb13eeb

**Comment by xexyl** [comment]
> This was a complex merge. See commit [0af0de4](https://github.com/ioccc-src/temp-test-ioccc/commit/0af0de488554abf0db13e063a05ee1a83bb13eeb)

Well I appreciate that you solved it! Thank you. 

I will reply to your comments in a bit though I am not sure if I will answer them all in a single go. 

Probably not. Hope you’re asleep by now (I saw that you were awake a little bit ago).

**Comment by xexyl** [comment]
On the subject of complicated merges. 

Would you prefer that I split many commits into more than one pull request?

if so how many? I might not always see manage it but I can try anyway.

**Comment by lcn2** [comment]
> On the subject of complicated merges. 
> 
> 
> 
> Would you prefer that I split many commits into more than one pull request?
> 
> 
> 
> if so how many? I might not always see manage it but I can try anyway. 

If it not too much of a bother, if you are going thru en tries year, by year, you can bunch the edits for a given year into a pull request.

**Comment by xexyl** [comment]
> > On the subject of complicated merges.
> > Would you prefer that I split many commits into more than one pull request?
> > if so how many? I might not always see manage it but I can try anyway.
> 
> If it not too much of a bother, if you are going thru en tries year, by year, you can bunch the edits for a given year into a pull request.

Sure.

I'm about to go .. back either tomorrow for a bit or Wednesday in not Tuesday (for obvious reasons).

Hope you have a great rest of your day!

**Pull request merged**
