### PR TITLE
Add 2015/duble/try.sh + format/typo checks

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I'll continue tomorrow morning. Hope you have a good night.

**Comment by lcn2** [comment]
Wow .. had to do lots of stuff to resole the pull request conflict.  *sigh*

**Comment by xexyl** [comment]
> Wow .. had to do lots of stuff to resolve the pull request conflict. _sigh_
> 
> ```shell
> git checkout -b xexyl-duble15-try master
> git pull --rebase https://github.com/xexyl/temp-test-ioccc.git duble15-try
> vi thanks-for-help.md
> git add thanks-for-help.md
> git rebase --continue
> git checkout master
> git merge xexyl-duble15-try
> vi thanks-for-help.md
> git add thanks-for-help.md
> git rebase --continue
> git commit
> git push
> ```

I guess all because of the renaming of the file. Sorry I didn't get to it! Just fixed references to the file / thanks. Thank you for taking care of this problem though. I appreciate it.

I should make some fixes to the commits to make it easier to redefine the macros in comments (and location) in the Makefile and also finish the other entries but not sure what I'll do when just yet other than I will do some here today, whatever it might be.

**Comment by lcn2** [comment]
There was some wacky things that happened with the GitHub repo. 

You should try to re-clone the temp-test-ioccc, if possible, to be sure that you are properly in sync.

**Comment by xexyl** [comment]
> There was some wacky things that happened with the GitHub repo.
> 
> You should try to re-clone the temp-test-ioccc, if possible, to be sure that you are properly in sync.

I am rather afraid of doing that as the last time I had a hell of a time even getting it to clone this repo and not the winner repo. And since you were just able to merge the pull request I guess things are fine.

**Comment by xexyl** [comment]
> If you do:
> 
> ```shell
> git log --pretty=oneline | head -n 20
> ```
> 
> you need to see these lines:
> 
> ```
> 6bd0237fa21edbc7f9e64a2273fc9e6a00c70044 Merge pull request #1661 from xexyl/duble2015-fmt
> 2b89837e0cdfda88bbca0028998b0f7232c608d6 Merge pull request #1660 from xexyl/fixes-help-links
> 0626447c623001c5352ef5e30c4ecd0993c3014a Further format fixes in 2015/duble
> 658669a73ab30b56061592385465b2d71783f38a improve .gitignore files, fix index.html links, sync CNAME
> bfdb56584f903fbe96790218647c19bdb0651f2f Fix references to thanks-for-fixes -> help
> 6206201d8a8ed272ce4fe0d634db121d1c6da4f6 add make genpath rules, .path files, updated .top and .year
> 2f002af1c88093300908778dda26f01250701c7d move archive files under archive/historic
> 211b7f28aba1786c0d8cd716ee1353516c909538 Merge branch 'xexyl-duble15-try'
> b2442cac8c09425a0e46151ef1625c3d9117696b fix make clobber for 2015/howe
> 6805d14c807055a0bb9285cdb29b66d0be82c75f moved and improved thanks
> ddf5746d4e84247df5acb3c6390f4526e9e1bcb7 add note to 2014/maffiodo2 README.md about tooting
> 25b894368cea7f3bc74e1205ce1dd76e4daa9109 fix make clobber for 2015/howe
> 0c6628d667dd398364c354d34edd5ad05df70558 moved and improved thanks
> 34e892f73da9545958e25b23f05208d00aed6825 add note to 2014/maffiodo2 README.md about tooting
> b9ed94d0a2be7741dc0bf12035a636ffd453f369 Add 2015/duble/try.sh + format/typo checks
> 05707864276f7c3da47cc077cd6151b587b624a7 Update todo file
> faff15f900ddec61739f93b52836800098955280 Improve how to redefine sleep time in 2006/sloane
> a6aa0332cd34c206eb55bc160f5f6480a5b70cce Improve how to redefine macros in 2006/monge
> 209410fa83b336ac9f04d81b6aa2eac77ba6952b Improve how to redefine macro in 2004/jdalbec
> c3fdf7c917cab4d27f13d5dd52a45b860f686cbf Improve how to redefine macros in 2004/gavare
> ```
> 
> If you see something like:
> 
> ```
> f2494a490218753353d0663e79b65b1e7d87df06 Revert "remove stray > from index.html"
> 5123ec46c771630774a8e32fbb8126190ddb48bd remove stray > from index.html
> 1500b01f8c1e96659d759584a06b0ba5250b5241 fix typo in index.html
> b8fe8d55d0ca350d12452d45b0ec1504dfd315a3 improve experimental web site links in experimental index.html
> 72d9cefa6850c992ca85dfb2678d840e1ba97239 sync CNAME with https://github.com/ioccc-src/winner/blob/master/CNAME
> 38bac24d748f7efe5c8b095f3afe059304061fa4 improve .gitignore files
> 47cae4940fa9d790c0c5bf1fb6c3bfdc61d6ab3b Merge pull request #1659 from ioccc-src/master
> ab32a325452a2631a4760ba21be3d937bc19dc00 Merge branch 'master' into master
> 6206201d8a8ed272ce4fe0d634db121d1c6da4f6 add make genpath rules, .path files, updated .top and .year
> 2f002af1c88093300908778dda26f01250701c7d move archive files under archive/historic
> 211b7f28aba1786c0d8cd716ee1353516c909538 Merge branch 'xexyl-duble15-try'
> b2442cac8c09425a0e46151ef1625c3d9117696b fix make clobber for 2015/howe
> 6805d14c807055a0bb9285cdb29b66d0be82c75f moved and improved thanks
> ddf5746d4e84247df5acb3c6390f4526e9e1bcb7 add note to 2014/maffiodo2 README.md about tooting
> 25b894368cea7f3bc74e1205ce1dd76e4daa9109 fix make clobber for 2015/howe
> 0c6628d667dd398364c354d34edd5ad05df70558 moved and improved thanks
> 34e892f73da9545958e25b23f05208d00aed6825 add note to 2014/maffiodo2 README.md about tooting
> b9ed94d0a2be7741dc0bf12035a636ffd453f369 Add 2015/duble/try.sh + format/typo checks
> 05707864276f7c3da47cc077cd6151b587b624a7 Update todo file
> faff15f900ddec61739f93b52836800098955280 Improve how to redefine sleep time in 2006/sloane
> ```
> 
> then you have a problem.
> 
> These in particular are a problem:
> 
> ```
> 47cae4940fa9d790c0c5bf1fb6c3bfdc61d6ab3b Merge pull request #1659 from ioccc-src/master
> ab32a325452a2631a4760ba21be3d937bc19dc00 Merge branch 'master' into master
> ```
> 
> To clone into a new directory, try:
> 
> ```shell
> git clone https://github.com/ioccc-src/temp-test-ioccc.git new-temp-test-ioccc
> ```
> 
> as this will clone [git@github.com:ioccc-src/temp-test-ioccc.git](https://github.com/ioccc-src/temp-test-ioccc.git) into a NEW directory called `new-temp-test-ioccc`.

I see:

```
a184f345141d9d55ae864eca187f8c5fb3d89bc7 Fixes in 2006/sloane/README.md file
6bd0237fa21edbc7f9e64a2273fc9e6a00c70044 Merge pull request #1661 from xexyl/duble2015-fmt
2b89837e0cdfda88bbca0028998b0f7232c608d6 Merge pull request #1660 from xexyl/fixes-help-links
0626447c623001c5352ef5e30c4ecd0993c3014a Further format fixes in 2015/duble
658669a73ab30b56061592385465b2d71783f38a improve .gitignore files, fix index.html links, sync CNAME
bfdb56584f903fbe96790218647c19bdb0651f2f Fix references to thanks-for-fixes -> help
6206201d8a8ed272ce4fe0d634db121d1c6da4f6 add make genpath rules, .path files, updated .top and .year
2f002af1c88093300908778dda26f01250701c7d move archive files under archive/historic
211b7f28aba1786c0d8cd716ee1353516c909538 Merge branch 'xexyl-duble15-try'
b2442cac8c09425a0e46151ef1625c3d9117696b fix make clobber for 2015/howe
6805d14c807055a0bb9285cdb29b66d0be82c75f moved and improved thanks
ddf5746d4e84247df5acb3c6390f4526e9e1bcb7 add note to 2014/maffiodo2 README.md about tooting
25b894368cea7f3bc74e1205ce1dd76e4daa9109 fix make clobber for 2015/howe
0c6628d667dd398364c354d34edd5ad05df70558 moved and improved thanks
34e892f73da9545958e25b23f05208d00aed6825 add note to 2014/maffiodo2 README.md about tooting
b9ed94d0a2be7741dc0bf12035a636ffd453f369 Add 2015/duble/try.sh + format/typo checks
05707864276f7c3da47cc077cd6151b587b624a7 Update todo file
faff15f900ddec61739f93b52836800098955280 Improve how to redefine sleep time in 2006/sloane
a6aa0332cd34c206eb55bc160f5f6480a5b70cce Improve how to redefine macros in 2006/monge
209410fa83b336ac9f04d81b6aa2eac77ba6952b Improve how to redefine macro in 2004/jdalbec
```

Does that look good to you?

I can try the commands you noted but I do recall problems before. I'm more concerned on the GitHub side and referring to the fork. I don't know that I even have a copy of the repo from ioccc-src at least not in the macOS system.

**Comment by lcn2** [comment]
> Does that look good to you?

Yes. 

You might want to clone a backup copy:

```sh
git clone https://github.com/ioccc-src/temp-test-ioccc.git backup-temp-test-ioccc
```

That way if you ever need to fallback copy you have one. 

You can then do a diff:

```sh
diff -r -u backup-temp-test-ioccc temp-test-ioccc
```

While gitnoring and differences in the `.git` directories, the rest of the tree should be same.

**Comment by lcn2** [comment]
> Good it looks okay! I can do the above but the problem is actually GitHub forking. I have to clone the fork not the ioccc-src one.

We thought that the [temp-test-ioccc.git repo](https://github.com/ioccc-src/temp-test-ioccc.git) was the fork of the **IOCCC winner repo**.  

The:

```sh
git remove -v
```

Should refer to `https://github.com/ioccc-src/temp-test-ioccc.git` and not the _winner repo_. 

We know your tree is in an OK state as far as not having problematic commits, we are just curious what your _git remove -v_ indicates.

**Comment by xexyl** [comment]
> > Good it looks okay! I can do the above but the problem is actually GitHub forking. I have to clone the fork not the ioccc-src one.
> 
> We thought that the [temp-test-ioccc.git repo](https://github.com/ioccc-src/temp-test-ioccc.git) was the fork of the **IOCCC winner repo**.  
> 
> The:
> 
> ```sh
> git remove -v
> ```
> 
> Should refer to `https://github.com/ioccc-src/temp-test-ioccc.git` and not the _winner repo_. 
> 
> We know your tree is in an OK state as far as not having problematic commits, we are just curious what your _git remove -v_ indicates. 

The problem is that I have to clone my fork and the only way to reclone the ioccc src one is to delete my fork. 

I will have to look at the command later on if I remember to as I am now afk a bit. 

What does that command do? Well I will look at the man page anyway. 

I hope that you got some sleep but if you haven't I hope that you get some sleep soon. Sleep is so important. Well you know that. I am just expressing that I do care. 

I will work on the repo in a while.

**Comment by xexyl** [comment]
Oh I see now. Okay yes it would refer to my fork and for some time trying to fork this repo kept forking the winner repo. 

That was my concern so thankfully it's good.

**Comment by xexyl** [comment]
.. actually I don't have `git remove`. It makes me think of `git rm` but there's no `-v` flag to that. What system is it on? Anyway at least it works out well and I can answer anyway what it would almost certainly show.

**Comment by xexyl** [comment]
I noticed some merge errors .. now I'm not sure what to do about that. I have to find them and hope I can get everything right.

**Comment by xexyl** [comment]
... going to checkout an earlier commit. Hopefully that'll work out.

**Comment by xexyl** [comment]
Okay maybe after the rename you can do your idea of adding `<a ..` back. There are too many merge conflicts to not go back to the old file and rename it to the new name. Sorry.

**Comment by xexyl** [comment]
> > Good it looks okay! I can do the above but the problem is actually GitHub forking. I have to clone the fork not the ioccc-src one.
> 
> We thought that the [temp-test-ioccc.git repo](https://github.com/ioccc-src/temp-test-ioccc.git) was the fork of the **IOCCC winner repo**.
> 
Just to clarify my previous comment: it is. But originally when trying to fork this repo it kept forking the other one which obviously wouldn't work. It was an annoying problem and I don't know how what I did to even fix it. Hence being concerned. Fortunately it all worked out.

> The:
> 
> ```shell
> git remove -v
> ```
> 
> Should refer to `https://github.com/ioccc-src/temp-test-ioccc.git` and not the _winner repo_.
> 
> We know your tree is in an OK state as far as not having problematic commits, we are just curious what your _git remove -v_ indicates.

As far as this goes since you addressed it was a typo (thanks - makes much mores sense now!) it is as I said:

```sh
 git remote -v
origin	git@github.com:xexyl/temp-test-ioccc.git (fetch)
origin	git@github.com:xexyl/temp-test-ioccc.git (push)
```

**Comment by lcn2** [comment]
> > > Good it looks okay! I can do the above but the problem is actually GitHub forking. I have to clone the fork not the ioccc-src one.
> > 
> > 
> > We thought that the [temp-test-ioccc.git repo](https://github.com/ioccc-src/temp-test-ioccc.git) was the fork of the **IOCCC winner repo**.
> 
> Just to clarify my previous comment: it is. But originally when trying to fork this repo it kept forking the other one which obviously wouldn't work. It was an annoying problem and I don't know how what I did to even fix it. Hence being concerned. Fortunately it all worked out.
> 
> > The:
> > ```shell
> > git remove -v
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should refer to `https://github.com/ioccc-src/temp-test-ioccc.git` and not the _winner repo_.
> > We know your tree is in an OK state as far as not having problematic commits, we are just curious what your _git remove -v_ indicates.
> 
> As far as this goes since you addressed it was a typo (thanks - makes much mores sense now!) it is as I said:
> 
> ```shell
> $ git remote -v
> origin	git@github.com:xexyl/temp-test-ioccc.git (fetch)
> origin	git@github.com:xexyl/temp-test-ioccc.git (push)
> ```

If you do the following, you will clone the repo AND then push to your fork:

```sh
git clone git@github.com:xexyl/temp-test-ioccc.git some-ioccc-dir
cd some-ioccc-dir
```

Or you could do:

```sh
git clone https://github.com/ioccc-src/temp-test-ioccc.git another-ioccc-dir
cd another-ioccc-dir
git remote set-url origin git@github.com:xexyl/temp-test-ioccc.git
```

**Comment by xexyl** [comment]
> > > > Good it looks okay! I can do the above but the problem is actually GitHub forking. I have to clone the fork not the ioccc-src one.
> > > 
> > > 
> > > We thought that the [temp-test-ioccc.git repo](https://github.com/ioccc-src/temp-test-ioccc.git) was the fork of the **IOCCC winner repo**.
> > 
> > 
> > Just to clarify my previous comment: it is. But originally when trying to fork this repo it kept forking the other one which obviously wouldn't work. It was an annoying problem and I don't know how what I did to even fix it. Hence being concerned. Fortunately it all worked out.
> > > The:
> > > ```shell
> > > git remove -v
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Should refer to `https://github.com/ioccc-src/temp-test-ioccc.git` and not the _winner repo_.
> > > We know your tree is in an OK state as far as not having problematic commits, we are just curious what your _git remove -v_ indicates.
> > 
> > 
> > As far as this goes since you addressed it was a typo (thanks - makes much mores sense now!) it is as I said:
> > ```shell
> > $ git remote -v
> > origin	git@github.com:xexyl/temp-test-ioccc.git (fetch)
> > origin	git@github.com:xexyl/temp-test-ioccc.git (push)
> > ```
> 
> If you do the following, you will clone the repo AND then be able push to your fork:
> 
> ```shell
> git clone git@github.com:xexyl/temp-test-ioccc.git backup-temp-test-ioccc
> cd backup-temp-test-ioccc
> ```
> 
> If you wanted to force your [own forked repo](https://github.com/xexyl/temp-test-ioccc.git) to match the [ioccc-src temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc.git):
> 
> ```shell
> git clone https://github.com/ioccc-src/temp-test-ioccc.git another-ioccc-dir
> cd another-ioccc-dir
> git remote set-url origin git@github.com:xexyl/temp-test-ioccc.git
> git push --force
> ```

Right but the problem was on GitHub it would not let me fork the temp repo: every time I tried (until the last time) it forked the winner repo. I don't remember how I resolved it. Nevertheless those commands might be of use at some point. I'm not sure. Thanks.

**Pull request merged**
