### PR TITLE
Minor updates to 1991/fine

### PR DESCRIPTION
**Pull request by xexyl**
I updated the try.sh with a new string that I discovered that is for fun
output especially given something the judges say in the guidelines.

Also since some of the strings are from Brian Westley's entry from 1989
and another one was credited to him I briefly referred to the entry as 
well.

### CODE REVIEW

**Comment by xexyl** [comment]
I invite you to try it out! :-)

**Comment by xexyl** [comment]
I won't be doing any more today - nothing like README.md files .. or at least I don't think I will be. I'm pretty worn out so will be taking it easy now. I should be able to resume 1991 tomorrow.

**Comment by lcn2** [comment]
Thank you 🙏 @xexyl

**Comment by xexyl** [comment]
> Thank you 🙏 @xexyl

You're very welcome! I'll do more tomorrow.

**Pull request merged**
