### PR TITLE
Change 'Click This' to 'Menu' for mobile devices

### PR DESCRIPTION
**Pull request by xexyl**
This is because 'Click This' is too vague and 'Menu' is much clearer and useful. This was done in inc/.

Rebuilt html files.

### CODE REVIEW

**Comment by xexyl** [comment]
I have left some comments/feedback in #2006 too. This is all I can do today I'm afraid but it's a good change I think. Much clearer now.

**Comment by lcn2** [comment]
We are going to look into using something like menu. 

However, as mentioned in [comment 2065139627](https://github.com/ioccc-src/temp-test-ioccc/issues/2273#issuecomment-2065139627), this is an active area of work where we are still making detailed changes. 

As such, while we note the suggestion, we have to reject this pull request implementation as it conflicts with our active work.

**Comment by xexyl** [comment]
> We are going to look into using something like menu. 
> 
> However, as mentioned in [comment 2065139627](https://github.com/ioccc-src/temp-test-ioccc/issues/2273#issuecomment-2065139627), this is an active area of work where we are still making detailed changes. 
> 
> As such, while we note the suggestion, we have to reject this pull request implementation as it conflicts with our active work. 

Well as I noted somewhere else I guessed that might be the case. That's fine. 

I will not worry about anything with this issue for a while. It was something quick and easy that I felt up to doing but it's fine. 

Please just let me know when the work you're doing is done. Hopefully by that time I will be more able to do things. 

Good luck and have a great day.

**Comment by xexyl** [comment]
> Addressed in commit [f226b7d](https://github.com/ioccc-src/temp-test-ioccc/commit/f226b7d65ed812792a66aea9986dfba10e31f0ee)
> 
> ... however more changes are on the way

Thanks. I'll let you do your work in the meantime. Still not feeling up to much following the surgery but hopefully by next week I will be able to do more. Hopefully by then you'll also be ready for me to look at things. If not maybe I can look at some of the other issues instead.

**Comment by lcn2** [comment]
> > Addressed in commit [f226b7d](https://github.com/ioccc-src/temp-test-ioccc/commit/f226b7d65ed812792a66aea9986dfba10e31f0ee)
> 
> > 
> 
> > ... however more changes are on the way
> 
> 
> 
> Thanks. I'll let you do your work in the meantime. Still not feeling up to much following the surgery but hopefully by next week I will be able to do more. Hopefully by then you'll also be ready for me to look at things. If not maybe I can look at some of the other issues instead.

Best wishes on feeling better soon.

**Pull request closed without merging**
