### PR TITLE
Fix mistake in 2020/ferguson1/chocolate-cake.html

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Have to go afk a bit .. already did some fixes in FAQ but will not commit for a while.

**Review by lcn2 — APPROVED** [review]
🍫

**Comment by xexyl** [comment]
Odd .. a change I thought I committed was not committed. I then just did a commit and push and no option to open a pull request. Trying to fix before I go to the FAQ again.

**Comment by xexyl** [comment]
Okay fixed. Now I can get to the FAQ again.

**Pull request merged**
