### PR TITLE
Fix author/Anton_Algmyr.json, rebuild authors.html

### PR DESCRIPTION
**Pull request by xexyl**
The json file had the email as a url by accident. The authors.html file
is not checked yet but will be soon, very possibly tomorrow, along with
the last (for the moment) top level html file (I think).

### CODE REVIEW

**Comment by xexyl** [comment]
It is very likely that tomorrow I will be able to say I can start looking at the entries' html files. I could possibly work more on this today so that tomorrow I could do that but I think it would be a mistake so I'm going to do other things for the rest of the day. In any case I will have to leave soon for a bit anyway.

**Review by lcn2 — APPROVED** [review]
Great catch @xexyl thank you

**Comment by xexyl** [comment]
> Great catch @xexyl thank you

'**Fissh, nice fissh**. White Face has vanished, my precious, at last, yes. Now we can eat **fish** in peace. No, not in peace, precious. For Precious is lost; yes, lost. Dirty hobbits, nasty hobbits. Gone and left us, gollum; and Precious is gone. Only poor Sméagol all alone. No Precious. Nasty Men, they'll take it, steal my Precious. Thieves. We hates them. Fissh, nice fissh. Makes us strong. Makes eyes bright, fingers tight, yes. Throttle them, precious. Throttle them all, yes, if we gets chances. Nice **fissh**. Nice **fissh**!'


.. though as you know well I added the bold to the words just so they stand out!

**Comment by xexyl** [comment]
> > Great catch @xexyl thank you
> 
> '**Fissh, nice fissh**. White Face has vanished, my precious, at last, yes. Now we can eat **fish** in peace. No, not in peace, precious. For Precious is lost; yes, lost. Dirty hobbits, nasty hobbits. Gone and left us, gollum; and Precious is gone. Only poor Sméagol all alone. No Precious. Nasty Men, they'll take it, steal my Precious. Thieves. We hates them. Fissh, nice fissh. Makes us strong. Makes eyes bright, fingers tight, yes. Throttle them, precious. Throttle them all, yes, if we gets chances. Nice **fissh**. Nice **fissh**!'
> 
> .. though as you know well I added the bold to the words just so they stand out!

And you're welcome of course! But I read that chapter yesterday and **fissh** and **fish** and **fishes** are caught. Would have been on it yet another time if not an additional time beyond that but unfortunately just too tired that I'm hardly reading anything at all each day :( .. though glad I can get a lot done here or a fair amount done. It is though my 9th time there in the book since February (and of course many times read before that). I think next year I will aim to reread some of the other books and maybe finally (!!) read The Wizard of Oz ... have had the books for some years (finally) and never got to them. Guess why! :-) (well that and other books I bought since then too some of which I read this year already.)

I am going to fix the author location of those two that I brought up yesterday and then I will see if i can check the final two html files (top level ones) that can be checked before the entries. Unfortunately they both have a lot of links so I have to be clear enough so as to verify link location and name but they should all be good (maybe some data wrong like what happened here) since it's all automated.

**Pull request merged**
