### PR TITLE
Add 2005/sykes/try.sh and test.sh + make test rule

### PR DESCRIPTION
**Pull request by xexyl**
The try.sh is different from others in that it is a loop showing a menu
with different options to use the emulator. It notes at the start of 
each iteration that one has to hit ctrl-c or whatever they have set 
their interrupt as.

The test.sh is run by make test. The exit status is ignored as it 
returns non-zero.

Format/typo check README.md.

I am not done with this entry as the bugs.md should probably be updated
to note some things the author noted. This will have to come another 
time.

### CODE REVIEW

**Comment by xexyl** [comment]
I will continue tomorrow starting with adding the entry to bugs.md and then see if I can finish the rest of 2005 (which I hope to do).

**Comment by xexyl** [comment]
As far as this entry though .. isn't this a typo in the file name? `kernal-2.901465-03.bin` ?

Want me to rename it to kernel... ?

**Comment by xexyl** [comment]
This entry is now complete unless the rename of files is needed. There are still a number of entries left in 2005 which I hope to deal with tomorrow. I am not doing any more here today however.

**Comment by lcn2** [comment]
> As far as this entry though .. isn't this a typo in the file name? `kernal-2.901465-03.bin` ?
> 
> 
> 
> Want me to rename it to kernel... ?
> 
> 
> 
> 

Yes.  It may have been a pun, but the pun was not obvious so a file rename is in order.

**Comment by xexyl** [comment]
> > As far as this entry though .. isn't this a typo in the file name? `kernal-2.901465-03.bin` ?
> > Want me to rename it to kernel... ?
> 
> Yes. It may have been a pun @xexyl, but the pun was not obvious so a file rename is in order.

What was the pun? I guess it's something I'm unaware of otherwise I would have picked up on it. Anyway it's been done now. Thanks.

**Pull request merged**
