### PR TITLE
Change 'may not compile to 'might not compile'

### PR DESCRIPTION
**Pull request by xexyl**
This is a subtle thing that I brought up on GitHub. Landon made the
    change in many files but missed some in 1986 through 1989. I am aware of
    a mass typo in the Makefiles but since some Makefiles are pending
    changes I'm not doing that yet.

### CODE REVIEW

**Comment by xexyl** [comment]
Doing other things now.

Good day!

**Comment by lcn2** [comment]
We noticed, @xexyl, something odd about the set of pull request from #33 thru #38.

Each pull request after #33 contained the all of the pull request changes back to #33.  So for example, pull request #34 included add of the file modifications from pull request #33.

If you look at the [pull requites files for #34](https://github.com/ioccc-src/temp-test-ioccc/pull/34/files), they contain the newly modified `1993/Makefile` as well as ALL of the [files modified by #33](https://github.com/ioccc-src/temp-test-ioccc/pull/33/files).

The the [pull requites files for #35 ](https://github.com/ioccc-src/temp-test-ioccc/pull/35/files) added some more files and included all of [pull requites files for #34](https://github.com/ioccc-src/temp-test-ioccc/pull/34/files) which in turn had LL of the [files modified by #33](https://github.com/ioccc-src/temp-test-ioccc/pull/33/files).

And so on thru [pull requites files for #38 ](https://github.com/ioccc-src/temp-test-ioccc/pull/38).  They all merged OK, so everything worked out.  We just wanted you to know that something odd is happening with compounding pull requests in terms of files modified.

**Comment by xexyl** [comment]
Oh and you are very welcome my good friend!

**Comment by xexyl** [comment]
It is exactly what I thought ... and I guess it is related to that problem. I'll see if I can make multiple pull requests soon to see if it works itself out. if not I'll have to re-fork this repo. Hopefully it's okay though. I am pretty sure it's from the branch issue I described above but whether deleting all the branches here will solve it or not I don't know.

Now go get some sleep 💤🛏️! and BCNU :-) (at least if you've not slept yet)

**Comment by xexyl** [comment]
With pull requests https://github.com/ioccc-src/temp-test-ioccc/pull/39 and https://github.com/ioccc-src/temp-test-ioccc/pull/40 we should find out if the problem persists after you merge them.

Of course the rest of the years have readmes (years' and the entries) to be updated as well but the 1984/README.md was a quick one I could test simply by updating the formatting.

**Pull request merged**
