### PR TITLE
Reword three award titles in 2012

### PR DESCRIPTION
**Pull request by xexyl**
At the request of Landon (after I brought it up as a possibility) I have reworded the Gold/Silver/Bronze Award titles in 2012 so that the precious metal is first so it flows a bit better.

Why did I suggest this? Because Precious told me to!

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
🥉🥈🥇@xexyl

**Comment by xexyl** [comment]
> 🥉🥈🥇@xexyl

For me I have a problem if it were to come to awards and those metals: not just the name of the award but in the case of a medal or some other object with the metals. Because silver is my favourite precious metal by far. Always has been. I find it far prettier than gold. If I have a choice I would take silver over gold: except in one case. If I were to get a prop of the One Ring obviously I would want gold. But even that would be difficult. When I have bought coins and there is the choice of gold versus silver I go for silver. Nice for price too! But then there comes the award situation: why would I want silver when gold means first place? So the question is would I choose gold or silver if I had my choice? And the funny thing is I would feel torn in two. I would obviously want the gold award but at the same time I would want the silver.

Fortunately at least when it comes to physical objects (award wise) this is never going to be a problem. I enjoy the Olympics but even if I were at one point n athlete (would be very hard with my asthma but if I was) it would be highly unlikely at my age that I would still be. But of course I would never have been competing like that. I actually wonder if anyone who has won a medal has ever had a similar problem. Would be interesting to know.

Anyway I think the award titles here look better now.

**Comment by lcn2** [comment]
We prefer the look 👀 of silver 🪙 as well.

**Comment by xexyl** [comment]
> We prefer the look 👀 of silver 🪙 as well.

Nice! Yet another thing we have in common.

I'm going afk now and looking at the time I will not really be doing anything else almost certainly. It's _possible_ I do but it's rather unlikely. Will be getting food soon and then just relaxing.

**Pull request merged**
