### PR TITLE
Minor update to thanks file

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
🙏4️⃣👦🆙📅 @xexyl 🤓

**Comment by xexyl** [comment]
> 🙏4️⃣👦🆙📅 @xexyl 🤓

Thanks fo(u)r something up 17 (of some month)?

**Comment by lcn2** [comment]
> > 🙏4️⃣👦🆙📅 @xexyl 🤓
> 
> Thanks fo(u)r something up 17 (of some month)?

Thanks 🙏 for 4️⃣ the minor 👦 update 🆙📅 @xexyl 🤓

**Comment by xexyl** [comment]
> > > 🙏4️⃣👦🆙📅 @xexyl 🤓
> > 
> > 
> > Thanks fo(u)r something up 17 (of some month)?
> 
> Thanks 🙏 for 4️⃣ the minor 👦 update 🆙📅 @xexyl 🤓

Okay that makes more sense now. Thanks. Clever. I got part of it but the 'minor' one would have never registered and I'm not sure the date one would have either as I was stuck with 'calendar'. Well done.

**Pull request merged**
