### PR TITLE
Updates and fixes to 1998/fanf

### PR DESCRIPTION
**Pull request by xexyl**
The try.sh script has been added to run the various inputs the judges 
recommended one try.

The Makefile now can do the intermediate steps. This is possible with 
the way I fixed the entry to compile. If you look at the original code 
it's different than the fixed version which is post processing (if I 
recall correctly).

Updated .gitignore.

Unless there's a mistake in markdown formatting this should complete 
1998/fanf's review.

### CODE REVIEW

**Comment by xexyl** [comment]
I do hope to finish 1998 today but I have something I have to do first. If I don't finish it today I should be able to tomorrow.

**Comment by lcn2** [comment]
Good progress on the year today @xexyl, thank you 🙏.

**Comment by xexyl** [comment]
> Good progress on the year today @xexyl, thank you 🙏.

You are most welcome. I hope to do more in a bit. I've put something else that should be done (but not required) off for too long. There's no way I can finish it today as I'm far behind on it but I am hoping to make a bit of progress on it. After that depending on how I feel I might be able to finish 1998.

Some other things that have to be done today too that will take time away but most of those shouldn't take that long.

**Comment by xexyl** [comment]
I have to go afk a bit and then I hope to continue and finish 1998. I don't know if I can: very sleepy but I'm hoping to wake up a bit. if I do finish it I don't know if I can start 2000 or not but if not I'll do tomorrow.

**Pull request merged**
