### PR TITLE
Change how 1985/sicherman alt code is managed

### PR DESCRIPTION
**Pull request by xexyl**
Removed the original sicherman.alt.c (which was the original code that requires -traditional-cpp or an older compiler) and make sicherman.alt2.c it instead which is a slight modification of sicherman.c: it has two args to main() in case some compilers (like clang) eventually object to having one arg (like it does for 4 args and claims it does for 1 even though it does not). Since the sicherman.alt.c is built automatically if compilation fails in the sicherman rule it will compile to sicherman. However if it is built manually like 'make alt' then it's built as sicherman.alt. This makes it easier to use but also allows one to build the alt version should they wish and not have it overwrite sicherman.

The try.alt.sh script was added in the case of manual compilation of sicherman.alt.c.

### CODE REVIEW

**Comment by lcn2** [comment]
Merry happy 🙂 @xexyl

**Comment by xexyl** [comment]
> Merry happy 🙂 @xexyl 

Happy Christmas to you too my good friend! 🎄 .. though I will say more about that later on and perhaps post something on mastodon about it to you. 

Hope you're sleeping well! I am going to try sleeping again in a bit but right now I can't. Not awake enough for the laptop but can't sleep. I think I might be able to in a bit for a little bit though.

**Comment by xexyl** [comment]
Hmmm should I make other entries that might fail due to compilation errors that have an alt version that will be able to compile like this entry? 

Might be good but might not. Not sure. There are not many of these. What do you think ?

**Comment by xexyl** [comment]
> Hmmm should I make other entries that might fail due to compiler (clang) errors that have an alt version that will be able to compile like this entry? 
> 
> Might be good but might not. Not sure. There are not many of these. What do you think ?

They would still have an alt rule of course just like this one.

**Comment by lcn2** [comment]
> > Hmmm should I make other entries that might fail due to compiler (clang) errors that have an alt version that will be able to compile like this entry? 
> > 
> > Might be good but might not. Not sure. There are not many of these. What do you think ?
> 
> They would still have an alt rule of course just like this one. 

Not sure as well.  It is an interesting idea.  Humm.  Not sure.

**Comment by xexyl** [comment]
> > > Hmmm should I make other entries that might fail due to compiler (clang) errors that have an alt version that will be able to compile like this entry? 
> > > 
> > > Might be good but might not. Not sure. There are not many of these. What do you think ?
> > 
> > They would still have an alt rule of course just like this one. 
> 
> Not sure as well.  It is an interesting idea.  Humm.  Not sure.

It is yes. I think it would depend on the entry. There aren't many where this would be necessary but an easy way to find them (or most of them) would be:

```sh
make clobber CC=clang all
```

and look for errors. One would have to look at each one but most entries now compile with clang so it probably wouldn't take much time. 

But then it might be that some entries would have to be done differently. Well I can look at it another time. Going to bed in a short bit. 

Hope you have a great night!

**Pull request merged**
