### PR TITLE
Update 1992/kivinen

### PR DESCRIPTION
**Pull request by xexyl**
When I started the program I noticed that it ends very quickly. Yusuke 
Endoh provided a patch that calls usleep(). I felt that this was too 
slow so I added a macro at the Makefile, Z, default 15000, so one can 
reconfigure it. Thank you Yusuke!
 
I also noticed that when starting the game it moves towards the right 
and then exits. Yusuke pointed out that if you click the mouse it moves
back towards the centre. I added this to the bugs.md file. Thank you 
Yusuke!

Fixed formatting of README.md file.

### CODE REVIEW

**Comment by lcn2** [comment]
15000*nice!

**Comment by xexyl** [comment]
> 15000*nice!
```sh
$ rm -f comp ; cat comp.c ; make comp 2>/dev/null ; ./comp
#include <stdio.h>
int main()
{
    printf("2*2*2*3*5*5*5*5 == %d: %d\n", 2*2*2*3*5*5*5*5, 
                2*2*2*3*5*5*5*5 == 15000 == 1);
}
cc -std=gnu90 -Wall -Wextra -pedantic -Wno-int-conversion -Wno-pointer-to-int-cast    -O3    comp.c   -o comp
2*2*2*3*5*5*5*5 == 15000: 1
```

Prime factorisation!

**Comment by lcn2** [comment]
> Should this also be an alt version? Like with the maze one?

Yes please.

**Comment by lcn2** [comment]
> Should this also be an alt version? Like with the maze one?

Perhaps not.  What do you think?

**Comment by xexyl** [comment]
> > Should this also be an alt version? Like with the maze one?
> 
> Perhaps not. What do you think?

Probably not too then: it makes it nigh impossible to play without it and some people might not go down to the alternate code section. Of course the same applies to the maze one with my change initially to the original and now in the alternate code but that's okay and the alternate code I made in that one has an additional nice touch in that you can control how long it sleeps. Of course I did this for this one too but I think that if we're going to do alt code for something like this it's better to do in the maze one than this one.

**Pull request merged**
