### PR TITLE
Disable bold in blockquote

### PR DESCRIPTION
**Pull request by xexyl**
It still is uncertain about italics. I think that might also be a
mistake but it is hard to be sure yet.

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

Welcome .. but the question is how does the italic work? I think there's an argument for not having it but a nice look having it too. I gave other thoughts in the issue that can be discussed. I'll be away for longer but when back I hope to look at 1991. I will be looking at it I just don't know when I will be able to. I aim to finish 1991 and at least 1992 too today but if I'm able to I'll try for 1993 too.

**Comment by lcn2** [comment]
> > Thank you @xexyl
> 
> 
> 
> Welcome .. but the question is how does the italic work? I think there's an argument for not having it but a nice look having it too. I gave other thoughts in the issue that can be discussed. I'll be away for longer but when back I hope to look at 1991. I will be looking at it I just don't know when I will be able to. I aim to finish 1991 and at least 1992 too today but if I'm able to I'll try for 1993 too.

We suggest you look at a few representative pages and see how it goes.

**Comment by xexyl** [comment]
> > > Thank you @xexyl
> > 
> > 
> > Welcome .. but the question is how does the italic work? I think there's an argument for not having it but a nice look having it too. I gave other thoughts in the issue that can be discussed. I'll be away for longer but when back I hope to look at 1991. I will be looking at it I just don't know when I will be able to. I aim to finish 1991 and at least 1992 too today but if I'm able to I'll try for 1993 too.
> 
> We suggest you look at a few representative pages and see how it goes.

Hmm .. to be clear you do mean here, right? I like the look though I still wonder why the colour is not showing up. It doesn't show up here either, on GitHub. But the styling works at W3Schools ... any idea what might be wrong? One way maybe is if we could have the block quotes have a special style but that would have to be done via pandoc or else it would not be markdown format which is obviously a problem.

**Comment by lcn2** [comment]
> > > > Thank you @xexyl
> 
> > > 
> 
> > > 
> 
> > > Welcome .. but the question is how does the italic work? I think there's an argument for not having it but a nice look having it too. I gave other thoughts in the issue that can be discussed. I'll be away for longer but when back I hope to look at 1991. I will be looking at it I just don't know when I will be able to. I aim to finish 1991 and at least 1992 too today but if I'm able to I'll try for 1993 too.
> 
> > 
> 
> > We suggest you look at a few representative pages and see how it goes.
> 
> 
> 
> Hmm .. to be clear you do mean here, right? I like the look though I still wonder why the colour is not showing up. It doesn't show up here either, on GitHub. But the styling works at W3Schools ... any idea what might be wrong?

No, sorry.

You need to look at a local server and a local copy of `ioccc.css` as the W3Schools environment is probably heavily constrained.

> One way maybe is if we could have the block quotes have a special style but that would have to be done via pandoc or else it would not be markdown format which is obviously a problem.

Yes, and it is unlikely that you would be successful doing that with pandoc too.

**Comment by xexyl** [comment]
> > > > > Thank you @xexyl
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Welcome .. but the question is how does the italic work? I think there's an argument for not having it but a nice look having it too. I gave other thoughts in the issue that can be discussed. I'll be away for longer but when back I hope to look at 1991. I will be looking at it I just don't know when I will be able to. I aim to finish 1991 and at least 1992 too today but if I'm able to I'll try for 1993 too.
> > 
> > 
> > > 
> > 
> > 
> > > We suggest you look at a few representative pages and see how it goes.
> > 
> > 
> > Hmm .. to be clear you do mean here, right? I like the look though I still wonder why the colour is not showing up. It doesn't show up here either, on GitHub. But the styling works at W3Schools ... any idea what might be wrong?
> 
> No, sorry.
> 
> You need to look at a local server and a local copy of `ioccc.css` as the W3Schools environment is probably heavily constrained.
> 

I might have to ask a friend who does this kind of thing .. though problem is he's so busy he's rarely about lately. Still I'll try and ask him sometime soon. Not now. I am almost done with 1991 but then I have to go afk - if I can finish it before I have to go afk.

> > One way maybe is if we could have the block quotes have a special style but that would have to be done via pandoc or else it would not be markdown format which is obviously a problem.
> 
> Yes, and it is unlikely that you would be successful doing that with pandoc too.

Indeed.

**Pull request merged**
