### PR TITLE
Rename remaining 'README' files to 'README.md'

### PR DESCRIPTION
**Pull request by xexyl**
I'm afraid that much has to be done with the many README.md files but this is a start anyway. In particular there are:

```sh
$ git ls-files '*README.md'|wc -l
     347
```

which is a lot to go through. I am off to do other things but I will return to working on the README files in the coming days. This ought to be fun! :-)

### CODE REVIEW

**Comment by xexyl** [comment]
I just tried pulling master branch and this is a real problem, having all the different branches here. I don't even know how to begin to fix the conflict as I don't want to cause any further problems. It might be that I simply make a new commit with the files being renamed (again) to README.md but I'm not sure if that's the case or not. Then there are the issues of the 2018/ferguson/.gitignore file I added as well as the readme files that were already with the .md extension. It's a mess.


If you are able to merge as many of the changes I made it'll be much easier to figure out what I need to do.

Going to try resting now and will do other things when I'm back.

**Comment by xexyl** [comment]
## CONFLICTS

I just tried to fix this with a new branch but it didn't work. The problem is I guess it's on this branch. I was hoping it would be smart enough to solve the problem here. Unfortunately it's not. I'm not sure what to do but this is a real problem unless you can merge specific commits. There were a lot of changes I made over many days but the commits you made yesterday and this morning have caused conflicts with them. With the many branches it's hard to go back and forth to get the right version of the files to then correct and put on the correct branch. But I have the different branches as you said it's easier for you to deal with the many changes. Is this a mistake maybe?

I'm not going to work more on the repo until this can be resolved as I don't want more problems to work out. Plus I'm too tired to do that anyway for today at least. Sorry.

**Comment by xexyl** [comment]
I just pushed the changes on this branch too and it still showing conflicts :(

I'm not doing anything else here today.

**Comment by lcn2** [comment]
We managed to commit this merge as well, @xexyl

**Comment by xexyl** [comment]
> We managed to commit this merge as well, @xexyl


Thank you very much for working this out! I'm glad (I guess) my idea about the README files and 2018/ferguson/.gitignore worked! This means I can take care of other issues. I'll be looking at what those are in a bit ... though I should say I've been playing round with some ideas for IOCCC28 too lately. Still shouldn't eat much time in this repo as I don't work _that_ much on either (as it would be unhealthy to do so). 

I still don't know why you didn't see the pull requests but hopefully that'll not happen again. Anyway thank you! Hope you're having a nice sleep my friend!

**Pull request merged**
