### PR TITLE
Add FAQ about dead and invalid links

### PR DESCRIPTION
**Pull request by xexyl**
... and what one should do, of course. This includes an example of an 
invalid link (albeit an extreme one :-) ) that I fixed quite some time 
back (months ago) just to give an idea. But it's more useful to check 
for dead links in the IOCCC website itself (linking to pages/files in 
the website that is). Of course I'll be doing that once the README.md 
files are in order but there's a high chance I won't be able to find 
them all esp as after the website is done I have more to do.

### CODE REVIEW

**Comment by xexyl** [comment]
You might enjoy the log of that fix btw:

```git
Author: Cody Boone Ferguson <53008573+xexyl@users.noreply.github.com>
Date:   Mon Apr 17 11:49:51 2023 -0700

    Detoxify Stephen Sykes (remove drug link) :-)
    
    Sound crazy? That's because it is! The URL is no longer owned by Stephen
    and instead it's a marijuana dispensary in Canada. That's right. The
    IOCCC has been endorsing drugs for some years now! :-) (or maybe it's
    :-( ? :-) ).
    
    Used Internet Wayback Machine link instead.
    
    Updated the CSV files, the winners.html files and all the relevant
    README.md files.
```

:-)

**Comment by lcn2** [comment]
The use of humor (and even humour 😄) is welcome.

We will, however, have to tone it down with a FAQ edit of our own as some people are humor impaired on the topic.  Nevertheless as must "spoil" your joke a bit as a result.

Leave it to us as we have a plan to let a little of your original humor to leak through, so do not worry (nor correct your last edit), we will take care of it accordingly.

We also have a plan to move the reference to your link checking into the "thanks" file.

Again, we have a plan on how to do this: so expect an edit to both files in the future.

**Comment by xexyl** [comment]
> The use of humor (and even humour 😄) is welcome.
> 
Humour yes.

> We will, however, have to tone it down with a FAQ edit of our own as some people are humor impaired on the topic. Nevertheless as must "spoil" your joke a bit as a result.
> 
Sadly that first part is true. Fortunately there's no joke meant! The only reason I included that is it was all I could think of at the time. After I committed and was resting I had the thought that I could just say instead 'if the website no longer is the author's' (or something like that) but I didn't get a chance to do that. So don't worry about it. I appreciate it though.

> Leave it to us as we have a plan to let a little of your original humor to leak through, so do not worry (nor correct your last edit), we will take care of it accordingly.

Well that sounds fun! Thanks. But no worries again. As noted it was the only thing I could think of at the time.

> 
> We also have a plan to move the reference to your link checking into the "thanks" file.
> 
I thought there already is that (I did but not for each entry of course)? Did I add it to the FAQ? If so I don't recall doing it. But it certainly isn't needed there either so by all means move it, please, and thank you for catching it.

> Again, we have a plan on how to do this: so expect an edit to both files in the future.

No worries either way. Like I said although I found it funny the first time (I still do, the log), I didn't include it in the FAQ for that reason. The log above was actually just for you as you were on holiday at the time so you did a mass merge and missed it.

I have good news with the eye doctor. I'll say elsewhere. Not sure if I'll do any more changes today though.

**Comment by lcn2** [comment]
Sorry about having to do commit f1c4b7aaf72c6280ea7e1ff631d8e20883a90f78

The reference in FAQ 5.6 was just too problematic to leave as it was.

We did improve the FAQ 5.6 in terms of providing guidance to those who wish to
help with correcting or reporting broken/invalid web links.

We also moved some content to the thanks file.

**Comment by xexyl** [comment]
> Sorry about having to do commit [f1c4b7a](https://github.com/ioccc-src/temp-test-ioccc/commit/f1c4b7aaf72c6280ea7e1ff631d8e20883a90f78)
> 
Don't be sorry! Like I said yesterday it was all I could think of at the time. Also what you changed it to is even better. I laughed out loud at it! Much needed laugh. Besides it's a team effort to make it better and it is better now (and funnier though it might be an inside joke between us :-) ). Thanks!

> The reference in FAQ 5.6 was just too problematic to leave as it was.
> 
As above: no worries. I had the thought to change it too but it was too late at that point. It was just a good example that I could think of - the only example - at the time.

> We did improve the FAQ 5.6 in terms of providing guidance to those who wish to help with correcting or reporting broken/invalid web links.
> 
I saw it and it looks good .. fixed some typos though .. will commit soon.

> We also moved some content to the thanks file.

I see that. I like it .. thanks! I didn't expect that.

.. so no worries, it's all good and even better. Like I said originally (and above in this comment) I only included that as it was all I could think of at the time!

**Pull request merged**
