### PR TITLE
Fixes/updates to 2004/anonymous/README.md

### PR DESCRIPTION
**Pull request by xexyl**
Some link fixes/additions and a fun fact or two added/clarified.

Precious made me do it! If this file is updated again it will be for
link fixes or format fixes when I go through the index.html files.

### CODE REVIEW

**Comment by xexyl** [comment]
I will return tomorrow to the other file for sure. I must leave for now and likely the rest of the day. Good luck with the infrastructure situation!

**Comment by lcn2** [comment]
⏣ 🤓 👍 @xexyl 

p.s. Still working on infrastructure

**Comment by xexyl** [comment]
> ⏣ 🤓 👍 @xexyl 
> 
> 
> 

💍 (we need a gold ring emoji though in every other case I would want silver as it's my favourite precious metal)

> p.s. Still working on infrastructure 

Good luck! I will be back tomorrow and hopefully I can get more done.

**Comment by lcn2** [comment]
This edit fails under `bin/find-missing-links.sh`.  Perhaps `make www` was not performed?

You might wish to review `markdown.html` and note the last item, @xexyl.

**Comment by xexyl** [comment]
> This edit fails under `bin/find-missing-links.sh`.  Perhaps `make www` was not performed?
> 
> 
> 
> You might wish to review `markdown.html` and note the last item, @xexyl.

Oops! I did the direct readme2index. 

I will look at this soon. I am in the middle of something now. I don't know why it would fail though since no files are linked to. 

Well I will take a look soon.

**Comment by xexyl** [comment]
> > This edit fails under `bin/find-missing-links.sh`.  Perhaps `make www` was not performed?
> > 
> > 
> > 
> > You might wish to review `markdown.html` and note the last item, @xexyl.
> 
> Oops! I did the direct readme2index. 
> 
> I will look at this soon. I am in the middle of something now. I don't know why it would fail though since no files are linked to. 
> 
> Well I will take a look soon. 

First time I did it that way but apparently it's a mistake. I will do the other way from now on.

**Comment by xexyl** [comment]
Looking into it now ..

**Comment by xexyl** [comment]
Ah. I see. Okay I'll fix it now. Hold on.

**Comment by xexyl** [comment]
As the fix commit shows (or a comment?) it's because the ()s in the link name confused the script. Hardly worth trying to fix the script as one should just use the & codes as I thought of at the time but failed to do as it rendered okay, forgetting about the missing link script (or running it).

**Pull request merged**
