### PR TITLE
Mass fix Makefiles: $(MAKE) -> ${MAKE}

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Have to go afk a bit but when I'm back I'm going to continue what I was doing with 2004/gavin.

**Comment by lcn2** [comment]
The $(MAKE) is by tradition, however this change makes them consistent and that's OK too.

**Comment by xexyl** [comment]
> The $(MAKE) is by tradition, however this change makes them consistent and that's OK too.

Yeah. I could have done it with ()s for the others too. I chose the `{}` because that's what it is for the others. It was also fewer to change which is less error prone (of course).

I actually only used `()`s in Makefiles prior to the IOCCC.

**Comment by xexyl** [comment]
Unrelated I hope to return to 2004 in a bit. Having a problem focusing right now.

I hope to reply to some of the wonderful comments yesterday and today too. Hope you have a great day! I'm sure I'll be able to get some more pull requests in later on today.

**Comment by xexyl** [comment]
That being said ... want me to change all references of `${MAKE}` to `$(MAKE)`? What about the other variables like `${CC}` to `$(CC)` etc.?

**Comment by lcn2** [comment]
> That being said ... want me to change all references of `${MAKE}` to `$(MAKE)`? What about the other variables like `${CC}` to `$(CC)` etc.?
> 
> 

No, the consistent use of {}'s is fine.

**Pull request merged**
