### PR TITLE
Remove lists and list items from FAQ

### PR DESCRIPTION
**Pull request by xexyl**
That is I did:

    sgit -e '/^<\/li>$/d' -e '/^<li>$/d' \
    -e '/^<ol>$/d' -e -e 's/^<\/ol>$/g' faq.md

The next steps are to move the question/answers to the appropriate sections and to try and shorten as many answers as possible, possibly merging some or even getting rid of some.

### CODE REVIEW

**Comment by xexyl** [comment]
Hopefully this also solves the lint problems. I have to go afk for a while but when back I'll try and move the answers. Unsure how that'll go but if I have problems there I'll try and look at shortening/removing answers that could use that.

I did get more sleep last night and that means not only less interrupted but also slept to 5 again: a nice hour for me. Even so I will struggle, I think, to move the answers to there right sections.

**Review by lcn2 — APPROVED** [review]
sgit fun 🤩

**Comment by lcn2** [comment]
> Hopefully this also solves the lint problems. I have to go afk for a while but when back I'll try and move the answers. Unsure how that'll go but if I have problems there I'll try and look at shortening/removing answers that could use that.

You have made good progress 👍

> I did get more sleep last night and that means not only less interrupted but also slept to 5 again: a nice hour for me.

That's a good sign.

We slept well last night and will now take another short nap. 

> Even so I will struggle, I think, to move the answers to there right sections.

While you are away we may sneak in and take a look and perhaps help with some of the manual editing.. maybe but we will nap a bit more first.

**Comment by xexyl** [comment]
Thanks! Though might be back first. 

Sleep well! Will reply to rest later.

**Comment by xexyl** [comment]
> sgit fun 🤩

Funny thing: sgit is an anagram for gits; this was only partly intentional when naming it. Of course it's also an anagram for gist.

**Comment by xexyl** [comment]
> > Hopefully this also solves the lint problems. I have to go afk for a while but when back I'll try and move the answers. Unsure how that'll go but if I have problems there I'll try and look at shortening/removing answers that could use that.
> 
> You have made good progress 👍
> 

Thank you! Trying. The moving all those answers is the real issue. Not sure why it's proving such a problem for me: probably being tired does not help but I'm sure it's more than that.

I forgot the `<ul>` and `</ul>` so the lint is upset. See commit 5dfa48efb31fd5f5a8bf37f4e4c9deb45f02aca6 of the fix. Hopefully that fixes it.


> > I did get more sleep last night and that means not only less interrupted but also slept to 5 again: a nice hour for me.
> 
> That's a good sign.
> 

It's certainly nice. Hopefully it continues. 

> We slept well last night and will now take another short nap.
> 

Glad you slept well and I hope after the nap you feel even more rested! There's no chance of any more rest for me until sleep tonight. That's okay though. I hate sleeping in the day. I actually also hate the feeling of being sleepy, even when it's night. I feel very uncomfortable. My guess why this is is I feel out of control of my body and it probably stems from anaesthesia at a very early age. I hate and have always hated the feeling and coming out of it too. I fight it. It's not a nice feeling for me. My first surgery was 17mo old and I've been under the knife many more times since then. More than most people could even imagine in a lifetime.

I used to take naps in the day at times but fortunately I don't have to now. In those days I did have to; I couldn't function without them.


> > Even so I will struggle, I think, to move the answers to there right sections.
> 
> While you are away we may sneak in and take a look and perhaps help with some of the manual editing.. maybe but we will nap a bit more first.

That would be **IMMENSELY** helpful. Thank you! I can then focus on shortening the FAQ answers. Also I can, in the interim, look at other files (that way there's no conflicts). If you can't get to it today then I can look at it tomorrow. 

Anyway hope you had a great nap and I hope you're all well now too!

**Pull request merged**
