### PR TITLE
Be more explicit about -O0 -g in 2019/endoh

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I decided I will take care of this problem before I resume 2019 as there aren't many of these (one has by mistake `-ggdb3` which will be removed too) and this way the problem is addressed for certainty. Fortunately I thought of the fact that some could override the OPT variable.

**Comment by lcn2** [comment]
Oh gee, but not too 😄 @xexyl

**Comment by xexyl** [comment]
I hope that didn't cause a problem. I got a late email and thought you had merged it so I did a git pull. Then I had to make a fix which seemed to work out. 

Let's hope so. If not I will fix it.

**Comment by lcn2** [comment]
Odd thing happened, this pull request had conflicts that we were forced to resolve.  We resolved then in favor of the 2nd form in 3 places involving 2 files.  You might wish to review, resend your repo and revise if needed, @xexyl.

**Comment by xexyl** [comment]
Thanks. I will do that. I just made a comment about what happened. I will check when back at the laptop and I will make corrections if necessary. 

Thanks for addressing it!

**Comment by xexyl** [comment]
> Thanks. I will do that. I just made a comment about what happened. I will check when back at the laptop and I will make corrections if necessary.
> 
> Thanks for addressing it!

Seems okay. Thanks again for taking care of it!

**Pull request merged**
