### PR TITLE
Fix 1991/rince and add two alt versions

### PR DESCRIPTION
**Pull request by xexyl**
The program was supposed to print a message that indicates whether you 
won or lost but it did not show up because of endwin() being called 
after it. To keep the code as close to the original as possible that 
part was left in but an additional call to printf() was made after 
endwin() is called.

The first alt version removes the maximum number of moves so that 
everyone can finish, even people not good at this kind of puzzle. The 
second alt version allows you to reconfigure (at compile time) the 
maximum number of moves even if you wish to make it harder to win.

Format fix README.md file.

At this time I believe the edits necessary for 1991/rince are complete.

### CODE REVIEW

**Comment by xexyl** [comment]
I had put this in bugs.md and then was about to commit and then it popped into my head what was wrong. I had already made the alt versions.


The curses ending and printing is one I took especial care to avoid in 2020/ferguson1.

I don't know how much more I'll get done today but I'm happy to have got the edits in that I did one of which I know is a tremendous help to you.

Unfortunately I am exhausted. Yesterday I had to have a long nap which is very unusual for me being able to. I don't know if that'll happen again today but it's possible.

Hope you had a nice sleep or if you're still asleep (which is more ideal given what hour you were up) I hope you're sleeping well.

**Comment by xexyl** [comment]
I'm afraid that this is all I will likely do  today. Don't feel like more editing right now. Kind of an off day. I do believe though that the mass edit to the README.md files will be of more use at this point than working on the files of 1991, at least temporarily. I hope so but I'll get back to 1991 tomorrow anyway.

I'm glad I got to do the alt code of this entry. Funny because I was just thinking about this entry the other day but I didn't know at the time that there would be anything to do with it, code wise, fix or alt code.

Sorry I can't do more right now. I might end up doing a bit more later on but I wouldn't count on it.

**Comment by lcn2** [comment]
Nice work, best wishes for the rest of your day @xexyl

**Comment by xexyl** [comment]
> Nice work, best wishes for the rest of your day @xexyl

You as well!

I did find where the crash is happening in 2000/dlowe in macOS btw ... can say more another time. Just taking it easy for now and probably the rest of the day.

**Pull request merged**
