### PR TITLE
Add FAQ entry about opening pull requests

### PR DESCRIPTION
**Pull request by xexyl**
This used commit afb9e54a4c9849a474782000d80239b7dcbb1f66 as an example
(an example commit and pull request was suggested to me by Landon).

Note that I did NOT update the html file as I am not clear how to do 
this (for the moment).

### CODE REVIEW

**Comment by xexyl** [comment]
Would you please tell me what command I should run to generate the html file ? Thanks. I can then do it or you can do it but then I'll know for future reference. Maybe a wrapper script could do it on all markdown files? Just a thought.

Have to go afk now. Might or might not do more later on but this is I think great progress. But did I miss anything?

BTW I started rereading LR again last night but that shouldn't matter for here.

**Comment by lcn2** [comment]
> Would you please tell me what command I should run to generate the html file ? Thanks. I can then do it or you can do it but then I'll know for future reference. Maybe a wrapper script could do it on all markdown files? Just a thought.
> 
> 
> 
> Have to go afk now. Might or might not do more later on but this is I think great progress. But did I miss anything?
> 
> 
> 
> BTW I started rereading LR again last night but that shouldn't matter for here.

Well `make www` will always do everything web page wise. 

And `make help` will remind you of the make rules that are used to build web site stuff.  In that top level `Makefile`, you will see comments with hints. 

The specific command you could use to build top level things like the `faq.html` file is `make gen_top_html`.

Sometimes it is hard to remember what changes what, so `make quick_www` will try to build all web page stuff assuming that the file timestamps are up to date.  If in doubt about file timestamps, use the longer running `make www`. 

BTW: The build tarball rules is now separated from web page building. We **DO NOT** recommend running those tar rules at this time as this will only churn the git repo with needless large binary blob edits:

```
make form_entry_tarball
make form_year_tarball
make form_all_tarball
make tar
```

As mentioned above, none of the make rules that build web page stuff change the tar files. 

We hope this helps.

**Comment by lcn2** [comment]
FAQ thanks 🙏 @xexyl  .. riding in a car 🚙 to get to the station 🚉 so we didn't have a change to view the result.

**Comment by xexyl** [comment]
> FAQ thanks 🙏 @xexyl .. riding in a car 🚙 to get to the station 🚉 so we didn't have a change to view the result.

Thanks for the reminder of the rules. I updated the faq.html file. Safe travels!

**Pull request merged**
