### PR TITLE
Fix 1996/westley

### PR DESCRIPTION
**Pull request by xexyl**
It always segfaulted (though with the correct input it still showed the
right results) and when argc == 1 it showed an environmental variable.

The body of the for loop can now be empty (or so it appears). I put the
original in westley.alt.c because it has some interesting techniques in
which he wrote about (which I preserved in the README.md file). I also 
put in the original code because I'm not entirely sure if the for loop 
really can be empty in all cases. Certainly it can be in the scripts 
provided but I don't know if there is a valid invocation that would need
it (but in any case it would always segfault with that loop body).

Updated 1996/westley/.gitignore (added westley.alt) and the Makefile so
that make alt will build westley.alt.

Formatting fixes in README.md.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

You're very welcome my friend! This was a fun one to fix also. Like I said in the log I kept the original version as I'm not sure if the fix is always correct (even though not fixing it would lead to a segfault in every case). 

Plus it had some interesting techniques and I think that should be shown - that is part of the purpose of the contest too after all. 

Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?

**Comment by xexyl** [comment]
> > Thanks @xexyl
> 
> You're very welcome my friend! This was a fun one to fix also. Like I said in the log I kept the original version as I'm not sure if the fix is always correct (even though not fixing it would lead to a segfault in every case).
> 
> Plus it had some interesting techniques and I think that should be shown - that is part of the purpose of the contest too after all.
> 
> Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?

## QUESTION

Just so if you get a chance you see my question at the end there. I guess it's still helpful to highlight questions?

**Comment by lcn2** [comment]
> Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?

We do not think the alt version adds value to the presentation of the entry.  The " The original is in [westley.alt.c](westley.alt.c)" text in `README.md` could be removed with nil impact on the quality of the presentation of the entry.  On the other hand it doesn't hurt the presentation of the entry.  :-)

**Comment by xexyl** [comment]
> > Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?
> 
> We do not think the alt version adds value to the presentation of the entry. The " The original is in [westley.alt.c](westley.alt.c)" text in `README.md` could be removed with nil impact on the quality of the presentation of the entry. On the other hand it doesn't hurt the presentation of the entry. :-)

I guess that applies to the ones I did today too?

What would you like me to do? I will do it tomorrow morning. 

Just unwinding now.

**Comment by lcn2** [comment]
> > > Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?
> > 
> > 
> > We do not think the alt version adds value to the presentation of the entry. The " The original is in [westley.alt.c](westley.alt.c)" text in `README.md` could be removed with nil impact on the quality of the presentation of the entry. On the other hand it doesn't hurt the presentation of the entry. :-)
> 
> I guess that applies to the ones I did today too?
> 
> What would you like me to do? I will do it tomorrow morning.
> 
> Just unwinding now.

See commit f9748a1b157af760ab429b717af417651373a089: we can leave it there for now.

**Comment by xexyl** [comment]
> > > > Still I think the body of the for loop is not needed and so the only reason to have the original is to show what it once was, what worked and how it worked. What do you think ?
> > > 
> > > 
> > > We do not think the alt version adds value to the presentation of the entry. The " The original is in [westley.alt.c](westley.alt.c)" text in `README.md` could be removed with nil impact on the quality of the presentation of the entry. On the other hand it doesn't hurt the presentation of the entry. :-)
> > 
> > 
> > I guess that applies to the ones I did today too?
> > What would you like me to do? I will do it tomorrow morning.
> > Just unwinding now.
> 
> See commit [f9748a1](https://github.com/ioccc-src/temp-test-ioccc/commit/f9748a1b157af760ab429b717af417651373a089) and commit [c522203](https://github.com/ioccc-src/temp-test-ioccc/commit/c5222031154b282df249170620a84c144cd79f23): we can leave it there for now.

Thanks!

**Pull request merged**
