### PR TITLE
Typo fix file name in 2001/westley/westley.sh

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
> Yes @xexyl 

If you really want me to flood your terminal!

```sh
yes '@xexyl'
```

But I suspect that nobody really wants that :-)

**Comment by lcn2** [comment]
> > Yes @xexyl
> 
> If you really want me to flood your terminal!
> 
> ```shell
> yes '@xexyl'
> ```
> 
> But I suspect that nobody really wants that :-)

yes '@xexyl' | head -10

**Comment by xexyl** [comment]
> > > Yes @xexyl
> > 
> > 
> > If you really want me to flood your terminal!
> > ```shell
> > yes '@xexyl'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I suspect that nobody really wants that :-)
> 
> yes '@xexyl' | head -10

That works yes :-)

....but see how well `yes :-)` works unquoted (not that you don't know) :-)

Hopefully I can do more tomorrow. Just passing by. Hope you have a great night!

**Comment by xexyl** [comment]
As for yes I am reminded of the American sitcom Get Smart. 

There was a German character on the Kaos side and on the Control side an agent known as 99. 

99 said something to him and he replied 'nein, nein, 99'. 

It's my favourite one line reply. Well that might not be so true now but it's certainly one of my all time favourites. It's brilliant. 

No idea what makes me think of it and I think I've shared it with you before but it's brilliant enough to share again!

I have some questions about the top level README files but I am not sure if I will get to asking them today. More important to update you about the doctor and lab work etc. which I hope to do in a bit. But I am extremely tired so I apologise if I don't get to it until tomorrow!

**Comment by xexyl** [comment]
> As for yes I am reminded of the American sitcom Get Smart. 
> 
> There was a German character on the Kaos side and on the Control side an agent known as 99. 
> 
> 99 said something to him and he replied 'nein, nein, 99'. 
> 
> It's my favourite one line reply. Well that might not be so true now but it's certainly one of my all time favourites. It's brilliant. 
> 
> No idea what makes me think of it and I think I've shared it with you before but it's brilliant enough to share again!
> 
> 

I have some questions about the top level README files but I am not sure if I will get to asking them today. More important to update you about the doctor and lab work etc. which I hope to do in a bit. But I am extremely tired so I apologise if I don't get to it until tomorrow!

**Comment by xexyl** [comment]
> As for yes I am reminded of the American sitcom Get Smart. 
> 
> There was a German character on the Kaos side and on the Control side an agent known as 99. 
> 
> 99 said something to him and he replied 'nein, nein, 99'. 
> 
> It's my favourite one line reply. Well that might not be so true now but it's certainly one of my all time favourites. It's brilliant. 
> 
> No idea what makes me think of it and I think I've shared it with you before but it's brilliant enough to share again!
> 
> 

Another great German joke is what comes between fear and sex?'

'Fünf!' because eins zwei drei vier fünf sechs.

**Pull request merged**
