### PR TITLE
Minor fixes and adjustments to 2000/natori

### PR DESCRIPTION
**Pull request by xexyl**
Typo fix and added note about the alternate code earlier in the file to note what it's for (southern hemisphere). Also added questions to ponder for the users of the alternate code in the northern hemisphere.

### CODE REVIEW

**Comment by lcn2** [comment]
thanks @xexyl

**Comment by xexyl** [comment]
> thanks @xexyl 

Happy to help.

**Comment by lcn2** [comment]
> > thanks @xexyl
> 
> Happy to help.

Happy that you are helping and are well enough to help, @xexyl.

**Comment by xexyl** [comment]
> > > thanks @xexyl
> > 
> > 
> > Happy to help.
> 
> Happy that you are helping and are well enough to help, @xexyl.

Thank you **_VERY_ MUCH**!

My lungs seem to be clear or almost all clear if not. Today and the next few days I think will be difficult but after that I hope that I will be able to do more each day: though I still have fit some reading in of course.

I made a few fixes this morning but I'm hoping to rest soon for a bit. If I am to listen to my body however I would say the resting is impossible at least at this point. I might have a shower instead and maybe I can rest after that. But it will be a hard day and unless I get something done in the next hour or two I would say I'm extremely unlikely to do anything else today.

Now just because tomorrow and the next few days will be hard does not mean I won't be able to do anything it just means I might not be able to do as much: we shall see!

I left what I hope is a bit of encouraging good news in the typos issue and the consistencies issue though. I have fewer entries to go through before I can do a final pass! On the other hand I do have a file to go through with a list of tasks. Some of these are not necessary to go through before those two issues can be closed but some do need to be done first. I ended up removing one today as I actually did the task the other day.

Hope you're sleeping well and thank you for the very kind words above! I really do hope my lungs are finally clear or clear enough and that I will be able to do more once the next few days are over .. just in time for you to leave for your wonderful space event :-) ... which again I hope you have a great time and please do **STAY VERY SAFE!**

**Pull request merged**
