### PR TITLE
Remove duplicate INABIAF in 2020/burton/README.md

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
Lots of good cleanup and progress: thank you @xexyl

**Comment by xexyl** [comment]
> Lots of good cleanup and progress: thank you @xexyl

Happy to help. Just looking at comments in these merged pull requests and then I'll be off I think.

**Comment by xexyl** [comment]
> > Lots of good cleanup and progress: thank you @xexyl
> 
> Happy to help. Just looking at comments in these merged pull requests and then I'll be off I think.

Okay back tomorrow. Good day!

**Comment by xexyl** [comment]
> Lots of good cleanup and progress: thank you @xexyl

Happy to help. Just looking at comments in these merged pull requests and then I'll be off I think.

> > Lots of good cleanup and progress: thank you @xexyl
> 
> Happy to help. Just looking at comments in these merged pull requests and then I'll be off I think.

Okay back tomorrow. Good day!

**Comment by xexyl** [comment]
And I hope that makes sense but if it escaped you for a moment: removed duplicate info and now added some here :-)

**Pull request merged**
