### PR TITLE
Rename 1985/lycklama.orig.c -> 1985/lycklama.alt.c

### PR DESCRIPTION
**Pull request by xexyl**
Rename 1985/lycklama.orig.c -> 1985/lycklama.alt.c
    
Updated README.md to refer to the alt version instead. Note that it's
    there because it provides fun output and also shows how it originally
    looked (which is quite different from the fixed [for modern compilers]
    version that I believe I made in an earlier commit but if so I'm not
    sure which one).

### CODE REVIEW

**Comment by lcn2** [comment]
From what we can tell from the diff, there isn't a rule to compile the alt code:

```make
${PROG}.alt: ${PROG}.alt.c
	${CC} ${CFLAGS} $< -o $@ ${LIBS}
```

**Comment by lcn2** [comment]
Thanks 🙏 @xexyl

**Comment by xexyl** [comment]
> Thanks 🙏 @xexyl

Welcome.

**Comment by xexyl** [comment]
> From what we can tell from the diff, there isn't a rule to compile the alt code:
> 
> ```makefile
> ${PROG}.alt: ${PROG}.alt.c
> 	${CC} ${CFLAGS} $< -o $@ ${LIBS}
> ```

I think I only removed it from the one and since github shows the previous commits in later pull requests I figured you meant that one. 

I can certainly add this tomorrow.

**Comment by xexyl** [comment]
> > From what we can tell from the diff, there isn't a rule to compile the alt code:
> > ```makefile
> > ${PROG}.alt: ${PROG}.alt.c
> > 	${CC} ${CFLAGS} $< -o $@ ${LIBS}
> > ```
> 
> I think I only removed it from the one and since github shows the previous commits in later pull requests I figured you meant that one.
> 
> I can certainly add this tomorrow.



```sh
$ make alt
$
```

so it seems all is good here.

**Comment by xexyl** [comment]
> > > From what we can tell from the diff, there isn't a rule to compile the alt code:
> > > ```makefile
> > > ${PROG}.alt: ${PROG}.alt.c
> > > 	${CC} ${CFLAGS} $< -o $@ ${LIBS}
> > > ```
> > 
> > 
> > I think I only removed it from the one and since github shows the previous commits in later pull requests I figured you meant that one.
> > I can certainly add this tomorrow.
> 
> ```shell
> $ make alt
> $
> ```
> 
> so it seems all is good here.

Specifically because alt shouldn't be compiled, right? I mean it can't be compiled. But the rule still is there. That's correct, isn't it?

```makefile
ALT_OBJ=
ALT_TARGET=

# alternative executable
#
alt: ${DATA} ${ALT_TARGET}
        @${TRUE}
```

**Pull request merged**
