### PR TITLE
Change references of 'web site' to 'website'

### PR DESCRIPTION
**Pull request by xexyl**
As agreed on GitHub to be consistent this should be done. This commit 
changes 470 files. There are some files that have not had this change.
Some it might be okay to change but there is one that should certainly
not be changed. The files not changed are thus:

    2004/hibachi/src/localhost/index.htm

This could be changed but it is part of the entry is not strictly 
necessary.
    
    2011/dlowe/dlowe-aux-data/english-1/Wireless_Days_2011_CFP.txt

This should not be changed because it is part of the training data that 
was used in the entry.

Any files under tmp/ that also refer to 'web site' have not been changed 
as these files are going away.

### CODE REVIEW

**Comment by xexyl** [comment]
Did everything go through this time ? Hopefully so but if not I'll have to look deeper into the problem.

**Comment by xexyl** [comment]
Note that I must have hit command+s in manifest.numbers. Nothing has changed though. There's not even an undo queue. I must have just hit command + s when I saw the problem I noted elsewhere (that has to be fixed later), probably out of habit of saving files I am working on. So although it seems that it was committed nothing actually changed so there is no need to export to the CSV file.

Just so you know.

**Comment by lcn2** [comment]
Rejecting the commit as it has the same problems as the last time.

**Comment by lcn2** [comment]
See [comment-2154429741](https://github.com/ioccc-src/temp-test-ioccc/issues/2006#issuecomment-2154429741).

**Comment by xexyl** [comment]
> There seems to be a problem with changing 'web site' to 'website'.  Not sure what the problem is: it could be how GitHub is reporting a large pull request and that your pull request #2408 was OK. Sorry (tm Canada 🇨🇦), we are going to reject this pull request.
> 
> 
> 
> So as to not get stuck on this problem, see [comment-2154429741](https://github.com/ioccc-src/temp-test-ioccc/issues/2006#issuecomment-2154429741) and commit 6e698b238abd62c144729c7b6204ef0dbc004a14.

I do know when I was looking at the diff I had to wait a few seconds each time at the bottom of the page for more to load. Could that be the problem?

I will see if I can check the comment later on. Still waking up and it was a pretty bad night again.

**Comment by xexyl** [comment]
> > There seems to be a problem with changing 'web site' to 'website'.  Not sure what the problem is: it could be how GitHub is reporting a large pull request and that your pull request #2408 was OK. Sorry (tm Canada 🇨🇦), we are going to reject this pull request.
> > 
> > 
> > 
> > So as to not get stuck on this problem, see [comment-2154429741](https://github.com/ioccc-src/temp-test-ioccc/issues/2006#issuecomment-2154429741) and commit 6e698b238abd62c144729c7b6204ef0dbc004a14.
> 
> I do know when I was looking at the diff I had to wait a few seconds each time at the bottom of the page for more to load. Could that be the problem?
> 
> I will see if I can check the comment later on. Still waking up and it was a pretty bad night again. 
> 
> 

Yes it seems like I should have said that before: to wait a few moments. Because this commit is exactly what mine was like. 

(I just looked at the commit here.)

But hopefully if such a large set of files have to be modified in a single commit again you will now know the problem. 

I am unsure what I will get done today here. If I had to answer right now it would be 'nothing' but that very likely will change at least a little bit if not more than a little bit. 

I have to think about what to look at next. I thought it might be the entries' html files but I think it might be better to go through the top level html files that are not the bugs file and not the FAQ as those would be nice to get out of the way. Then the entries after that then those last two files. 

Anyway thanks for taking care of the seeming problem and now we know why I saw all files there and you thought maybe they weren't all there! Maybe GitHub should have a better visual cue or something for cases like this. Seems like it wasted our time - not just your time but my time twice. 

Hope you feel a great sleep!

**Comment by xexyl** [comment]
I just made a fix to your solving the problem: training data for 2011/dlowe was modified and it should not be quite obviously. This was the file that I discovered in my first attempt that I modified without realising that this commit avoided. See https://github.com/ioccc-src/temp-test-ioccc/pull/2409/commits/6a29841b303e4d1713aeb52300a2ff1da73162be.

**Pull request closed without merging**
