### PR TITLE
Add CSV files from SQL

### PR DESCRIPTION
**Pull request by xexyl**
The file auth-year-prizes.csv is in the form:

    # year_name_handle,award name

e.g.:

    2018_ferguson,Best use of weasel words
    2020_ferguson1,Don't tread on me award
    2020_ferguson2,Most enigmatic
    
and the person.csv file is in the form:
    
    
    # name,entry_handle,url,email,country,mastodon/twitter

e.g.:
    
    
    Cody Boone Ferguson,Cody_Boone_Ferguson,https://ioccc.xexyl.net,null,null,XX,https://fosstodon.org/@xexyl);

where 'XX' is the country (sometimes it's not just a country code but name - that might or might not need changing).
    
Above I made null my email for this log entry (even though it's public elsewhere in git). But these are just an example I'm most familiar with (however horribly shocking that might be! :-) ) to give the idea.

I'm the only one with a Mastodon handle; the others that are not null are twitter handles.

As far as how these were created:

    grep INSERT person.fixed.sql |sed -e 's,.*VALUES(,,g' -e "s/'//g"|awk -F, \
     '{ print $1,$2","$3","$4","","$6","$7","$8 }' |sed -e 's/NULL/null/g' -e  \
    "s/,,/,null,/g" | sort > person.csv.txt
    
     
(I changed the single sql file to several and then made some manual fixes.)

Similar was done for the other file.

There certainly is room for improvement and it definitely needs some fixes. This was a quick hack but it's a good start.

### CODE REVIEW

**Comment by xexyl** [comment]
32 pull requests! A power of 2!

Which brings up the joke (that's not mine) that I think I might have shared with you before:

--

Once Heracles was walking by a lake and there he saw Hydra. He ran up to her and cut her single head off. But instead of one head two more grew. Heracles cut them off too but 4 more appeared. He cut the 4 heads off - and there were 8 heads... So passed one hour, two hours, three hours...

And then Heracles cut Hydra's 32768 heads off and Hydra died for she was 16-bit.

--

**Comment by xexyl** [comment]
.. leaving for the day. I would like to actually do more pull requests today for my game but I have other things I should do. I'll do more tomorrow most likely format fixes in README.md files.

Take good care!

**Comment by xexyl** [comment]
Oh btw: funny thing. When I went to push this to GitHub I tried to push branch cvs. For a moment I was confused why I got an error and then I noticed what I had typed! I used to use CVS a lot so that's probably why.

**Comment by lcn2** [comment]
**THANKS!**

**Comment by xexyl** [comment]
> THANKS!

WELCOME!

**Comment by xexyl** [comment]
… got an email from my server cronjob that I set up to check for disk failures and yet again the new backup drive partition 1 is having errors. Considering that it made me lose my 311 days uptime I am really unhappy. I tried fsck and that found lots of errors and fixed them but I guess now it’s time to format it. Hopefully that will solve the problem. If it doesn’t I might have to send the drive back and then I will be very unhappy. 

I looked at the prices for RDX drives and cartridges and they are much more expensive and after Lily’s surgery I have to be careful for a bit. So I can’t really afford a proper backup drive now: just a USB drive. 

Then there’s the fact that there’s another iPadOS update and every time that happens I have to remove music on it and then transfer it back … going to have to get a new one sooner than later but with increased capacity. This iPad was the first generation iPad Pro but it was a gift so only 64GB. 

The iPhone 14 Pro Max that I bought last year is 1TB. The MacBook Pro Max with the M1 chip I of course got 8TBs. The old phone is 256GB. 

Well these are all asides but things that I have to concern myself with at least. I am going to boot up the laptop and start the server maintenance and then I will go through these pull requests and then I hope that I can do more here!

I hope that you’re having a great day!

**Comment by xexyl** [comment]
> … got an email from my server cronjob that I set up to check for disk failures and yet again the new backup drive partition 1 is having errors. Considering that it made me lose my 311 days uptime I am really unhappy. I tried fsck and that found lots of errors and fixed them but I guess now it’s time to format it. Hopefully that will solve the problem. If it doesn’t I might have to send the drive back and then I will be very unhappy.
> 
> I looked at the prices for RDX drives and cartridges and they are much more expensive and after Lily’s surgery I have to be careful for a bit. So I can’t really afford a proper backup drive now: just a USB drive.
> 

... or not: the state is D again .. I know what process at least but why it's happening is beyond me. But of course I have a cat between my legs so I can't go hard reboot the server :( ... so it's going to flood the logs for some hours more. I also remembered the macOS update so I'll take care of that and then clean up the branches. Then I'll do more here. Later on I'll hopefully fix the server problem.

**Pull request merged**
