### PR TITLE
Fix redundancy in 1989/jar.2/chocolate_cake.lisp

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
We don't understand this fix. Please 🙏 explain if you will @xexyl

**Comment by xexyl** [comment]
> We don't understand this fix. Please 🙏 explain if you will @xexyl 

There was a line that had something like hexa_layered and then below it it had the word layered also so the redundancy was it said layered twice!

**Comment by xexyl** [comment]
I will respond to your other replies later on .. might try showering and then maybe my body will be able to sleep again. But I will get to them this morning. 

Hope you're sleeping well!

**Comment by xexyl** [comment]
> > We don't understand this fix. Please 🙏 explain if you will @xexyl 
> 
> There was a line that had something like hexa_layered and then below it it had the word layered also so the redundancy was it said layered twice!
> 
> 

Too bad it didn't say chocolate twice or thrice or ... that might be okay!

**Pull request merged**
