### PR TITLE
Fixes for recent commits

### PR DESCRIPTION
**Pull request by xexyl**
The Makefile.example file now has the ALT_OBJ and ALT_TARGET (with a comment explaining how to use it) and the alt rule (which if the variables are left empty it will do nothing with 'make alt' or 'make everything').

The example Makefile now has the everything rule as well, for those who have an alt target.

Fix links to next/try.sh, next/try.alt.sh and next/Makefile.example in html files (guidelines/rules/FAQ) to not link to GitHub as they're supposed to be downloaded.

### CODE REVIEW

**Comment by xexyl** [comment]
Hopefully this sorts things out. Have to go now. Let me know if you see anything that could be fixed/improved.

**Review by lcn2 — COMMENTED** [review]
Not sure some of the changed paths will work well. We need to check this before we consider accepting this PR.

**Comment by lcn2** [comment]
> > Not sure some of the changed paths will work well. We need to check this before we consider accepting this PR.
> 
> > 
> 
> > ## UPDATE 0
> 
> > We will need to find the time to test things first.
> 
> 
> 
> I actually wondered about some. I was not sure if some of them should link to GitHub or should be downloaded. But since they were in the guidelines and those are to be used I opted for downloading them. But I'm happy to update the ones you think might be better linked to GitHub. Though that might not happen until tomorrow.
> 
> 
> 
> Thanks for checking into it.

Regarding the excellent question raised in [GH-issuecomment-2518269646](https://github.com/ioccc-src/temp-test-ioccc/pull/2761#issuecomment-2518269646):

At issue are links to:

- next/try.sh
- next/try.alt.sh
- next/Makefile.example

For these files, there is a need to download the file **AND** there is a need to view the file. 

To view the file, a link to the GitHub path is next.  To download the file, a local URL with and appropriate HTML magic 🪄 to specify the target 🎯 to download is needed.  

We don't think this is a general issue with files. Instead it is limited to just those 3 listed above.

Perhaps what is needed is for the PR to be modified so that there is a clear "downloading" link as well as a "viewing" link.  The "downloading" link would use appropriate HTML magic 🪄 to specify the target 🎯 to download and the "viewing" link would access the GitHub repository URL.

**Comment by xexyl** [comment]
Oh I like that idea.

The question is what should it look like? I could see it something like...

<hr>
We recommend that you use the `[example Makefile](GitHub link) ([download here[(Makefile.example))`.
<hr>

or something like that?

But I don't know. I don't think emojis are useful though. Certainly I wouldn't be able to determine what they mean and in the rare case that there is someone using a screenreader it would not help them.

Of course it could also be the reverse. Something like:

<hr>
We recommend that you use the `[example Makefile](Makefile.example) ([view on GitHub](...))`.
<hr>

**Comment by xexyl** [comment]
Another important question: which files should this be done in? FAQ? Probably the guidelines and rules but what about FAQ? Or do I have that wrong? If you get back to me on these things I'd be happy to adjust it - but it might not be until tomorrow.

**Comment by lcn2** [comment]
> Oh I like that idea.
> 
> The question is what should it look like? I could see it something like...
> 
> We recommend that you use the [example Makefile](GitHub link) ([download here[(Makefile.example)).
> or something like that?
> 
> But I don't know. I don't think emojis are useful though. Certainly I wouldn't be able to determine what they mean and in the rare case that there is someone using a screenreader it would not help them.
> 
> Of course it could also be the reverse. Something like:
> 
> We recommend that you use the [example Makefile](Makefile.example) ([view on GitHub](...)).

Something like that, or perhaps explicit bullet list is even better as the text might get lost to some who quickly glance and prefer not to read too much.

For example:

```
... stuff ...

We recommend that you start with our example Makefile:

- [view example Makefile](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/Makefile.example)
- <a href="next/Makefile.example" download="Makefile">download example Makefile</a>

... stuff ...
```

In the above HTML, the use of a 2 line bullet list makes the distinction between viewing and download clear.    It stands out clearly form the rest of the text and is much more likely to catch the attention of those with a short attention span.  The use of an explicit HTML for the download is needed because the `download="Makefile"` will cause the name of the download file to be `Makefile` and not _Makefile.example_.  In fact, the actual name _Makefile.example_ is not even mentioned: only the function of viewing or download an example Makefile.

There is clean and clear use of whitespace.  So it looks like this:

... stuff ...

We recommend that you start with our example Makefile:

- [view example Makefile](https://github.com/ioccc-src/temp-test-ioccc/blob/master/next/Makefile.example)
- <a href="next/Makefile.example" download="Makefile">download example Makefile</a>

... stuff ...

Our point is that the use of whitespace and clean simple dual bullet list make is easier to quickly look at and understand a dual view/download link pair.

Of course, in the context of this GitHub comment, the above "<a href="next/Makefile.example" download="Makefile">download example Makefile</a>" **WILL NOT WORK**.   However once the markdown file is processed by `pandoc(1)`, the resulting HTML should (hopefully) work.

We recommend that this PR be modified accordingly places where these files are referenced and a dual view/download link pair is needed:

* next/try.sh
* next/try.alt.sh
* next/Makefile.example

**Comment by xexyl** [comment]
I can do that - tomorrow. That works well enough for me. Must leave now. Good day!

**Comment by xexyl** [comment]
Making progress but I took a break. I'm going to look at it again and will then commit.

**Comment by xexyl** [comment]
See if this does it. Feel free to let me know if anything else needs fixing .. though I have other things to do now.

**Review by lcn2 — APPROVED** [review]
thank you @xexyl

**Pull request merged**
