### PR TITLE
Typo fix in FAQ

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I noticed some other things but this is all I'll end up doing for the day I'm afraid.

**Comment by xexyl** [comment]
.. okay I have a minor bug fix in one of the `bin/` scripts too but have to run `make www` to make sure all is okay first .. but that's all I'll do today.

**Comment by lcn2** [comment]
Thanks 🙏 @xexyl 

Hope your recovery is progressing nicely.

**Comment by xexyl** [comment]
> Thanks 🙏 @xexyl 
> 

You are most welcome. 

> Hope your recovery is progressing nicely. 

Thank you! It's coming along. Still difficult but each day is a bit better. Today has been rough. But what is really bothersome is that I have been so sleepy in the day. Sleepy but unable to sleep. I might try going to sleep a little bit earlier. See if that helps. Not that I go to bed late anyway but maybe going to sleep earlier than I have been (which is later than it had been) will help. 

I know I have numerous comments to reply to but I am afraid those are for another day. Thank you for the kind wishes!

**Pull request merged**
