### PR TITLE
Add 2018/hou/try.sh + format/typo checks

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
So four entries of 2018 are now done.

**Comment by xexyl** [comment]
`2018/mills` is going to take some time and work to do to make sure everything looks good. Well you know why. It's an incredible piece of work.

I'm aware of at least two where I have to bring something up. I'm not sure about the others yet. I'll be going afk soon for a bit most likely.

**Comment by xexyl** [comment]
I see 2018/bellard calls for a new FAQ entry too - about ImageMagick. Pretty sure we don't have anything about that there. Once this is done other entries that make use of it should also refer to that FAQ.

**Comment by lcn2** [comment]
Nice 2018 progress, @xexyl 

In the matter of `2018/bellard` tools: If they are complex tools, or they are semi-complex tools that other people currently maintain, it might be better to go the FAQ route instead of trying to embed them into the `2018/bellard/` directory.  If we do not have to maintain and support a complex tool, or if someone else maintains a semi-complex tool it will be much better to point to such tools via the FAQ.  Of course if they are trivial tools such as a shell script, then embedding them into the `2018/bellard/` directory is better.

**Comment by xexyl** [comment]
> Nice 2018 progress, @xexyl
> 
> In the matter of `2018/bellard` tools: If they are complex tools, or they are semi-complex tools that other people currently maintain, it might be better to go the FAQ route instead of trying to embed them into the `2018/bellard/` directory. If we do not have to maintain and support a complex tool, or if someone else maintains a semi-complex tool it will be much better to point to such tools via the FAQ. Of course if they are trivial tools such as a shell script, then embedding them into the `2018/bellard/` directory is better.

Yes I meant the FAQ. JPEG tools, ImageMagick and others are missing from the FAQ.

**Comment by xexyl** [comment]
> Nice 2018 progress, @xexyl

Thanks!

**Pull request merged**
