### PR TITLE
Remove unbeaten for ... text in faq.html

### PR DESCRIPTION
**Pull request by xexyl**
This is because each year it will be outdated and it was already outdated by 23 (!!) years (2023 - (1988+12)).

### CODE REVIEW

**Comment by lcn2** [comment]
Likewise for this Makefile, the alt rule should still exist in empty form:

```make
# alternative executable
#
alt: data ${ALT_TARGET}
	@${TRUE}
```

Please issue an appropriate follow up pull request, @xexyl

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

You are most welcome.

**Comment by xexyl** [comment]
> Likewise for this Makefile, the alt rule should still exist in empty form:
> 
> ```makefile
> # alternative executable
> #
> alt: data ${ALT_TARGET}
> 	@${TRUE}
> ```
> 
> Please issue an appropriate follow up pull request, @xexyl

That was the same Makefile but just how GitHub displays it so it should be done already with the open pull request?

**Pull request merged**
