### PR TITLE
Update several of the files from 2015

### PR DESCRIPTION
**Pull request by xexyl**
With all README.md files I changed the copyright years to refer not to 2016 but 2015 as the year was 2015 and 2016 did not even have a contest.

I fixed formatting and some typos in a few of the README.md files but mostly the changes are the copyright years.

As a reminder to myself I have only looked at (counting those of commit fa31f80b39fb310024695074f92d229389806f4e) burton, dogon, duble and part of endoh1. The rest will come in a future commit or maybe commits.

### CODE REVIEW

**Comment by xexyl** [comment]
With a23d24f:

Fix 2015/endoh3/README.md

Fix dead link. Apout is no longer available at the location in the README.md. Instead it's on GitHub. I checked it and it's the same author, Warren Toomey of TUHS so I know it's good (or at least the program is: not sure if the repo is owned by him).

Format fixes.

Fix ioccc.org link (though it shouldn't be necessary since mullender.c is actually in the repo).

...

it appears that Warren does not own that repo though .. didn't really look other than the README.md saying it was his and recognising the commands (I have a copy of the archive .. shared some funny things from it with you a while back too).

**Comment by xexyl** [comment]
Have to leave for the day. At least I don't think I'll be able to do more later.

Will do more tomorrow. Good day!

**Comment by lcn2** [comment]
Good!

**Comment by xexyl** [comment]
> Good!

You are most welcome.

**Pull request merged**
