### PR TITLE
Fix 2020/ferguson1/Makefile

### PR DESCRIPTION
**Pull request by xexyl**
The DATA variable still had html files which I removed a while back. This made make fail.

Also there is a joke Easter egg that I added: something to do with eating as that's also kind of the point of the entry: though eating insects (or bugs for a joke I made originally, so that it can say there are bugs that are not bugs). Snakes are carnivores: they don't eat apples and although insects are not going to be filling enough they can eat them. But what the joke is one has to discover for themselves!

### CODE REVIEW

**Comment by xexyl** [comment]
I quite like the Easter egg I added. There's even a pun with that word: snakes eat eggs! Do you see it? I guess you do but it's a fun one. I would be delighted to find it as another person.

Really off now .. will do more tomorrow.

**Comment by lcn2** [comment]
🥪😀@xexyl

**Comment by xexyl** [comment]
> 🥪😀@xexyl

image

Bonus points if you recognise where I got the first part from! Hint: late 1980s film.

**Comment by xexyl** [comment]
And going to bed now. Will hopefully be able to do more tomorrow. Glad you got a laugh out of the joke that I added though I guessed that you would. Good night!

**Comment by xexyl** [comment]
It was Lethal Weapon btw: the hilarious scene where Martin Riggs is called crazy and he shows them crazy slapping himself and then them before showing them his gun and saying that his badge is real and so is the firearm. 

But maybe you did recognise it? I am going to try sleeping again and then I will be back and try and reply to the comments. 

Hope you're sleeping well!

**Pull request merged**
