### PR TITLE
Restore 1998/schweikh2 original code

### PR DESCRIPTION
**Pull request by xexyl**
By some chance the original code that was restored as schweikh2.orig.c 
was not the original. This has been fixed by copying it from the
archive. The file that is being updated is almost like my fix (which 
solves a gcc internal compiler error).

### CODE REVIEW

**Comment by xexyl** [comment]
Okay now I really am leaving for the day .. will do more tomorrow.

**Comment by lcn2** [comment]
Good restore 👍 @xexyl

**Comment by xexyl** [comment]
> Good restore 👍 @xexyl

Fortunately I found it. I'm not even sure how.

**Comment by xexyl** [comment]
.. apparently I have other fixes for this entry - in the README.md file. I'll commit those tomorrow morning.

**Pull request merged**
