### PR TITLE
Make 1989/fubar more like original

### PR DESCRIPTION
**Pull request by xexyl**
There's no need to have the 'cc' macro have 'int ' before main. Instead
have CSILENCE include '-Wno-implicit-int'.

### CODE REVIEW

**Comment by xexyl** [comment]
I'm not done here but I am going afk again .. not sure if I'll get back to this today or not.

**Comment by xexyl** [comment]
> I'm not done here but I am going afk again .. not sure if I'll get back to this today or not.

... well this commit is done of course but I'm not done looking this one over.

**Comment by xexyl** [comment]
Okay going afk again ... will look back here another time.

**Comment by xexyl** [comment]
With the new script I can go to the next one .. not sure if I'll work on any more entries today though. If I do it's likely it won't be for much longer.

**Comment by lcn2** [comment]
How original 🤓 @xexyl

**Comment by xexyl** [comment]
> How original 🤓 @xexyl

Almost an original print. Or file.

**Pull request merged**
