### PR TITLE
Add 1994/horton/try scripts and article cited

### PR DESCRIPTION
**Pull request by xexyl**
The try.sh and try.alt.sh scripts correspond to the original entry and the alt code (which is enhanced).

The PDF files might need a bit more explaining. The author wrote an article in 'The USENIX Association Newsletter ;login: September / October 1992 Vol. 17, No. 5' (the exact title from the PDF) called 'Using GraphTab'. I found the full newsletter in the Internet Wayback Machine which is now added to the repo (okay: the newsletter as a PDF is added to the repo, not the Internet Wayback Machine :-) ). But the pages cited are 28-31 so I extracted (with macOS Preview app: File -> Print option) the specific pages so one need not look at the full newsletter if they do not wish to. It felt better to have the PDF rather than images as it's easier to deal with what the right size is: the size is there and one can zoom in or out as they see fit (whereas with images different resolutions make it easier or harder to see what is in them).

### CODE REVIEW

**Comment by xexyl** [comment]
Since the alt code is enhanced should we suggest using it first?

**Comment by lcn2** [comment]
> Since the alt code is enhanced should we suggest using it first?

Yes

**Comment by xexyl** [comment]
> > Since the alt code is enhanced should we suggest using it first?
> 
> Yes

Will do .. for now I have to go afk again. I'll be back later on.

**Comment by xexyl** [comment]
Hmm I wonder something, @lcn2, about this. The enhanced version is unobfuscated. Do we still want to suggest it first? I had the idea that it could say something about we recommend one try (as in USE) the alt version but when looking at the code one should look at the original.

What do you think ?

**Comment by lcn2** [comment]
> Hmm I wonder something, @lcn2, about this. The enhanced version is unobfuscated. Do we still want to suggest it first? I had the idea that it could say something about we recommend one try (as in USE) the alt version but when looking at the code one should look at the original.
> 
> What do you think ?

Good point, lets not reorder it then.

**Pull request merged**
