### PR TITLE
Update FAQ about gets() -> fgets() change

### PR DESCRIPTION
**Pull request by xexyl**
I gave example output of a program where not changing it caused 
confusing output, particularly in macOS, which is one of the strongest
reasons to make the change as it affects usability (in that it can make 
one wonder what to do albeit probably briefly so).

### CODE REVIEW

**Comment by xexyl** [comment]
19 pull requests: a prime number. This will be changing momentarily but it's at least prime time (not that this commit even references `time(3)` :-) ) for a moment :-)

**Comment by lcn2** [comment]
A bit more cell service: thanks 🙏 @xexyl

**Comment by lcn2** [comment]
Yea 🎉 thanks for this time 😁 @xexyl

**Comment by xexyl** [comment]
> Yea 🎉 thanks for this time 😁 @xexyl

Of course. And it's a lot easier than the alternatives at least.

**Pull request merged**
