### PR TITLE
Add try scripts to 2020/ferguson2, other updates

### PR DESCRIPTION
**Pull request by xexyl**
The try.sh script is for the original entry. The try.alt.sh is of course
for the alt version that I only recently made.

Removed html files recode.html and chocolate-cake.html (the horror! But 
there is the markdown file so all is good... or would be if it wasn't 
for the fact it's enciphered as a fun way to experience the entry .. or
else otherwise a frustration if there wasn't 
2020/ferguson1/chocolate-cake.md? :-) ).

Updated .gitignore.

Minor updates to chocolate cake file: but of course for most people they
might want 2020/ferguson1/chocolate-cake.md instead.

This should be all that needs to be done for 2020/ferguson2 - for now 
anyway. The documentation has not been checked for typos/formatting but
that might happen another time.

### CODE REVIEW

**Comment by xexyl** [comment]
Now truly just 11 more entries to go! I will of course do a very quick final pass to see if any entries should have a script to simplify trying the entry but that doesn't have to happen right away and if it doesn't happen at all it's also okay: the vast majority do.

I doubt very much that I'll finish 2020 today but I hope to this weekend. If I don't manage it'll be next week some time for sure. Tomorrow I have to do some housework as well as a couple people will be here for the holiday (and it's about time I did it anyway .. been meaning to but haven't got to it for various reasons).

**Comment by lcn2** [comment]
> Now truly just 11 more entries to go! I will of course do a very quick final pass to see if any entries should have a script to simplify trying the entry but that doesn't have to happen right away and if it doesn't happen at all it's also okay: the vast majority do.
> 
> 
> 
> I doubt very much that I'll finish 2020 today but I hope to this weekend. If I don't manage it'll be next week some time for sure. Tomorrow I have to do some housework as well as a couple people will be here for the holiday (and it's about time I did it anyway .. been meaning to but haven't got to it for various reasons).

Did you consult with the author on these modifications?  😄

Nice progress @xexyl 👍

**Comment by xexyl** [comment]
> Did you consult with the author on these modifications? 😄

I'm afraid not but the voices in his head suggested that it's okay. We have a telepathic communication, the two of us. Some think we're as mad as a box of frogs but we don't care. We know it's real. They're just jealous toads.

> 
> Nice progress @xexyl 👍

Thanks! I'm hoping to do another entry now or rather finish it. Not sure how many more I can get done today but we'll see.

**Comment by xexyl** [comment]
> > Now truly just 11 more entries to go! I will of course do a very quick final pass to see if any entries should have a script to simplify trying the entry but that doesn't have to happen right away and if it doesn't happen at all it's also okay: the vast majority do.
> > I doubt very much that I'll finish 2020 today but I hope to this weekend. If I don't manage it'll be next week some time for sure. Tomorrow I have to do some housework as well as a couple people will be here for the holiday (and it's about time I did it anyway .. been meaning to but haven't got to it for various reasons).
> 
> Did you consult with the author on these modifications? 😄
> 
> Nice progress @xexyl 👍

Thanks! I'm hoping to do another entry now or rather finish it. Not sure how many more I can get done today but we'll see.

**Comment by xexyl** [comment]
Just making sure you saw [comment 1866834583](https://github.com/ioccc-src/temp-test-ioccc/pull/1767#issuecomment-1866834583) since I think you'll find it funny and we can all use laughs even when we have them all the time :-) .. hope you're sleeping well.

**Pull request merged**
