### PR TITLE
Minor fixes in sgit/README.md

### PR DESCRIPTION
**Pull request by xexyl**
Change './sgit' to just 'sgit'.

Remove space at end of lines.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Welcome. Should there be a way to do a clone like there is in the other repo with some of the tools ? I'm not suggesting it - it just might be something to consider. Or not. I am happy to always make new pull requests and I probably would do it anyway since I would know when it's been updated.

Well anyway either way not for now. Hope you have a great day!

**Comment by lcn2** [comment]
> Should there be a way to do a clone like there is in the other repo with some of the tools 

We suggest you MOVE the tool to your own repo.

The tool can stand on its own and doesn't need to also live in the mkiocccentry at the same time as sgit isn't required to compile/build the code.

**Comment by xexyl** [comment]
> > Should there be a way to do a clone like there is in the other repo with some of the tools
> 
> We suggest you MOVE the tool to your own repo.
> 
> The tool can stand on its own and doesn't need to also live in the mkiocccentry at the same time as sgit isn't required to compile/build the code.

I think I wasn't clear. I don't think it should be in mkiocccentry either. I was only saying that that repo has a clone rule for other repos that it uses. This repo might too. But as I was saying it doesn't really matter. So forget the idea because whatever the case I have to do something and copying isn't any slower or harder than otherwise.

**Comment by xexyl** [comment]
> > > Should there be a way to do a clone like there is in the other repo with some of the tools
> > 
> > 
> > We suggest you MOVE the tool to your own repo.
> > The tool can stand on its own and doesn't need to also live in the mkiocccentry at the same time as sgit isn't required to compile/build the code.
> 
> I think I wasn't clear. I don't think it should be in mkiocccentry either. I was only saying that that repo has a clone rule for other repos that it uses. This repo might too. But as I was saying it doesn't really matter. So forget the idea because whatever the case I have to do something and copying isn't any slower or harder than otherwise.

In other words: nothing needs to be done. Just pretend I didn't bring it up.

**Comment by lcn2** [comment]
> I think I wasn't clear. I don't think it should be in mkiocccentry either. I was only saying that that repo has a clone rule for other repos that it uses. This repo might too. But as I was saying it doesn't really matter. So forget the idea because whatever the case I have to do something and copying isn't any slower or harder than otherwise.

The `sgit` tool is probably good to be in its own repo.

You are correct that sgit doesn't belong as part of the mkiocccentry repo.

The new sgit repo can use a Makefile to install the tool for use with various repos.

**Comment by xexyl** [comment]
> > I think I wasn't clear. I don't think it should be in mkiocccentry either. I was only saying that that repo has a clone rule for other repos that it uses. This repo might too. But as I was saying it doesn't really matter. So forget the idea because whatever the case I have to do something and copying isn't any slower or harder than otherwise.
> 
> The `sgit` tool is probably good to be in its own repo.
> 
> You are correct that sgit doesn't belong as part of the mkiocccentry repo.
> 
> The new sgit repo can use a Makefile to install the tool for use with various repos.

Already all done. Thanks.

**Pull request merged**
