### PR TITLE
Improve discussion of gets()/fgets() in FAQ/thanks

### PR DESCRIPTION
**Pull request by xexyl**
It is not yet clear to me if some of the information in the two files 
should be swapped. I think it probably should be done as the point in 
the thanks file was to be a quick note but it ended up being long and 
with details better left to the FAQ. But this can be done another time 
after the remaining entries are reviewed or sometime in between.

### CODE REVIEW

**Comment by xexyl** [comment]
Okay now I can get back to the entries of 2005 .. possibly after a break. I hope to get a number of the entries in 2005 done today but whether I finish it or not I can't say. I hope to but it's one of those days.

But yes I'm going to take a break now. Back in a while!

**Comment by xexyl** [comment]
It looks like I've done 5 entries of 2005 out of 15. I doubt I'll get the last 10 done today but maybe we'll luck out. If not I hope to at least get 5 done. Some are shorter than others and there is a chance that some don't need anything at all (I recall there might be one such thing in this year) and that speeds things up too.

I'll be able to resume in a bit .. have to do some other things first but thought you'd like a status update.

**Comment by lcn2** [comment]
> It is not yet clear to me if some of the information in the two files
> should be swapped. I think it probably should be done as the point in
> the thanks file was to be a quick note but it ended up being long and
> with details better left to the FAQ

Our guess is that we disagree as to the need to swap text between the thanks file and the FAQ. 

The FAQ should discuss things at a high level. 
The FAQ should avoid going into specifics about certain entries or individuals unless it is really necessary. This is because the FAQ is talking about the IOCCC at a high level.

People usually come to the FAQ to seek answers to issues that cover the whole IOCCC, or something related to the IOCCC at a general/high level. 

The thanks file is where individuals should be thanked for efforts made on behalf of a particular IOCCC winner. The FAQ, on the other hand, shouldn't mention specific people unless it is really necessary (such as FAQ0.0 must do). 

If there is content in the thanks file that suggests creating a new FAQ entry, and such a FAQ can be written to address the overall IOCCC, then adding a new FAQ might be appropriate. As was requested by several people, thanking specific individuals for their input is better left to the thanks file.  Here we have done a good job and should continue this practice.

The FAQ should try to avoid detailed questions about a specific entry.  One could have a FAQ about "What is the smallest source code that has won the IOCCC?" and give the answer along with referencing the 5 smallest IOCCC source codes. This is because the FAQ question covers the whole IOCCC. Only the answer needs to be a specific entry answer even then goes into mentioning some other nearly smallest entires: thus making the answer less about a specific entry.

Yes, the above is a suggestion for a new FAQ. 😉. 

IOCCC trivia questions that focus on the whole IOCCC, might be good FAQs (such as the above example of the smallest source code) even though their answers might point to a specific entry. Even then the answer could be made a bit more broad by mentioning a some nearly smallest winners. 

A particular question about a particular entry, **if that question was of common interest**, is probably better raised and answered in the "judges section" of the `README.md` of the particular entry.

**Comment by lcn2** [comment]
> I'll be able to resume in a bit .. have to do some other things first but thought you'd like a status update.

Thanks @xexyl for the status update.

**Comment by xexyl** [comment]
> > It is not yet clear to me if some of the information in the two files
> > should be swapped. I think it probably should be done as the point in
> > the thanks file was to be a quick note but it ended up being long and
> > with details better left to the FAQ
> 
> Our guess, @xexyl, is that we might disagree somewhat as to the need to swap text between the thanks file and the FAQ.
> 
> The FAQ should discuss things at a high level. The FAQ should avoid going into specifics about certain entries or individuals unless it is really necessary. This is because the FAQ is talking about the IOCCC at a high level.
> 
> People usually come to the FAQ to seek answers to issues that cover the whole IOCCC, or something related to the IOCCC at a general/high level.
> 
> The thanks file is where individuals should be thanked for efforts made on behalf of a particular IOCCC winner. The FAQ, on the other hand, shouldn't mention specific people unless it is really necessary (such as FAQ0.0 must do).
> 
> If there is content in the thanks file that suggests creating a new FAQ entry, and such a FAQ can be written to address the overall IOCCC, then adding a new FAQ might be appropriate. As was requested by several people, thanking specific individuals for their input is better left to the thanks file. Here we have done a good job and should continue this practice.
> 
> The FAQ should try to avoid detailed questions about a specific entry. One could have a FAQ about "What is the smallest source code that has won the IOCCC?" and give the answer along with referencing the 5 smallest IOCCC source codes. This is because the FAQ question covers the whole IOCCC. Only the answer needs to be a specific entry answer even then goes into mentioning some other nearly smallest entires: thus making the answer less about a specific entry.
> 
> Yes, the above is a suggestion for a new FAQ. 😉.
> 
> IOCCC trivia questions that focus on the whole IOCCC, might be good FAQs (such as the above example of the smallest source code) even though their answers might point to a specific entry. Even then the answer could be made a bit more broad by mentioning a some nearly smallest winners.
> 
> A particular question about a particular entry, **if that question was of common interest**, is probably better raised and answered in the "judges section" of the `README.md` of the particular entry.

I did say I wasn't sure! :)

Please put your suggestion in the TODO, perhaps linking to the comment.

**Comment by xexyl** [comment]
I'll reply to the above long comment in a moment ... more details.

**Comment by xexyl** [comment]
> > It is not yet clear to me if some of the information in the two files
> > should be swapped. I think it probably should be done as the point in
> > the thanks file was to be a quick note but it ended up being long and
> > with details better left to the FAQ
> 
> Our guess, @xexyl, is that we might disagree somewhat as to the need to swap text between the thanks file and the FAQ.
> 

I'll try clarifying anything in this comment.

> The FAQ should discuss things at a high level. The FAQ should avoid going into specifics about certain entries or individuals unless it is really necessary. This is because the FAQ is talking about the IOCCC at a high level.
> 

That makes sense .. kind of. In some cases it might be useful like mullender. That being said I wasn't referring to (in this case) that so much as the problem at hand, not entries itself. I think an entry I listed is a good example that is useful in the FAQ though and it's there. In other words I was thinking that the FAQ might have more to say about the change itself rather than entries that have had this change.


> People usually come to the FAQ to seek answers to issues that cover the whole IOCCC, or something related to the IOCCC at a general/high level.

Yes. That's what my thinking would address. It wouldn't be entirely swapped. Just some parts of it - if useful.
> 
> The thanks file is where individuals should be thanked for efforts made on behalf of a particular IOCCC winner. The FAQ, on the other hand, shouldn't mention specific people unless it is really necessary (such as FAQ0.0 must do). As was requested by several people, thanking specific individuals for their input is better left to the thanks file. Here we have done a good job and should continue this practice.

On the other hand it's useful (I think) in cases like mullender which points out specific winners where people can enjoy that entry. Like Yusuke Endoh, Christopher Mills and I also referred to myself as the alt code. Now I'm happy to remove any of the three and I wasn't even sure about any of it at all. It was done spontaneously when looking over the file. Along the liens of '.. okay, here's this entry that won't work on most systems but there are alternatives'. Nevertheless it might be that this entire thing could be moved to the bugs.md file? I mean it's there but perhaps the alternatives could be listed there instead? I think that might actually be better but I was only updating the question that was already there. Want me to remove that question and then make sure it's all in the bugs.md file? If I do I'll have to deal with reordering the questions but it might be better. Of course if the question there refers to more than one entry (I know one at least did but not sure if it's that question) then we might have to discuss that more.

> 
> If there is content in the thanks file that suggests creating a new FAQ entry, and such a FAQ can be written to address the overall IOCCC, then adding a new FAQ might be appropriate.
> 
Of course.

> The FAQ should try to avoid detailed questions about a specific entry. One could have a FAQ about "What is the smallest source code that has won the IOCCC?" and give the answer along with referencing the 5 smallest IOCCC source codes. This is because the FAQ question covers the whole IOCCC. Only the answer needs to mention a specific IOCCC winner answer. Even then, it should mention a few other nearly smallest entires: thus making the answer less about a specific entry.
> 

Ah. Well that explains the one about mullender then if that question (as I recall it) has others in it. But even so it might be better to be moved to bugs.md? I'm okay doing however you wish. Like I said I was just updating the question - that's what I had available at the time.

> Yes, the above is a suggestion for a new FAQ 😉.
> 
> IOCCC trivia questions that focus on the whole IOCCC, might be good FAQs (such as the above example of the smallest source code) even though their answers might point to a specific entry. Even then the answer should be made more broad (such as mentioning a some other nearly smallest winners).
> 

Makes sense.

> Here the choice of "IOCCC trivia FAQs" should be added with some care as such FAQs might overly influence future writers of IOCCC submissions. The FAQ about the smallest source code is OK because the IOCCC judges encourage small entries specifically by nearly always awarding the best one liner or best small entry.
> 
That's true.

> An example of a bad trivia FAQ might be "Which entry has the most functions?" as this might cause future IOCCC submissions to try to beat that record. A trivia question FAQ should not overly influence the nature of future IOCCC submissions unless that influence is for betterment of the IOCCC.

I agree. Also that would be very hard to answer. I would argue it'd be impossible to answer especially as it's highly subjective. I mean I can think of some like 1989/westley but there are others like it and does that mean it's more functions? That is highly subjective.

> 
> A question about a particular IOCCC entry, if the question about that particular IOCCC winner **was of common interest**, is probably better **asked and answered** within the "judges section" of the `README.md` of the particular entry.

If you have an example please do let me know .. though I think that there isn't any example right now?

Hope that helps. Will do more tomorrow.

**Pull request merged**
