### PR TITLE
Improve FAQ section for submitting

### PR DESCRIPTION
**Pull request by xexyl**
More work might need to be done in this section and other sections might need checking too but I believe this section is more helpful. An attempt was made to shorten some of it without compromising the usefulness but more will have to be done to make sure this is the case.

### CODE REVIEW

**Comment by xexyl** [comment]
If I have time later today I'll work on it more but otherwise tomorrow. I guess we don't need to review every part of the FAQ though as the most important things are about submitting and those are the ones being worked on.

**Comment by xexyl** [comment]
BTW: as I was writing that above comment it occurred to me that if you rearrange the letters in `SUBMITTING` you can get `SMITING`, a rather fun and ironic chance.

**Review by lcn2 — APPROVED** [review]
Good idea @xexyl

**Comment by xexyl** [comment]
> Good idea @xexyl 

Still a bit more work to do here but I guess that's this is the section that really matters. 

I do have an important question but that doesn't belong here. 

In a little bit I will going afk but when back I will work on the FAQ. 

I might try and work more on it today and push out one day other things that can wait so that I can get this done but we'll see. 

Hope you had a great sleep!

**Pull request merged**
