### PR TITLE
Add missing README to archive-2018.tar.bz2

### PR DESCRIPTION
**Pull request by xexyl**
This file is from my copy from the preview period of 2018 but that 
somehow was missing. I had added this to /2018/README.md but this was 
not carried over to the archive tarball.

### CODE REVIEW

**Comment by xexyl** [comment]
... well, README.text as it was then ... didn't add the html file now I think on it. Want me to ?

**Comment by xexyl** [comment]
Trying to rest now .. will do more fixes in a while.

**Comment by lcn2** [comment]
> ... well, README.text as it was then ... didn't add the html file now I think on it. Want me to ?
> 
> 
> 
> ## UPDATE 0
> 
> 
> 
> Okay I see the others don't have it so I guess the answer is no?

Please don't add an HTML equivalent for any markdown file, including `README.md` as they will just be overridden/replaced my HTML generated by a tool.

**Comment by xexyl** [comment]
> > ... well, README.text as it was then ... didn't add the html file now I think on it. Want me to ?
> > ## UPDATE 0
> > Okay I see the others don't have it so I guess the answer is no?
> 
> Please don't add an HTML equivalent for any markdown file, including `README.md` as they will just be overridden/replaced my HTML generated by a tool.

Not going to .. I wasn't sure at first until I checked. Thanks.

**Pull request merged**
