### PR TITLE
Remove <ul>/</ul> in FAQ

### PR DESCRIPTION
**Pull request by xexyl**
This was forgotten in the previous commit.

Also shorten some command lines (end line with '\').

### CODE REVIEW

**Comment by xexyl** [comment]
Now the lint should be good (I hope)!

**Review by lcn2 — APPROVED** [review]
dLint/dFile 🤓

**Comment by lcn2** [comment]
Are you taking a break now in editing the faq.md file?

**Comment by xexyl** [comment]
> Are you taking a break now in editing the faq.md file?

I'll do that so I won't cause a conflict with your help: yes. Thanks!

**Comment by xexyl** [comment]
.. once you've rearranged the answers I can look at shortening some answers, maybe merging some and possibly removing some too. After that I think it'll be in pretty good shape, unless something comes up of course.

**Pull request merged**
