### PR TITLE
Add deobfuscated versions of 199[1-3]/ant

### PR DESCRIPTION
**Pull request by xexyl**
Anthony/@SirWumpus kindly provided these files. The source code and
their Makefiles are in a deobfuscated/ subdirectory (for each of the
three entries) but running make alt
from the entry directory works. It uses the deobfuscated version's
Makefile but copies the compiled binary to the entry's directory to keep
things clean (deobfuscated code separate from the entry) to simplify
using the deobfuscated versions.

Entries that had a test suite Makefile have a new one for the
deobfuscated code and a try.alt.sh script was added to 1992/ant and
1993/ant but the entry_text is a bit different than the usual to 
indicate that it's the deobfuscated version.

It might be that the way this is done should be reorganised some but
that can be decided on later.

The entries from 2004 and 2005 have not yet been added because some
decisions have to be made as those are the ones with a configure script.

The manifest was updated and the .entry.json and index.html files were
updated. It is not clear yet if the inventory_order is right but that
will be looked at in the next day or two.

Thank you Anthony!

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Not sure if using a Makefile in an entry sub-directory is a good idea.

Oh well.

**Comment by xexyl** [comment]
> Not sure if using a Makefile in an entry sub-directory is a good idea.
> 
> Oh well.

I am not sure either. It does keep it cleaner but as noted it's certainly possible that it can and maybe even should be reorganised some. But in what way I don't know. 

What would you like it to be? I am happy to change it! I just didn't know and since you weren't about (hopefully having a great day) I went for the method of using the Makefile provided there. 

Let me know what you think and I can change it.

**Comment by SirWumpus** [comment]
IMO the original contest winner should be in a top level directory: year/author/entry1/* with any future fixes/additions as prog[0-9].alt.c.  Author supplied spoilers, background, history AFTER the win should go in  year/author/entry1/*/spoiler (or what ever).  Make a clear separation of the untainted original winner from the author's "notes" I think even for just one file having a directory  holding this supplement separates what the judges saw and what the author's core dump.

**Comment by xexyl** [comment]
> IMO the original contest winner should be in a top level directory: year/author/entry1/* with any future fixes/additions as prog[0-9].alt.c. Author supplied spoilers, background, history AFTER the win should go in year/author/entry1/*/spoiler (or what ever). Make a clear separation of the untainted original winner from the author's "notes" I think even for just one file having a directory holding this supplement separates what the judges saw and what the author's core dump.


In some cases the author initially provided a deobfuscated version though: what then? However in the case of this commit that's what I had - deobfuscated/. But I guess we'll see what Landon thinks on this matter. My view is similar to yours (at least as I understand it).

**Comment by SirWumpus** [comment]
> In some cases the author initially provided a deobfuscated version 

If it was part of judging then sure top level, if it to be viewed only later "in case of winner break seal", then it should go in something like "spoiler" .  As dir name "deobfuscated" is ugly IMO.

**Comment by xexyl** [comment]
> > In some cases the author initially provided a deobfuscated version
> 
> If it was part of judging then sure top level, if it to be viewed only later "in case of winner break seal", then it should go in something like "spoiler" . As dir name "deobfuscated" is ugly IMO.

I'm not particularly fond of it either - depending on what it is (if it is a deobfuscated version I don't see the problem) - but Landon does not want the word `spoiler` so we'll have to see what other word he likes: or if he wants another word. What do you think about all this, Landon (including my earlier thoughts on the Makefile in the subdirectory)?

**Pull request merged**
