### PR TITLE
Change references of many terms to new names

### PR DESCRIPTION
**Pull request by xexyl**
This is a HUGE commit and this task is not done. There are still some changes that might need to be discussed and since so much is done here I think it's better to let this go through and then make sure everything is okay. When the remaining references are discussed they can also be changed.

I did NOT include changes in the tmp/OLD_manifest directory.

Some of the changes in this commit (it might be exhaustive but it might not be - not sure):

- In the Makefiles the WINNERS was renamed AUTHORS.
- References to winners.html were changed to authors.html.
- The FAQ named anchor 'fix_a_winner' was renamed 'fix_an_entry'.
- The JSON fields (or whatever they're called) 'winner_id' and 'winner_JSON_format_version' were changed so that 'winner' is 'entry'.
- In scripts for entries 'IOCCC winner' was changed to 'IOCCC entry'.
- 'winners_text' is now 'entries_text'. It might be better to be 'entry_text' as it's per entry but this was not noticed at first. Since this is easy to fix I am holding off on this for the meantime.
- The script tmp/update-manifest.sh now has the commit log messages changed to the correct terms as well.

The index.html files were updated as well with any of the above changes.

There are some references that should NOT be updated. Two examples caught (and maybe more have slipped through that will have to be changed back): in 1984/anonymous/README.md the author wrote back to Landon after being told about the famous tattoo and they used the words:

    .. my entry will be the first IOCCC winner ..

but since this comes from the author it should remain so.

The other one is that winners.html should still refer to winners.html as it informs people that it's been moved to authors.html (it does redirect too but even so if it was changed it would defeat the purpose of the message).

With paths like authors.html I tried to copy paste so that hopefully there are no typos. It is possible that I did not end up doing this with all but these can be fixed when discovered.

### CODE REVIEW

**Comment by xexyl** [comment]
Minor fixes in 205fa25

It appears that indeed winners_text was meant to signify 'winner's text'
so 'entries_text' was changed to 'entry_text'. Also WINNER_TEXT variable
was changed to ENTRY_TEXT. If it is desired it can be changed to 
'ENTRYS' but this is very wrong in my head and I can't get myself to do
it without it being declared significant enough to change.

**Comment by xexyl** [comment]
Please do:

```sh
git grep winner
```

and let me know what else you think might need to change. Also was I supposed to check another word or more than one word?

**Comment by lcn2** [comment]
> Minor fixes in 205fa25
> 
> 
> 
> It appears that indeed winners_text was meant to signify 'winner's text'
> 
> so 'entries_text' was changed to 'entry_text'. Also WINNER_TEXT variable
> 
> was changed to ENTRY_TEXT. If it is desired it can be changed to 
> 
> 'ENTRYS' but this is very wrong in my head and I can't get myself to do
> 
> it without it being declared significant enough to change.
> 
> 

entry_text is fine

**Comment by lcn2** [comment]
Thanks @xexyl for this big step 🦶

**Comment by xexyl** [comment]
> Thanks @xexyl for this big step 🦶

You are most welcome. I'll check things another time.

**Pull request merged**
