### PR TITLE
Fixes and improvements to bugs.md

### PR DESCRIPTION
**Pull request by xexyl**
A line for one entry was in the wrong entry.

I added that I'm working on them (with some humour injected there) but
others may try too .. if they are okay making people very sad :-)

Added more information / examples in some of the status sections and
possibly some of the entries that are listed.

### CODE REVIEW

**Comment by lcn2** [comment]
ok!

**Comment by lcn2** [comment]
Suggestion: You might wish to change status lines under an entry such as:

```
[2020/ferguson1](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/prog.c) ([README.md](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/README.md))

Status: INABIAF - please do not fix

...
```

So that "Status: INABIAF - please do not fix" to the information now at the top:

```
Status: INABIAF - please do not fix

INABIAF: It's not a bug it's a feature :-)

The following entries should NOT be touched: they are system specific by design but are noteworthy nonetheless.
```

**Comment by xexyl** [comment]
> ok!

I will be updating the file more in the coming days for sure. I am first looking at each entry that has problems and try fixing them first (or making partial fixes). But I do know that more work needs to be done with this file.

**Comment by xexyl** [comment]
> Suggestion: You might wish to change status lines under an entry such as:
> 
> ```
> [2020/ferguson1](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/prog.c) ([README.md](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/README.md))
> 
> Status: INABIAF - please do not fix
> 
> ...
> ```
> 
> So that "Status: INABIAF - please do not fix" to the information now at the top:
> 
> ```
> Status: INABIAF - please do not fix
> 
> INABIAF: It's not a bug it's a feature :-)
> 
> The following entries should NOT be touched: they are system specific by design but are noteworthy nonetheless.
> ```

Good idea! I have had thoughts of additional sections as well but haven’t had a chance to put them in yet. 

Thank you!

**Comment by xexyl** [comment]
> > Suggestion: You might wish to change status lines under an entry such as:
> > ```
> > [2020/ferguson1](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/prog.c) ([README.md](https://github.com/ioccc-src/temp-test-ioccc/blob/master/2020/ferguson1/README.md))
> > 
> > Status: INABIAF - please do not fix
> > 
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So that "Status: INABIAF - please do not fix" to the information now at the top:
> > ```
> > Status: INABIAF - please do not fix
> > 
> > INABIAF: It's not a bug it's a feature :-)
> > 
> > The following entries should NOT be touched: they are system specific by design but are noteworthy nonetheless.
> > ```
> 
> Good idea! I have had thoughts of additional sections as well but haven’t had a chance to put them in yet.
> 
> Thank you!

Now that I have my reading glasses on .. do you mean by top the section _about the different statuses_ or do you mean each entry? Or maybe both?

**Pull request merged**
