### PR TITLE
Finish format/typo check 1991/brnstnd/README.md

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I believe this completes 1991: unless some issue is discovered when looking for dead links and checking the rendering of the html.

That's for another day however. Off now whether for the rest of the day or not. I'll start 1992 next either way.

**Comment by lcn2** [comment]
Yea 🥳 for 1991 ‼️ Only a few years to go to 2020 😉. 

Seriously, @xexyl, awesome progress.  The "learning curve" of 1984 to 1991 has been an important and impressive. We anticipate that things will go smoother for the IOCCC that followed.

**Comment by xexyl** [comment]
> Yea 🥳 for 1991 ‼️ Only a few years to go to 2020 😉.
> 
> Seriously, @xexyl, awesome progress. The "learning curve" of 1984 to 1991 has been an important and impressive. We anticipate that things will go smoother for the IOCCC that followed.

Thank you! That does mean a lot.

Another factor is that as we get closer to 2020 (hmm, does that mean we're going back in time ? :-) ) there will be fewer problems to resolve as well. There might be some alt versions worth adding here and there and sometimes a lot of work needs to be done in markdown files but the closer we get to the end the easier it should become. I won't spend that much time on my entries since I write a lot (as if you didn't know that! :-) ) and I can always look at those later if necessary. 

I think though that we might yet be a bit away from it getting much easier. But I guess we'll see.

I will be doing other things for the rest of the day but tomorrow I aim to start 1992. Have a great rest of your day!

**Comment by xexyl** [comment]
Hope you're sleeping well. I slept in a bit for third day in a row, somehow. I don't know that it'll continue but it would be nice if it did. Very sleepy still but can't sleep: body won't let me lie down. Hope to work on the contest in a bit if I still can't lie down (but might try anyway).

Hope you're sleeping well my friend!

**Comment by lcn2** [comment]
> Hope you're sleeping well. I slept in a bit for third day in a row, somehow. I don't know that it'll continue but it would be nice if it did. Very sleepy still but can't sleep: body won't let me lie down. Hope to work on the contest in a bit if I still can't lie down (but might try anyway).
> 
> 
> 
> Hope you're sleeping well my friend!

Woke up briefly so figured a GitHub check would be a good way pass a bit of time as we seem tired enough to return to sleep in a bit.

Best wishes on your sleep streak.

**Comment by xexyl** [comment]
> > Hope you're sleeping well. I slept in a bit for third day in a row, somehow. I don't know that it'll continue but it would be nice if it did. Very sleepy still but can't sleep: body won't let me lie down. Hope to work on the contest in a bit if I still can't lie down (but might try anyway).
> > Hope you're sleeping well my friend!
> 
> Woke up briefly so figured a GitHub check would be a good way pass a bit of time as we seem tired enough to return to sleep in a bit.
> 

The true sign of a developer: wake up and think of code and related!

> Best wishes on your sleep streak.

Thank you! Would be nice. I wouldn't want to sleep in past say 4:30 or 5: at least not yet. But it'd be nice if I could get there. It'll probably be a while yet before that happens I'm afraid though.

**Pull request merged**
