### PR TITLE
Fix 1986/marshall for linux                        

### PR DESCRIPTION
**Pull request by xexyl**
Choo choo! :-)                                            
                                                             
There was a problem in linux where it either segfaulted or entered an
infinite loop depending on compiler / flags. This was caused by a for
loop that had an empty condition and the call to _exit().        

A game of cat and mouse occurred where fixing it for one compiler caused
the program to segfault with the other compiler. Unfortunately the
formatting did have to change a bit but it still mostly looks like a
train even if not quite as pretty.

### CODE REVIEW

**Comment by xexyl** [comment]
... off until tomorrow .. good day!

**Comment by lcn2** [comment]
Fun bug 🐛 fix @xexyl

**Comment by xexyl** [comment]
> Fun bug 🐛 fix @xexyl

Yes. I'll see about writing up more in the README.md tomorrow morning. Do feel free to remind me if I forget! I have a number of things on my mind so it's entirely possible though I'm sure I'll see it again.
> 
> If you do submit this issue as a bug report to compiler folks, we hope they are at least amused by your report.

That would be nice if they are yes. I'm not sure if I will have the time / energy esp as it might be better to spend time working on the IOCCC.

**Comment by xexyl** [comment]
I've not forgotten the idea of documenting the funny things I found in linux with this entry. I just haven't had at the same time the time and energy and motivation. Right now I am going to do other things outside of the IOCCC but I will do more with it tomorrow if not later today (most likely it won't be later today).

**Pull request merged**
