### PR TITLE
Make bug statuses in index.html files quotes

### PR DESCRIPTION
**Pull request by xexyl**
Instead of code blocks the bug / (mis)features statuses are quoted 
rather than in a code block. In the case that there is more than one a 
line break was added at the end of all but the last one.

A bug status was renamed to be slightly more correct (maybe more than 
one was renamed for the same purpose but at least one was).

The bug statuses in the quotes are now bold to let them stand out 
better.

### CODE REVIEW

**Comment by xexyl** [comment]
Looks much nicer now. Back tomorrow. Good day!

**Comment by xexyl** [comment]
I'm not sure why all that information was removed at how to fix author information as it gave quite some important details that are now lost. And I don't think I included their email anyway as I have no way of knowing if it's still valid.

Well we can discuss that another time .. gone for the day.

**Comment by xexyl** [comment]
It was meant to be two pull requests too - an accident when I was rushing off .. and gone again.

**Comment by lcn2** [comment]
> I'm not sure why all that information was removed at how to fix author information as it gave quite some important details that are now lost. And I don't think I included their email anyway as I have no way of knowing if it's still valid.
> 
> Well we can discuss that another time .. gone for the day.

The additional text was lengthy, read like a change log, was too specific to a given author, and was potentially confusing to a reader.

While we some of the additional text and so we modified the PR in order to accept other parts of the PR that were good.

**Comment by xexyl** [comment]
But that was not part of the commit. And although it might kind of look like a log it explained how to do it and it no longer does.

**Review by lcn2 — APPROVED** [review]
Approving PR #2578 with modifications.  Thank you @xexyl

About the modifications, see commit 43fafd0af6d88c964348618cbd1f4a2ec1dc7072:

improve FAQ 5.5 and FAQ 6.16

We improve FAQ 5.5 (correcting or updating IOCCC author information)
by adding a generic example on changing author's URL.

Now the "PLEASE HELP us identify proper locations for IOCCC authors"
(that now follows the change of URL example) contains only
generic information about changing the location_code from ZZ to AU.

We remove the indirect reference to author email in FAQ 6.16 as we
do not wish to call out what we previously included in the
`authors.html` page.

This commit modifies that otherwise perfect fine PR #2578.

Performed `make www` to accomplish the above and to test under macOS.

**Review by lcn2 — APPROVED** [review]
Thank you @xexyl

**Pull request merged**
