### PR TITLE
Fix to bugs.md for 1986/hague

### PR DESCRIPTION
**Pull request by xexyl**
I by accident had left an incomplete sentence in the file (probably
jumping to another entry when updating the file with multiple entries
and then forgetting to go back .. numerous times). Fixed that and added
a bit of information (or at least elaborated a bit?).

### CODE REVIEW

**Comment by lcn2** [comment]
feature

**Comment by xexyl** [comment]
> feature

Though in this case it's NOT INABIAF. So it might be said to be INAFIAB or something like that ... maybe it's better to just say IAB. 

Well misuse of `gets()`. I started a fix but haven't finished it yet.

**Comment by lcn2** [comment]
> Well misuse of gets(). I started a fix but haven't finished it yet.

Is the misuse of `gets()` intentional / part of the entries obfuscation?  Would replacing with with `fgets()` it be a change in the entry that is not a fix?

Just curious.  We understand why modern code should not use `gets()`, and we have let _corrections_ go thru so far.  Nevertheless we have wondered if these `fgets()` replacements are a fix bordering on _tampering_?  We think in general the  `fgets()` changes are a good thing.  We just wonder if every use on all entries is a good thing?  The answer is probably yes, nevertheless there is this question.

We anticipate the the guidelines will state that we prefer to not have entries use `gets()` in the future: along the lines of indicating that we tend to dislike trigraphs.

**Comment by xexyl** [comment]
> > Well misuse of gets(). I started a fix but haven't finished it yet.
> 
> Is the misuse of `gets()` intentional / part of the entries obfuscation? Would replacing with with `fgets()` it be a change in the entry that is not a fix?

I don't think it's part of obfuscation no. One I've come across is unique and I didn't change it - I just changed the buffer size. There are some others that can't change either.

> 
> Just curious. We understand why modern code should not use `gets()`, and we have let _corrections_ go thru so far. Nevertheless we have wondered if these `fgets()` replacements are a fix bordering on _tampering_? We think in general the `fgets()` changes are a good thing. We just wonder if every use on all entries is a good thing? The answer is probably yes, nevertheless there is this question.
> 
Great question. I'm not sure and I guess it depends. I think if the functionality is the same it is probably okay but if not then it's possibly not okay. I'm aware of one that makes a slight modification in output that I am wondering about changing back but all it does is add an extra line. On the other hand it makes it so larger input doesn't crash it.

In some cases changing to fgets() allows the entry to work I'd guess which is perhaps the best example of when it should be done.

Another one that changing it to use gets() actually introduces a bug so I've not done that. Not sure which one that is off hand and I need to get going very soon.

I think it's iffy too. I've wondered about it but like you it seems like it might be a good idea.

I think if it can't be done simply it shouldn't be done maybe? Most of them have been .. at least the ones I've encountered. But for this entry at least the buffer size could be increased.

One I avoided is when the author said they know it uses `gets()` but they justified it and they included code that does not use it as well. 

So some of them are more valid than others but it could be a greyish area. If you like I can avoid doing this for now and then ask you about specific entries when you get home. I'll still work on other things of course.


> We anticipate the the guidelines will state that we prefer to not have entries use `gets()` in the future: along the lines of indicating that we tend to dislike trigraphs.

And digraphs ... I know I kind of killed them in 2020. I'm not sorry! :-)

**Comment by xexyl** [comment]
.. and with that said I'm leaving for the day.

Fixed 1986/wall to compile without `-traditional-cpp`.

Have a great afternoon! I'll reply to everything in the morning.

**Comment by xexyl** [comment]
Oh there's another argument for changing it to use `fgets()` if feasible.

In linux when compiling you'll get (or maybe it's gcc) e.g.:
```
/usr/bin/ld: /tmp/ccvGIKmD.o: in function `main':
hague.c:(.text.startup+0x2a): warning: the `gets' function is dangerous and should not be used.

```

and in macOS with that entry you get:

```sh
$ ./hague 
warning: this program uses gets(), which is unsafe.
```

and the latter one is more annoying. In one entry I fixed it actually made the interface look confusing with that warning there.

Well I'm leaving now. Will do more tomorrow. Good day!

**Comment by lcn2** [comment]
> And digraphs ... I know I kind of killed them in 2020. I'm not sorry! :-)

:-)

**Comment by xexyl** [comment]
> > And digraphs ... I know I kind of killed them in 2020. I'm not sorry! :-)
> 
> :-)

To be fair: I did not use them for obfuscation so much as to align text and also because there is a kind of beauty to them in my eyes (even though I sometimes have to look up the different ones :-) ). The fact they mess up some beautifiers is a nice bonus though. But certainly I was under no impression that they would confuse any C programmer and especially not the IOCCC Judges!

**Comment by xexyl** [comment]
As for `gets()` versus `fgets()`: I have the perfect solution. Need to do something on the server but assuming that goes quickly I'll start working on this. I'll post a new comment with the fix commit link in a bit!

**Comment by xexyl** [comment]
... **\*mutters\*** .. server had a problem with new backup drive and I was forced to reboot ... 311 days uptime too :( and not only that but it doesn't want to come back up and I have a cat between my legs and probably will for some hours.

Connected by changing DNS server to modem which means ISP DNS servers.

I'm going to hope that the problem on the old one was bitrot and then I can fix it by doing a format of that. But several processes got in D state. This has delayed me. It seems that this is why the backup jobs were not running: or running but actually not doing anything. I should have copied important info on backup drive to /home and then formatted it. :( 

.. so with that until the cat is up I have to not look at the server. I will have to do a hard reboot and hope to hell that it can boot up okay. I remembered to change `/etc/fstab` so that it doesn't try mounting faulty volumes but I fear the worst. If this is so I might not get much done except for right nowish. 

I have to be with Lily for some hours today and after that I might or might not be able to do more.

Sorry :(

**Comment by xexyl** [comment]
As for the `gets()` versus `fgets()` see commit https://github.com/ioccc-src/temp-test-ioccc/pull/285.

I think this is the right way to go about it. What do you think ?

**Comment by lcn2** [comment]
> was forced to reboot ... 311 days uptime too :(

That is a sad reboot after such uptime.

**Comment by lcn2** [comment]
> > was forced to reboot ... 311 days uptime too :(
> 
> That is a sad reboot after such uptime.

Best wishes on resolving this system issue.

**Comment by xexyl** [comment]
> > was forced to reboot ... 311 days uptime too :(
> 
> That is a sad reboot after such uptime.

Yes. Very unhappy about it. Thank you.

**Comment by xexyl** [comment]
> > > was forced to reboot ... 311 days uptime too :(
> > 
> > 
> > That is a sad reboot after such uptime.
> 
> Best wishes on resolving this system issue.

Well I think it’s okay. I am not sure yet but it looks like the backup job went through okay. The verify job didn’t seem to start though so I am not sure. I manually initiated it but I haven’t had a chance to check its status. 

Thank you!

Well at least I got some really great fixes in here today.

**Comment by xexyl** [comment]
> > As for the `gets()` versus `fgets()` see commit
> > [06a5665](https://github.com/ioccc-src/temp-test-ioccc/commit/06a5665f5d1c86f89f8dc36a4fd5064cb70d44fa) (pull request #285).
> > I think this is the right way to go about it. What do you think ?
> 
> You may be correct. Things will be inconvenient either way, perhaps your solution in the above mentioned pull request is a reasonable compromise.

Yes both ways are possibly problematic. 

In the case of other bugs being fixed I didn’t do that but otherwise yes. 

We can change it so the alternative version is the fgets one if that’s desired.

**Comment by lcn2** [comment]
> We can change it so the alternative version is the fgets one if that’s desired.

Maybe not. It may be better to have the possibility problematic output (due to runtime complaints about using `gets()`) come from the alt version.

**Comment by xexyl** [comment]
> > We can change it so the alternative version is the fgets one if that’s desired.
> 
> Maybe not. It may be better to have the possibility problematic output (due to runtime complaints about using `gets()`) come from the alt version.

Agreed. Thank you. Just thought I would bring it up as a possibility.

**Comment by xexyl** [comment]
As far as file system errors ... this is on the volume that's been a problem. Wish I had done it at the laptop (ssh) so I would have had better / clearer pictures but I wanted to make sure everything went okay without having to go back to the console. Fun fact: piping to `tee -a ...` fsck won't work: needs terminal for interactive repair (the last part makes sense but I thought `tee -a` would work).

IMG_7314
IMG_7315

As for the other volumes (including one repeated due to not noticing it .. was still waking up and perhaps shouldn't have been doing it but when the log is being flooded with disk errors it's time to fix it if at all possible). I'm concerned that this will happen again and I might very well format the volume again just to be sure as it seems to be a repeat problem (though yesterday the fsck didn't show any problems which was strange to me). Anyway:

Screenshot 2023-04-06 at 03 21 05

.. incredibly annoying and still very upset about the lost uptime :( ... anyway hopefully this is resolved now. I'll probably later on in the day check in on it and then copy anything important to another volume on the disk (probably `/dev/sdf3`) and then format `/dev/sdf1` and then update `/etc/fstab`.

Safe travels and BCNU my friend! :)

**Pull request merged**
