### PR TITLE
Clean up bugs file

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
So one more file besides the FAQ. Hopefully between the two of us we can get the FAQ in order before the 28th (happy early birthday btw! .. will say something then of course). Next I will work on that other file. Unsure about further changes to the FAQ today. If not I'll start on it tomorrow but it should be all that is needed, really, in theory at least.

I might need to take a longer break today given how awful the night was. We shall see. In a little bit I might be afk for a short while but I'll be working on the last file (last file besides the FAQ).

**Review by lcn2 — APPROVED** [review]
dBug / dFile 🤓

**Comment by xexyl** [comment]
> dBug / dFile 🤓

Bugd (bugged or bug daemon: hmm, that sounds like a fun one!, bud, dub etc.; and

Filed, Field, d-File (defile), die, fie, fled, etc.

**Comment by xexyl** [comment]
The other file I think is probably good enough. The FAQ though .. I'm not even sure how to continue with that. I know that the lint fails on it now. Unsurprising. I guess I can start with that but the moving the entries (and I noticed I made a typo in the log) is proving to be a huge problem. Maybe I should start out with simplifying them but I don't know.

Today is a hard day. Anyway the point is I think the FAQ is the one to work on and then probably we're good.

**Pull request merged**
