### PR TITLE
Add note about alt code of 1992/lush (gets())

### PR DESCRIPTION
**Pull request by xexyl**
This code should probably be deleted but that can happen another time. 
This can be considered a reminder to do this when I have the time.

### CODE REVIEW

**Comment by lcn2** [comment]
We are going to merge pull request #328 and see if that will cause the note based pull requests stating with pull request #324 to be merged as well.

**Comment by lcn2** [comment]
🎶

**Comment by lcn2** [comment]
It seems it does merge all previous unmerged pull requests.  OK. Good to know that if we wanted to NOT process a given pull request we have to close/reject it. That we cannot simply skip it and leave it pending.

**Comment by xexyl** [comment]
> It seems it does merge all previous unmerged pull requests. OK. Good to know that if we wanted to NOT process a given pull request we have to close/reject it. That we cannot simply skip it and leave it pending.

Glad you discovered what you need to know!

**Comment by xexyl** [comment]
.. with commit https://github.com/ioccc-src/temp-test-ioccc/pull/340/commits/af1028c4c7cfad5e5d62596c71a167cdc6f84b10 the alt code was removed and it now just refers to the archive.

**Pull request merged**
