### PR TITLE
Add faq.md, remove faq.html

### PR DESCRIPTION
**Pull request by xexyl**
I tried to keep the formatting as close to the original as possible. It's very likely links have to be fixed and it's very likely formatting has to be fixed.

Some things necessarily had to change but very few did in fact need to change.

As tempting as it was to change it to British English I did not (though I started to when fixing a link but I caught myself in time) :-)

Naturally as this is a major change problems are expected but these will be worked out. I guess the next step would be to do this for other raw html files but I don't fancy doing more than one in a day. This can be discussed later though as some will be automatically generated anyway so no need for a markdown file (faq.md was discussed as a good idea).

### CODE REVIEW

**Comment by xexyl** [comment]
> FAQ!

Yes. Should be easier to update now.

I was just checking .. will reply and do clean up later. Going back to my dog. She's having a very difficult time. I'll have a bit of time later today possibly but that's not certain. Been with her a lot which I enjoy but it's for all the wrong reasons.

Will do more tomorrow.

**Comment by xexyl** [comment]
.. hmm .. shouldn't `faq.html` be deleted entirely ? Want me to do that ?

**Comment by lcn2** [comment]
> .. hmm .. shouldn't `faq.html` be deleted entirely ? Want me to do that ?

Yes please.

**Comment by xexyl** [comment]
> > .. hmm .. shouldn't `faq.html` be deleted entirely ? Want me to do that ?
> 
> Yes please.

Done in commit https://github.com/ioccc-src/temp-test-ioccc/pull/223/commits/df86d0cdc340ebe8819b7dfe6ab2ed9a80e058a1. Added it to .gitignore in https://github.com/ioccc-src/temp-test-ioccc/pull/223/commits/a009145f67c66f9779efca2504b80d223eab1705.

Changed to /faq.html in commit 99e872cc1476bc8a2d904ad32fbd0f8911c7bcf0.

**Pull request merged**
