### PR TITLE
Fixes in 1998 html files

### PR DESCRIPTION
**Pull request by xexyl**
This includes some notices to those who wish for a greater challenge.

In the 1998/schweikh3 the man page (and its copy to demonstrate the entry) have been updated slightly but only in comment (move 'or' from the command suggested to render it in text to its own line before the next command also in comment).

The bugs file was updated for an entry or two.

### CODE REVIEW

**Comment by xexyl** [comment]
Hmmm .... that's unfortunate: the `#Lx` feature of GitHub is not checked in the script. I don't know if it should be added or not but it would be nice if it is. I'll let you decide. For now I have to go afk. If the script can be updated that would be a great addition. Maybe I can look at it but that might be complicated if it's not checking `%%REPO_URL%%` explicitly (which I guess it is not).

**Comment by xexyl** [comment]
Trying something real quick .. if it does not work I'll be back later to address this: either removing the good feature of GitHub or else seeing if I can fix the script.

**Comment by xexyl** [comment]
Okay I had a fix but it was a typo ... good. Afk now a while.

**Review by lcn2 — APPROVED** [review]
nice improvements, @xexyl

**Comment by xexyl** [comment]
> nice improvements, @xexyl

More than I expected but good to finish 1998 - and obviously 1999 as there was no 1999 contest. If the IOCCC used Windows there might not have been a Y2K either! (Well okay MS did manage but still ... we at least had until 2038! :-) ... until the update of `time_t` type: well Unix/Linux always was ahead of Windows!).

**Pull request merged**
