### PR TITLE
Rename wrongly named author/winner handles

### PR DESCRIPTION
**Pull request by xexyl**
There were many files renamed in this commit and I hope I got all the
references to the old names changed to the new names. To explain this
commit there were some older entries that had the wrong directory name:
not the surname but something else.

Very possibly there are other directories that need to be renamed and I
am actually aware of one right now but since it's in 2005 (which is
close to being worked on) I am not changing that now but just noting it:
2005/anon should be changed to 2005/anonymous (unless there's a very
good reason I am unaware of). But like I said since 2005 will be worked
on soon I have not touched it.

The Makefiles, .gitignore, the all/summary.txt, years.html and
winners.html files as well as the directories and the files under the
renamed directories have all been updated.

This is a rather big update and it might be that there are conflicts. If
so I will fix them. I will have to update 2005/anon later on to try and
prevent this from happening but very possibly there will be conflicts
here. It's also possible I missed some changes in years.html and/or
winners.html and/or summary/all.txt but I think I got them all. These
should be verified later on.

### CODE REVIEW

**Comment by xexyl** [comment]
NOTE: 2005/anon I did not touch because you'll likely be updating that directory soon .. once you've finished 2005 I can update it though. I'll make sure that you have that todo item in issue #3 but and perhaps you could make a note of this specific entry as it would be helpful.

Anyway with a lot of renames it's very possible I have missed something but they can be corrected in time of course.

**Comment by lcn2** [comment]
We should be cautious in renaming entries, although the cases you sighted here seem to warrant it, @xexyl

**Comment by xexyl** [comment]
> We should be cautious in renaming entries, although the cases you sighted here seem to warrant it, @xexyl

I agree. I believe that it was what was wanted though, right? To make it so that the same winner is easily identified. 

I am certainly up to ideas to help with this that are different though.

**Comment by xexyl** [comment]
As per our both coming to the conclusion that this was wrong after all I'm preparing to do the rolling back .. not sure if I'll do it right now or a bit later. I really ought to get moving but I am having a very slow day so for now I'm going to I think at least start the process.

Made a few other pull requests first including one with a fix for a 1989 entry (westley). This now compiles with clang though not all versions do - see the README.md for invocations if you don't recall. I did get those to compile too but they did not work right. I also found a bug in that entry (in ver2) which is also in the fix (it wasn't meant to fix any bugs .. just to make it compile with clang). Sometimes the same input will make it segfault though I'm not sure why. I might revisit this to make it work with clang - all versions. I should say the segfault seems to do it _after_ the output is written to stdout. I'll have this part in a comment by itself in that pull request too so you can identify it in particular (though the title should be obvious).

**Pull request merged**
