### PR TITLE
Fix 1993/jonth

### PR DESCRIPTION
**Pull request by xexyl**
With a mis-feature (I guess) of the C pre-processor that no longer works
the entry no longer compiled. It needs #define to define (imagine that! :-)  
macros.

### CODE REVIEW

**Comment by lcn2** [comment]
thanks for the define fixes @xexyl

**Comment by xexyl** [comment]
> thanks for the define fixes @xexyl

You're very welcome my friend! .. and I know you've probably noticed but I am trying my best to keep the formatting as close to as the original as possible. Sometimes this is not possible; in most cases I won't add lines to match the formatting as merging lines and creating new lines can be problematic esp if I don't disable formatting in vim but I think in some cases I have added lines. Obviously the one that I should never do that is the one-liner entries!

**Comment by xexyl** [comment]
## QUESTION 

But this does bring up an interesting question I had: how was the code valid before? Was there a time where the code could be compiled? What compilers?

**Comment by lcn2** [comment]
> ## QUESTION
> But this does bring up an interesting question I had: how was the code valid before? Was there a time where the code could be compiled? What compilers?

No doubt there was a time and environment.

**Comment by xexyl** [comment]
> > ## QUESTION
> > But this does bring up an interesting question I had: how was the code valid before? Was there a time where the code could be compiled? What compilers?
> 
> No doubt there was a time and environment.

Of course. Did some standard change it? C99? Since it clearly worked in 1993.

**Pull request merged**
