### PR TITLE
Fix paths in contact.md and contact.html

### PR DESCRIPTION
**Pull request by xexyl**
Changed ../judges.html to /judges.html and faq.html to /faq.html. These
are of course pedantic fixes: for of course at the root directory 
../judges.html will evaluate to /judges.html and at the root directory 
faq.html will be the same as /faq.html so these updates don't fix a 
problem but rather make it more correct. The reason for the / is in case
for some reason any of the files are moved to subdirectory (or if the 
files are in different directories, I guess), unlikely as that is. This
was done in other files quite some time back and probably should be done
throughout the repo but that can be dealt with another time.

### CODE REVIEW

**Comment by xexyl** [comment]
Afk a bit and when back I plan to look at the other comments I have been unable to address for some days.

**Comment by lcn2** [comment]
The paths should **NOT** be absolute as this causes the path to depend on the docroot in stead of the relative position.

See commit 2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613

**Comment by xexyl** [comment]
> The paths should **NOT** be absolute as this causes the path to depend on the docroot instead of the relative position.
> 
> See commit [2b92c89](https://github.com/ioccc-src/temp-test-ioccc/commit/2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613)

Then should `./` be used instead or no path at all?

**Comment by xexyl** [comment]
Oh you fixed it. Thanks. I actually thought of docroot but I did not look at the lower level of it. I was also still not truly awake but I probably would not have anyway.

Thanks for taking care of the problem!

**Comment by lcn2** [comment]
> Oh you fixed it. Thanks. I actually thought of docroot but I did not look at the lower level of it. I was also still not truly awake but I probably would not have anyway. Actually I certainly would not have.
> 
> Thanks for taking care of the problem!

We did not fix anything recently in this regard.  The commit 2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613 was done back in 2024 Mar 4.

**Comment by xexyl** [comment]
> > Oh you fixed it. Thanks. I actually thought of docroot but I did not look at the lower level of it. I was also still not truly awake but I probably would not have anyway. Actually I certainly would not have.
> > Thanks for taking care of the problem!
> 
> We did not fix anything recently in this regard. The commit [2b92c89](https://github.com/ioccc-src/temp-test-ioccc/commit/2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613) was done back in 2024 Mar 4.

Ah. I didn't look yet either. Trying to finally reply to the comments I have neglected but first another one that you made a short bit ago. So the `../` maybe is needed due to the way it is generated. That's what I guess. What about the other file though? Should that also be updated to have `../`? I'm happy to do that though I guess it's less important than some of the other things and if necessary perhaps you'll take care of it.

Thanks.

**Comment by lcn2** [comment]
Probably in the cases of `judges.html` the link, since it in the same directory, should just be to `judges.html`.

**Comment by lcn2** [comment]
## UPDATE 0

Sorry (tm Canada 🇨🇦) to have to reject the pull request.

**Comment by xexyl** [comment]
> ## UPDATE 0
> Sorry (tm Canada 🇨🇦) to have to reject the pull request.

It's fine. As I noted somewhere it seems it is better that I hold off on all commits until these problems are resolved. So I will try and reply to the comments but hold off on any commits. No point when there are chances of conflicts.

**Pull request closed without merging**
