### PR TITLE
Typo fix and improve brew instructions in bin/

### PR DESCRIPTION
**Pull request by xexyl**
In particular the notice for macOS users now tells how to install bash with Homebrew (brew install bash).

### CODE REVIEW

**Comment by lcn2** [comment]
thanks @xexyl

**Comment by lcn2** [comment]
We are going to call an early night in order to be able to do better tomorrow

**Comment by xexyl** [comment]
> We are going to call an early night in order to be able to do better tomorrow

Good idea! I have a minor update to this commit to make the line length a bit better and to make it clearer what to do (in comments the same applies). I will be doing that after a `make www` completes successfully. In a bit I probably will go afk. I then do have those reminders I mentioned yesterday to take care of. But I want to today start on checking if the make clobber rules are sufficient or if there are files missing. I don't know if I can finish that today but I hope to start it.

And of course you're welcome!

**Comment by xexyl** [comment]
... although given I just saw a lower case C as a lower case Q ... maybe it's good I'll be doing nothing for a bit of time ... well anyway hopefully I get more than the incoming commit done today.

**Pull request merged**
