### PR TITLE
Add note about 1986/wall.alt.c

### PR DESCRIPTION
**Pull request by xexyl**
It was added so one can see just how different the C language was at the
time. Well see without having to look at the archive.

### CODE REVIEW

**Comment by lcn2** [comment]
Tinkertoy

**Comment by xexyl** [comment]
> Tinkertoy

A true classic!

**Comment by xexyl** [comment]
> > Tinkertoy
> 
> A true classic!

Look what I just discovered!

https://www.computerhistory.org/collections/catalog/X39.81

.. though I somehow would not be surprised if you already know of this Tinkertoy computer. Do you? The pictures look great by themselves but the concept is wonderful too!

**Comment by lcn2** [comment]
> > > Tinkertoy
> > 
> > 
> > A true classic!
> 
> Look what I just discovered!
> 
> https://www.computerhistory.org/collections/catalog/X39.81
> 
> .. though I somehow would not be surprised if you already know of this Tinkertoy computer. Do you? The pictures look great by themselves but the concept is wonderful too!

Yes, I have seen it in person.

**Comment by xexyl** [comment]
> > > > Tinkertoy
> > > 
> > > 
> > > A true classic!
> > 
> > 
> > Look what I just discovered!
> > https://www.computerhistory.org/collections/catalog/X39.81
> > .. though I somehow would not be surprised if you already know of this Tinkertoy computer. Do you? The pictures look great by themselves but the concept is wonderful too!
> 
> Yes ... seen it in person.

Somehow - as noted - this does not surprise me! But I'm concerned here .. usually you ay 'we'. Here you say 'I'. What does that mean?

> Cody felt a strange certainty that in this matter Landon was for once not so far from the truth as might be suspected; that he had somehow found a way out of Mordor, and at least believed that it was by his own cunning. For one thing, he noted that Landon used *I*, and that seemed usually to be a sign, on its rare appearances that some remnants of old truth and sincerity were for the moment on top. But even if Landon could be trusted on this point, Cody did not forget the wiles of the Enemy. The 'escape' may have been allowed or arranged, and well known in the Dark Tower. And in any case Landon was plainly keeping a good deal back.

Well okay: Cody is really Frodo and Landon is really Gollum but you get the idea :-) :-) :-)

**Comment by xexyl** [comment]
> > > > Tinkertoy
> > > 
> > > 
> > > A true classic!
> > 
> > 
> > Look what I just discovered!
> > https://www.computerhistory.org/collections/catalog/X39.81
> > .. though I somehow would not be surprised if you already know of this Tinkertoy computer. Do you? The pictures look great by themselves but the concept is wonderful too!
> 
> Yes ... seen it in person.

I think it's hilarious that you edited your comment to remove the 'I' part! :-) Thanks for the laugh!

**Pull request merged**
