### PR TITLE
Typo fix in FAQ

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Just saw this by chance but as you know it's really all I can do right now.

**Comment by lcn2** [comment]
Ann 🫎 😁 @xexyl

**Comment by xexyl** [comment]
> Ann 🫎 😁 @xexyl

Not sure what that's supposed to be or reference to. Mind elaborating if you get a chance? (Obviously very very low priority.)

**Comment by lcn2** [comment]
> > Ann 🫎 😁 @xexyl
> 
> Not sure what that's supposed to be or reference to. Mind elaborating if you get a chance? (Obviously very very low priority.)

Monty Python reference

**Comment by xexyl** [comment]
> > > Ann 🫎 😁 @xexyl
> 
> > 
> 
> > Not sure what that's supposed to be or reference to. Mind elaborating if you get a chance? (Obviously very very low priority.)
> 
> 
> 
> Monty Python reference 

Ah. I have not seen them all. Another problem is that I don't even know what all the emojis are. My vision is not good enough and sometimes zooming way in is still not enough. 

It seems like it was an animal but what animal I don't know and how it relates to the pull request I also don't know. 

Anyway thanks for answering!

**Pull request merged**
