### PR TITLE
Format/typo check 2000/tsoj

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Looks like 7 to go! I have to leave though for now.

**Comment by xexyl** [comment]
Okay I'll resume tomorrow .. leaving for the day. It seems like I might even be able to finish it tomorrow but if not I'd guess I can Saturday! Good day!

**Comment by lcn2** [comment]
Nice progress .. thanks @xexyl

**Comment by xexyl** [comment]
> Nice progress .. thanks @xexyl

You're very welcome!

**Pull request merged**
