### PR TITLE
Add named links to FAQs

### PR DESCRIPTION
**Pull request by xexyl**
I also fixed a format issue and some incorrect terms.

### CODE REVIEW

**Comment by xexyl** [comment]
I left a little joke in a named FAQ for you. In particular `How did the IOCCC get started?`.

Gone for the day .. will look at the next year tomorrow.

**Review by lcn2 — APPROVED** [review]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl 

Welcome. Did you catch the joke there? A reference to something I will call special even though some call it awful. Special can mean many things after all! 

If you didn't catch it I will elaborate tomorrow.

**Comment by xexyl** [comment]
Of course the next step for the FAQ is to make the table of contents link to the named links but that can be done another time.

**Pull request merged**
