### PR TITLE
Typo check entries for 1984

### PR DESCRIPTION
**Pull request by xexyl**
This commit includes the two entries not already done (other changes 
besides a final typo and formatting pass) in 1984, anonymous and laman.

This commit means that the entries of 1984 have each had their README.md
file formatted and typo fixed one more time and this should be good for
publication.

### CODE REVIEW

**Comment by xexyl** [comment]
And thus the entries for 1984 are finished!

**Comment by xexyl** [comment]
> We are on the run here getting ready to visit the Behringer meteor crater and Lowell observatory. The Astronomer who was to be giving the lectures tour group got sick and so we are doing the lectures on the bus and instead of sitting back and listening, we have been studying and preparing to talk to the tour group.

That explains a lot but I hope it goes well for you! I'm sure it will. Personally I'd find an astronomy lecture by you really fascinating!

**Comment by lcn2** [comment]
Briefly reviewed the edits but no time to comment or thank or take the opportunities to make punny comments.  Sorry (tm Canada 🇨🇦)

**Comment by xexyl** [comment]
> Briefly reviewed the edits but no time to comment or thank or take the opportunities to make punny comments. Sorry (tm Canada 🇨🇦)

You can do it later :-)

**Comment by xexyl** [comment]
> Great progress @xexyl thank you

And thank you!

**Pull request merged**
