### PR TITLE
Add 2006/borsanyi/try.sh

### PR DESCRIPTION
**Pull request by xexyl**
The script runs in a loop until the user answers anything but 'y' or 'Y'
when asked if they wish to make another one. It does NOT check the valid
range of characters or the length. Instead it suggests one try and see 
what happens if they do not follow the rules.

Updated .gitignore.

### CODE REVIEW

**Comment by xexyl** [comment]
2006 done.

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

You're very welcome.

I will reply to the other comments tomorrow. I think I have to be done for the day. Too tired to focus on such important things.

**Comment by lcn2** [comment]
> > Thank you @xexyl
> 
> You're very welcome.
> 
> I will reply to the other comments tomorrow. I think I have to be done for the day. Too tired to focus on such important things.

Then maybe tomorrow you can try your hand at updating the manifest as per the recent changes you made today?

**Comment by xexyl** [comment]
> > > Thank you @xexyl
> > 
> > 
> > You're very welcome.
> > I will reply to the other comments tomorrow. I think I have to be done for the day. Too tired to focus on such important things.
> 
> Then maybe tomorrow you can try your hand at updating the manifest as per the recent changes you made today?

Yes. I put the files I added in a file so I know what I added. I see that you made more comments on the subject which I'll have to look at first. But I think that'll be the first thing I do here tomorrow.

**Pull request merged**
