### PR TITLE
Format/typo check 2015/endoh1

### PR DESCRIPTION
**Pull request by xexyl**
The FAQ has been updated to say how to compile and install tcpserver 
(for systems that don't have a package in their package manager) as this
entry requires it. The FAQ does not mention this entry.

The README.md file has been format/typo checked.

### CODE REVIEW

**Comment by xexyl** [comment]
This completes 2015!

**Comment by lcn2** [comment]
echo thank you @xexyl | tcpserver 127.0.0.1 7

**Comment by xexyl** [comment]
> echo thank you @xexyl | tcpserver 127.0.0.1 7

When I first saw this in email preview (very quickly) I thought I saw a typo. I see now that's not the case! Referring to port 7. I don't know how I remember that but I do. The problem with attackers is that one cannot have fun with some old ports as even if the services are opened (rare) they're filtered. Admittedly I always thought it'd be fun to try and pipe port 19 to a printer (remotely .. I'm terrible!) but I'm glad I never did try. Waste of paper and resources and would not be funny. The Ents might dislike the murdering of trees and so would I.

**Comment by xexyl** [comment]
> > echo thank you @xexyl | tcpserver 127.0.0.1 7
> 
> When I first saw this in email preview (very quickly) I thought I saw a typo. I see now that's not the case! Referring to port 7. I don't know how I remember that but I do. The problem with attackers is that one cannot have fun with some old ports as even if the services are opened (rare) they're filtered. Admittedly I always thought it'd be fun to try and pipe port 19 to a printer (remotely .. I'm terrible!) but I'm glad I never did try. Waste of paper and resources and would not be funny. The Ents might dislike the murdering of trees and so would I.

`finger` comes to mind as a good example of fun totally ruined :(( and I'm not even referring to the famous coke machine that was connected to the Internet. I remember checking it years ago even though I was not there and I don't like any carbonated drinks. It was brilliant engineering.


My root .plan file is:

```
# chown -R root:root /universe
# chmod -R u=rwx,g=rx,o=rx /universe
```

and the .plan for my main user wouldn't surprise you one bit:

```
Three Rings for the Elven-kings under the sky,
Seven for the Dwarf-lords in their halls of stone,
Nine for Mortal Men doomed to die,
One for the Dark Lord on his dark throne
In the Land of Mordor where the Shadows lie.
One Ring to rule them all, One Ring to find them,
One Ring to bring them all and in the darkness bind them
In the Land of Mordor where the Shadows lie. 
```

.. though I ought to put Black Speech there which somehow I memorised also. Well anyway I'll be leaving soon. I'll do more tomorrow. Good night!

**Pull request merged**
