### PR TITLE
Remove space at EOL from 2020/ferguson2/recode.md

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
thanks&nbsp;&nbsp;&nbsp;&nbsp;@xexyl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

.. with lots of "_&nbsp_;"'s

**Comment by lcn2** [comment]
We verified that the markdown change had no effect on the HTML generated for the `2020/ferguson2/recode.html` page.

**Comment by xexyl** [comment]
> thanks    @xexyl                    
> 
> .. with lots of trailing _&nbsp_;'s

```c
#include <string.h>
#include <stdio.h>
int is_html_space(
char *s){return s ?(!
strcmp(s,"&nbsp;")?1:0):0;}
int main(int A,char**V){for(A=1;
A[V];++A)printf("%d",is_html_\
space(V[A]));}
```

```sh
$ ./is_html_space '&nbsp' '&nbsp;' '&psbn;' '&nbsp&' 'foo' 'bar' 'baz'
0100000$
```

Yes .. much more complicated than just checking for ' ' :)

**Comment by xexyl** [comment]
> We verified that the markdown change had no effect on the HTML generated for the `2020/ferguson2/recode.html` page.

Thanks!

**Comment by xexyl** [comment]
> > thanks    @xexyl                    
> > .. with lots of trailing _&nbsp_;'s
> 
> ```c
> #include <string.h>
> #include <stdio.h>
> int is_html_space(
> char *s){return s ?(!
> strcmp(s,"&nbsp;")?1:0):0;}
> int main(int A,char**V){for(A=1;
> A[V];++A)printf("%d",is_html_\
> space(V[A]));}
> ```
> 
>  ```shell
> $ ./is_html_space '&nbsp' '&nbsp;' '&psbn;' '&nbsp&' 'foo' 'bar' 'baz'
> 0100000$
> ```
> 
> Yes .. much more complicated than just checking for ' ' :)

.. not that I couldn't have simplified it of course ...

**Pull request merged**
