### PR TITLE
Get 1994/ldb to compile

### PR DESCRIPTION
**Pull request by xexyl**
This required some -includes at the compiler line as well as use of the
comma operator as srand() returns void but it was used in || expression.

### CODE REVIEW

**Comment by xexyl** [comment]
The merge branch was because I went to do `git commit --amend` to get the log (as after one pull request it doesn't show the notes) but I forgot to delete it to make it so that no additional commit is made ... but of course one was so I had to push which required a merge.

This was a fun entry to fix (simple though it was) and a fun entry in general!

**Comment by xexyl** [comment]
> 1994/ldb thanks you :) @xexyl

Why do I get the feeling there might something significant about the way you put this? :-) .. am I wrong and it was just a fun way to put it or was there something more ?

**Comment by lcn2** [comment]
> Did Bourne shell not support globs like `ls foo*` ? I probably have used it on older systems (long time ago) but I don't recall .. I thought it worked always but maybe it's a limitation of the entry ? If so should we try fixing it ? (Possibly not: would guess it would make it much longer but worth asking anyway .. maybe as an alt version?)

The original Bourne shell DID support globs such as `foo`.

**Comment by xexyl** [comment]
> > Did Bourne shell not support globs like `ls foo*` ? I probably have used it on older systems (long time ago) but I don't recall .. I thought it worked always but maybe it's a limitation of the entry ? If so should we try fixing it ? (Possibly not: would guess it would make it much longer but worth asking anyway .. maybe as an alt version?)
> 
> The original Bourne shell DID support globs such as `foo*` as in:
> 
> ```shell
> ls foo*
> ```

I figure it was just a limitation of the entry. Thanks for confirming! Should we add a note in the readme ? I'll look at doing that actually ... maybe after replying to the other comment and making another I thought of (an idea for each entry - Makefile specific).

**Comment by xexyl** [comment]
> > > Did Bourne shell not support globs like `ls foo*` ? I probably have used it on older systems (long time ago) but I don't recall .. I thought it worked always but maybe it's a limitation of the entry ? If so should we try fixing it ? (Possibly not: would guess it would make it much longer but worth asking anyway .. maybe as an alt version?)
> > 
> > 
> > The original Bourne shell DID support globs such as `foo*` as in:
> > ```shell
> > ls foo*
> > ```
> 
> I figure it was just a limitation of the entry. Thanks for confirming! Should we add a note in the readme ? I'll look at doing that actually ... maybe after replying to the other comment and making another I thought of (an idea for each entry - Makefile specific).

... ah I already did note it though not so simply as globs don't work. Maybe I should do that. What do you think?

**Comment by lcn2** [comment]
> > > > Did Bourne shell not support globs like `ls foo*` ? I probably have used it on older systems (long time ago) but I don't recall .. I thought it worked always but maybe it's a limitation of the entry ? If so should we try fixing it ? (Possibly not: would guess it would make it much longer but worth asking anyway .. maybe as an alt version?)
> > > 
> > > 
> > > The original Bourne shell DID support globs such as `foo*` as in:
> > > ```shell
> > > ls foo*
> > > ```
> > 
> > 
> > I figure it was just a limitation of the entry. Thanks for confirming! Should we add a note in the readme ? I'll look at doing that actually ... maybe after replying to the other comment and making another I thought of (an idea for each entry - Makefile specific).
> 
> ... ah I already did note it though not so simply as globs don't work. Maybe I should do that. What do you think?

Good idea to note that.

**Pull request merged**
