### PR TITLE
Restore anonymous locations to anonymous authors

### PR DESCRIPTION
**Pull request by xexyl**
In the case of 1984, 2001 and 2005 the anonymous authors had location 
codes but the country code for anonymous locations is XX. This has been
done and the authors.html, location.html and the respective index.html 
files have been rebuilt.

One file was not touched because I was not sure how to best approach it
as an email was provided and possibly other things too (in particular a
second author of 2015/endoh1).

### CODE REVIEW

**Comment by lcn2** [comment]
This change incorrectly assumes that an anonymous author wants their location to also be anonymous.  We know in at least one case this is NOT correct. 

We plan to reject this pull request as a result.

**Comment by xexyl** [comment]
> This change incorrectly assumes that an anonymous author wants their location to also be anonymous. We know in at least one case this is NOT correct.
> 
> We plan to reject this pull request as a result.

Ah. I did not think of that as location can be identifying. That's fair enough. I'll not do more of this nature unless I find a mastodon handle or something like that.

**Comment by xexyl** [comment]
> > This change incorrectly assumes that an anonymous author wants their location to also be anonymous. We know in at least one case this is NOT correct.
> > We plan to reject this pull request as a result.
> 
> Ah. I did not think of that as location can be identifying. That's fair enough. I'll not do more of this nature unless I find a mastodon handle or something like that.

... which will be highly unlikely I might add ... but maybe I'll come across one in the future. Not planning on trying to find more links or accounts though. But point is I won't do anything but that.

**Comment by lcn2** [comment]
> > This change incorrectly assumes that an anonymous author wants their location to also be anonymous. We know in at least one case this is NOT correct.
> 
> > 
> 
> > We plan to reject this pull request as a result.
> 
> 
> 
> Ah. I did not think of that as location can be identifying. That's fair enough. I'll not do more of this nature unless I find a mastodon handle or something like that.

We are now in a stalled situation where future pull requests seem to try and replay this closed pull request.

**Comment by xexyl** [comment]
> > > This change incorrectly assumes that an anonymous author wants their location to also be anonymous. We know in at least one case this is NOT correct.
> > 
> > 
> > > 
> > 
> > 
> > > We plan to reject this pull request as a result.
> > 
> > 
> > Ah. I did not think of that as location can be identifying. That's fair enough. I'll not do more of this nature unless I find a mastodon handle or something like that.
> 
> We are now in a stalled situation where future pull requests seem to try and replay this closed pull request.

Ugh. I can't address anything today but if you tell me what I might do let me know please. Otherwise I guess you'll figure it out. Some pretty important changes are made in the remaining open ones.

**Comment by lcn2** [comment]
Yes, it seems we cannot proceed using an iPhone.  Maybe the desktop will allow us to better process the future pull requests? Not sure 🤔.. will have to investigate how to fix this problem later.

**Comment by xexyl** [comment]
> > > > This change incorrectly assumes that an anonymous author wants their location to also be anonymous. We know in at least one case this is NOT correct.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > We plan to reject this pull request as a result.
> > > 
> > > 
> > > Ah. I did not think of that as location can be identifying. That's fair enough. I'll not do more of this nature unless I find a mastodon handle or something like that.
> > 
> > 
> > We are now in a stalled situation where future pull requests seem to try and replay this closed pull request.
> 
> Ugh. I can't address anything today but if you tell me what I might do let me know please. Otherwise I guess you'll figure it out. Some pretty important changes are made in the remaining open ones.

Maybe you could reopen it and merge and then change them back? I think you're able to do that? Just a thought. Anyway must leave for now.

**Comment by xexyl** [comment]
Sorry for the mess that I caused! I almost didn't do it but as location can be identifying I went ahead with it, against better or worse judgement. 

Tomorrow I likely won't get as much done and Thursday I have to go back to the doctor (second post surgery appointment) so I probably won't do as much that day either. But maybe Wednesday I can do more.

**Comment by xexyl** [comment]
This makes me think though: perhaps an FAQ item should be added about future handling of anonymous entries as I know the idea you have had has changed this. Seems like it should be discussed?

Well anyway have a good rest of your day .. off again. Just had power restored but soon will be leaving for food anyway.

**Comment by xexyl** [comment]
Sorry about commit 4e8aaedaec327f5f9bf50aad7d6c54188172091f. More annoying is the fact you had to do it in the first place. I pondered trying to do it for you but I was unable to at that point. I still think you should add an FAQ entry about anonymous entries at least for future contests if not past. I don't really know what you have entirely in mind: obviously since this is an area that only the judges can know. And that was against better judgement on my part. I knew better but for some reason I was compelled to do it.

I also didn't expect that it would be a problem if it had to be closed. If I had had time I would have, as said above, fixed it myself. But as for the FAQ I have a while before I'll look at the FAQ for formatting etc. so you have time to do that now. It might also be a good idea to expand the entry about fixing anonymous author information.

I did the last part but I think the other parts might be good to add. That change I just did made me think of another change with the Makefile but if I do that it'll have to be done another day. Leaving now and won't be back until at least tomorrow most likely.

**Comment by xexyl** [comment]
Hopefully https://github.com/ioccc-src/temp-test-ioccc/commit/b12c47b6166f1ccb336e3d51f1b7a1babcadc56a will be helpful to prevent this kind of problem in the future. But to make it easier to see that only has to do with author location. It doesn't talk about author information in general like email or other things. I would add that but I have to go and I also don't know where you want it so like with other details about such authors I am leaving that to you.

**Pull request closed without merging**
