### PR TITLE
Remove hint.html, rename hint.text etc. to README.md

### PR DESCRIPTION
**Pull request by xexyl**
I've also updated references in files from hint.text and hint.txt to README.md.

I am not clear on the implications of that other than the fact that changing the names of those files would break the references including links. That's one I'm especially unclear about. Do the links need to refer to index.html or some other file instead? I guess so but I don't know and I don't know which one either.

### CODE REVIEW

**Comment by lcn2** [comment]
This is a great start .. thanks @xexyl

**Comment by xexyl** [comment]
> This is a great start ..

Thank you my friend!

> thanks @xexyl

You are most welcome good sir!

## Testing

Would it be possible to have a test subdomain of the main IOCCC website OR a temp / test subdirectory that has all the changes of THIS repo so we can make sure everything looks and works okay ? It might be a good way to verify that everything can be merged to the real website later on.

**Comment by lcn2** [comment]
> > This is a great start ..
> 
> 
> 
> Thank you my friend!
> 
> 
> 
> > thanks @xexyl
> 
> 
> 
> You are most welcome good sir!
> 
> 
> 
> ## Testing
> 
> 
> 
> Would it be possible to have a test subdomain of the main IOCCC website OR a temp / test subdirectory that has all the changes of THIS repo so we can make sure everything looks and works okay ? It might be a good way to verify that everything can be merged to the real website later on.
> 
> 

The `temp-test-ioccc` repo is available at the [temp-test-ioccc web site](https://ioccc-src.github.io/temp-test-ioccc/).  You have to wait about a minute or two after the repo / pull request is performed for the web site to catch up.


0

**Comment by xexyl** [comment]
> > > This is a great start ..
> > 
> > 
> > Thank you my friend!
> > > thanks @xexyl
> > 
> > 
> > You are most welcome good sir!
> > ## Testing
> > Would it be possible to have a test subdomain of the main IOCCC website OR a temp / test subdirectory that has all the changes of THIS repo so we can make sure everything looks and works okay ? It might be a good way to verify that everything can be merged to the real website later on.
> 
> The `temp-test-ioccc` repo is available at the [temp-test-ioccc web site](https://ioccc-src.github.io/temp-test-ioccc/). You have to wait about a minute or two after the repo / pull request is performed for the web site to catch up.
> 
> 0

Oh thank you! That's helpful. I'll have to keep that in mind when I start working on the files (which I'm afraid most likely will not be today).

**Pull request merged**
