### PR TITLE
Make 2001/anonymous more like it was before

### PR DESCRIPTION
**Pull request by xexyl**
In other words try and make it so that the munmap(),close(),execv() is 
like how it was before (comma operator in succession) though of course
the munmap() and close() were not there until yesterday's fix as text
file busy error (ETXTBSY) was not a problem in the past with this entry.

### CODE REVIEW

**Comment by xexyl** [comment]
.. I still want to change the magic stuff referenced in the Makefile to be back to where it was before if possible but for now this is still better .. I'll look at the other stuff later: maybe today maybe not. I'm hoping I can rest soon though I am feeling like I won't be able to yet.

Still this is an improvement.

**Comment by xexyl** [comment]
.. more to follow in a while .. going to see if I can rest. If I can't then I'll get back to it else I'll do it later .. making good progress with this though and I hope and think I can finish it today! Hope travels are going well my friend!

**Comment by lcn2** [comment]
who am i @xexyl

**Comment by xexyl** [comment]
> who am i @xexyl

My guess is that it would be something like ...

```sh
$ whoami
chongo
```

but that's just a hunch :-)

**Pull request merged**
