### PR TITLE
Format/typo check 2005/chia

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Getting a little head start. And the comments in this one (the code) are classic. Very funny. I don't personally hate java. There are some things I don't like about it I'm sure but it has an amazing graphics API at least. But as you would expect I'm drawn to C just as I am to puns like the one I just made.

**Comment by lcn2** [comment]
Thanks for reaching to 2005 @xexyl

**Comment by xexyl** [comment]
> Thanks for reaching to 2005 @xexyl

Minus 2004/gavin of course but hopefully that won't take too long. I think it won't once I start it. Might not be able to document how to use it as such but perhaps you would like to do that .. or else I can later on look at how to use QEMU.

**Comment by lcn2** [comment]
> > > Thanks for reaching to 2005 @xexyl
> 
> > 
> 
> > Minus 2004/gavin of course but hopefully that won't take too long. I think it won't once I start it. Might not be able to document how to use it as such but perhaps you would like to do that .. or else I can later on look at how to use QEMU.
> 
> 
> 
> Now ... [Go the .... to sleep!](https://www.youtube.com/watch?v=teIbh8hFQos) :-)
> 
> 

Will do .. just finished a few `faq.md` edits .. going to 😴

**Comment by xexyl** [comment]
> > > > Thanks for reaching to 2005 @xexyl
> > 
> > 
> > > 
> > 
> > 
> > > Minus 2004/gavin of course but hopefully that won't take too long. I think it won't once I start it. Might not be able to document how to use it as such but perhaps you would like to do that .. or else I can later on look at how to use QEMU.
> > 
> > 
> > Now ... [Go the .... to sleep!](https://www.youtube.com/watch?v=teIbh8hFQos) :-)
> 
> Will do .. just finished a few `faq.md` edits .. going to 😴

Good! And thanks for the note. I'll pull the changes soon.


Sleep well! I'm going to finish 2005/aidan and then try and rest myself. After that I'll go to 2004/gavin and then I can start on the third entry of 2005.

Good night! (even though it's morning :-) )

**Comment by xexyl** [comment]
Oh I see you made quite a few additions. I'll go through them too to look for typos and any other issues.

Thanks for the pull request related ones! That was one that I was not even sure how to go about doing .. though if you don't explain how to fork and open one (though you did mention fork in one FAQ) then I'll have to figure it out.

Anyway sleep tight!

**Pull request merged**
