### PR TITLE
Add alt code to 1993/rince

### PR DESCRIPTION
**Pull request by xexyl**
This is based on the suggestion of the judges that some people might 
want to slow the game down a bit.

It is easy to configure at compile time like:

    make CDEFINE=-DZ=18 clobber alt

More details are in the README.md file.

Updated .gitignore and thanks file (not just for this but also 
making something else clearer in another entry).

### CODE REVIEW

**Comment by xexyl** [comment]
Off to do other things now ... will do more tomorrow hopefully if not later today but later today seems unlikely.

Good day!

**Comment by lcn2** [comment]
As this pull request is after pull request #988 and pull request #988 is in "Draft pull requests cannot be merged." state, we will wait until either:

Pull request #988 is withdrawn

or

Pull request #988 is moved out of draft state.

or

We reject #988 :-)

Either way, the nature of how GitHub processes pull requests (i.e., merging all incomplete pull requests prior to the pull request being merged) we will hold off on all future pull requests while this is the case.

**Comment by xexyl** [comment]
I will close the other for now.

**Comment by xexyl** [comment]
I will close it tomorrow actually and then we can do this one and discuss the other one. 

So just keep this open for the time being please. 

Have a great night! Didn't know this would be a problem :(

**Comment by xexyl** [comment]
Question: should I change it to not draft? Or should I close it and we discuss it? I will do whichever one tomorrow.

**Pull request merged**
