### PR TITLE
Change task wrt try scripts in todo

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
You did a thumbs up but haven't merged it. I guess it will be done soon but I want to be sure you didn't get distracted (say by the sort discussion) and forget (not that I think your memory is that poor :-) ).

Anyway back tomorrow.

**Comment by lcn2** [comment]
Thank you very much @xexyl for your all of your hard work on this matter of trying.

**Comment by xexyl** [comment]
> Thank you very much @xexyl for your all of your hard work on this matter of trying.

Welcome. I'll take a look at the tool tomorrow. It seems kind of funny but interesting too. Funny I say but I actually thought of it as I made the commit.

Have a great night!

**Comment by xexyl** [comment]
.. though `sgi` makes me think of SGI and also just one char short of `sgit`. Good thing I made that into a repo!

Anyway I'll do more tomorrow morning.

**Comment by lcn2** [comment]
> .. though `sgi` makes me think of SGI and also just one char short of `sgit`. Good thing I made that into a repo!
> 
> 
> 
> Anyway I'll do more tomorrow morning. 

As a former SGI employee the pun was intentional 🤓

**Comment by xexyl** [comment]
> > .. though `sgi` makes me think of SGI and also just one char short of `sgit`. Good thing I made that into a repo!
> > Anyway I'll do more tomorrow morning.
> 
> As a former SGI employee the pun was intentional 🤓

I remember you telling me that you worked there. That's even better then!

**Pull request merged**
