### PR TITLE
Rename try.me.sh scripts to try.sh

### PR DESCRIPTION
**Pull request by xexyl**
This is to make them consistent with the others called try.sh which 
seems better named as it's under the try section.

The manifest files in tmp/ have been updated as well, including the
macOS Numbers file.

### CODE REVIEW

**Comment by xexyl** [comment]
... okay going to try resting now .. hope to do more later on ... still unsure how I feel versus yesterday. Maybe a bit better but too early to tell yet.

**Comment by lcn2** [comment]
Approve, Yoda does. 😁 @xexyl

**Comment by xexyl** [comment]
> Approve, Yoda does. 😁 @xexyl

Commit, approve, pull.

**Comment by xexyl** [comment]
.. and all your references to SW really tells me I should watch them again .. haven't watched them for decades. Oh well, maybe I'll get them some day ...

**Pull request merged**
