### PR TITLE
Update FAQ about different image tools

### PR DESCRIPTION
**Pull request by xexyl**
Three different image utility packages have been described for macOS (MacPorts and Homebrew) and Red Hat Linux. I don't have any other linux so I can't explain how to do those with certainty (except for copy/paste somewhere which might or might not be correct).

### CODE REVIEW

**Comment by xexyl** [comment]
Would you please update the answers for debian ?

**Comment by xexyl** [comment]
That was fast!

**Comment by lcn2** [comment]
> That was fast!

Not for updating Debian .. that is still being worked on.

**Comment by xexyl** [comment]
> > That was fast!
> 
> Not for updating Debian .. that is still being worked on.

I meant the merge. But thanks for taking care of it.

**Comment by lcn2** [comment]
# QUESTION 

Why were some of the \`\`\`sh blocks indented in `faq.md`?

**Comment by xexyl** [comment]
> # QUESTION
> Why were some of the ```sh blocks indented in `faq.md`?

That was an attempt to get the alignment right .. and then I forgot to check the formatting. Because the list item was indented but then the code is at the first column so it doesn't look right.

That's not relevant to this commit though, right?

**Comment by xexyl** [comment]
> > # QUESTION
> > Why were some of the ```sh blocks indented in `faq.md`?
> 
> That was an attempt to get the alignment right .. and then I forgot to check the formatting. Because the list item was indented but then the code is at the first column so it doesn't look right.
> 
> That's not relevant to this commit though, right?

I forgot as yesterday I had a banging headache. If it doesn't come out right then we can just not worry about syntax highlighting OR else say the indenting is not a problem. I don't know what you would prefer. I'm trying to remember where it was in the FAQ.

**Comment by xexyl** [comment]
Okay I see it did not come out right - as I feared. What do you propose is done?

**Comment by lcn2** [comment]
> > # QUESTION
> 
> > Why were some of the ```sh blocks indented in `faq.md`?
> 
> 
> 
> That was an attempt to get the alignment right .. and then I forgot to check the formatting. Because the list item was indented but then the code is at the first column so it doesn't look right.
> 
> 
> 
> That's not relevant to this commit though, right?

Is the intending needed for the file, or in general?

We are concerned that such intending isn't done elsewhere and we do not know the impact (positive or negative) of indenting such blocks.

**Comment by xexyl** [comment]
> > > # QUESTION
> > 
> > 
> > > Why were some of the ```sh blocks indented in `faq.md`?
> > 
> > 
> > That was an attempt to get the alignment right .. and then I forgot to check the formatting. Because the list item was indented but then the code is at the first column so it doesn't look right.
> > That's not relevant to this commit though, right?
> 
> Is the intending needed for the file, or in general?
> 
> We are concerned that such intending isn't done elsewhere and we do not know the impact (positive or negative) of indenting such blocks.

That was markdown rendering doing it with lists. I don't think it's needed at all but markdown tends to disagree (or at least GitHub's rendering?).

**Comment by xexyl** [comment]
The solution is to not have the `sh` part added and instead just have the block of text indented to make it code.

Another possibility would to make it not a list in the truest sense (escape the number I guess?).

I guess the former would look nicer but I don't know. There might be other places that this problem occurs too but I'll be looking for those later as well.

**Comment by lcn2** [comment]
> The solution is to not have the `sh` part added and instead just have the block of text indented to make it code.
> 
> 
> 
> Another possibility would to make it not a list in the truest sense (escape the number I guess?).
> 
> 
> 
> I guess the former would look nicer but I don't know. There might be other places that this problem occurs too but I'll be looking for those later as well.

Good idea, @xexyl, about removing the \`\`\`sh part for that numbered list near the top of the `faq.md` file.

See e74a5d1c96af8ad4bdbec3c12e8c362d65108838

**Comment by xexyl** [comment]
> > The solution is to not have the `sh` part added and instead just have the block of text indented to make it code.
> > Another possibility would to make it not a list in the truest sense (escape the number I guess?).
> > I guess the former would look nicer but I don't know. There might be other places that this problem occurs too but I'll be looking for those later as well.
> 
> Good idea, @xexyl, about removing the ```sh part for that numbered list near the top of the `faq.md` file.
> 
> ## UPDATE 0
> See the latest commit.

Thanks.

**Comment by xexyl** [comment]
I made some minor fixes to it .. looks good now.

**Comment by lcn2** [comment]
> Would you please update the answers for debian ?

Fixed, among a number of other things, in commit cca4189e84b79fec4f115cfd36e48bd5fff493e1.

**Comment by lcn2** [comment]
> I made some minor fixes to it .. looks good now.

Hopefully they were not impacted by commit cca4189e84b79fec4f115cfd36e48bd5fff493e1.

**Comment by xexyl** [comment]
> > Would you please update the answers for debian ?
> 
> Fixed, among a number of other things, in commit [cca4189](https://github.com/ioccc-src/temp-test-ioccc/commit/cca4189e84b79fec4f115cfd36e48bd5fff493e1).

Thanks. I forgot about this request. I hope my update did not conflict. If it did I'll fix it.

**Comment by xexyl** [comment]
> > I made some minor fixes to it .. looks good now.
> 
> Hopefully they were not impacted by commit [cca4189](https://github.com/ioccc-src/temp-test-ioccc/commit/cca4189e84b79fec4f115cfd36e48bd5fff493e1).

Yes I just had the same thought. I forgot about the request. I can always fix it if necessary.

**Comment by xexyl** [comment]
> > I made some minor fixes to it .. looks good now.
> 
> Hopefully they were not impacted by commit [cca4189](https://github.com/ioccc-src/temp-test-ioccc/commit/cca4189e84b79fec4f115cfd36e48bd5fff493e1).

Speaking of this commit I just looked at the log: I really like the concept behind it. Thanks! I'll look at the text another time and typo check it.

I have two cats on my bed now when I'd rather try and sleep but it's worth it. In a bit I might work on the entries of 2018 but right now just going to kind of lie back and relax. Hope you're sleeping well!

**Pull request merged**
