### PR TITLE
Typo fixes in 2000/natori/README.md

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Off to bed ... just noticed this as I wanted to look at the phase of the Moon and by chance saw the typos too.

**Comment by lcn2** [comment]
🌕🌖🌗🌘🌑🌒🌓🌔🌕@xexyl

**Comment by xexyl** [comment]
> 🌕🌖🌗🌘🌑🌒🌓🌔🌕@xexyl

> 'Wraiths!' he wailed. 'Wraiths on wings! The Precious is their master. They see everything, everything. Nothing can hide from them. Curse the **White Face**! And they tell Him everything. He sees, He knows. Ach, <i>gollum</i>, <i>gollum</i>, <i>gollum</i>!' It was not until the moon had sunk, westering far beyond Tol Brandir, that he would get up or make a move.

:-)

**Comment by xexyl** [comment]
> 🌕🌖🌗🌘🌑🌒🌓🌔🌕@xexyl

> 🌕🌖🌗🌘🌑🌒🌓🌔🌕@xexyl

--

'Wraiths!' he wailed. 'Wraiths on wings! The Precious is their master. They see everything, everything. Nothing can hide from them. Curse the **White Face**! And they tell Him everything. He sees, He knows. Ach, <i>gollum</i>, <i>gollum</i>, <i>gollum</i>!' It was not until the moon had sunk, westering far beyond Tol Brandir, that he would get up or make a move.

--

:-)

**Comment by xexyl** [comment]
.. and that's very cool that there is an emoji for all the phases of the Moon! I had no idea. I love how you did that. Of course as an astronomer you'd know the name of them all and much more about them too.

I guess you knew that billions of years ago it was much, much closer to the Earth and so the winds were much more deadly than today's cyclones/hurricanes. Now it's ~250m miles away though I know it varies hence the average (though I think it's more like 240 something).

Anyway: I have always loved White Face and not liked Yellow Face: never liked Yellow Face!

**Comment by xexyl** [comment]
Thought I clicked comment but I was so tired I did not whether trying to sleep again or something else I have no idea. Anyway.

I'm also glad I got the White Face entry to work. Actually it wasn't that hard to fix. I know it crashed in linux and didn't even compile in macOS but of course now it works in both. Was a pretty simple fix. I find it fun that it has to call another function (it = `main()`) but then that function calls `main()` itself which calls the original function which calls the Moon function (well `moon()` in this case) ...

Hope you have a great day!

**Pull request merged**
