### PR TITLE
Minor fixes in 1989/tromp/README.md

### PR DESCRIPTION
**Pull request by xexyl**
This has not been format/typo checked yet.

### CODE REVIEW

**Comment by xexyl** [comment]
Look at what this does ....

Screenshot 2023-10-19 at 10 29 31

**Comment by xexyl** [comment]
And I'm afraid I might not get much more done today ... we'll see but not feeling that great: still trying to recover from yesterday. I have to go afk for now but I hope I can get more done in a bit. Unfortunately I have also run into some problems / things to consider with some of the files in 1989 which is also one of the things that's delaying me. If necessary I'll skip them and go on to 1990 or maybe focus on the alt code section headings or something else. Anyway that's for later today or else tomorrow ...

**Comment by lcn2** [comment]
Thanks .. lots of good edits today @xexyl

**Comment by xexyl** [comment]
> Thanks .. lots of good edits today @xexyl

Thank you! Not as many as I'd like I must say but still good progress I guess.

**Comment by xexyl** [comment]
> Look at what this does ....
> 
> Screenshot 2023-10-19 at 10 29 31

Yesterday I improved upon this .. will take another screenshot.

**Comment by xexyl** [comment]
Screenshot 2023-10-21 at 04 55 12

... and the link goes to: [In name game, Loser wins and brother Winner loses](https://web.archive.org/web/20181023221954/https://www.chicagotribune.com/news/ct-xpm-2002-07-31-0207310310-story.html)

:-)

(which I showed you before but anyway I felt it would be good to add for enjoyment and if I'm going to do it this way I might as well go all the way)

**Pull request merged**
