### PR TITLE
Add try.sh to 1985/sicherman

### PR DESCRIPTION
**Pull request by xexyl**
The Makefile was also modified to have a sicherman.alt rule as it 
requires -traditional-cpp. There is an argument that this should be 
removed and instead the alt2 version (which is compiled if a compiler 
fails to compile sicherman.c because of the 'wrong' number of args to
main() - one arg) would become the alt version because if someone wants
to try the original code they can look at sicherman.orig.c. This can be
done another time if it's worth doing (which I think it might be).

### CODE REVIEW

**Comment by xexyl** [comment]
What do you think of my thought about the alt code? Do you agree that the alt2 should become the alt and the current alt is removed?

**Comment by lcn2** [comment]
> What do you think of my thought about the alt code? Do you agree that the alt2 should become the alt and the current alt is removed?

Yes.

**Comment by lcn2** [comment]
> What do you think of my thought about the alt code? Do you agree that the alt2 should become the alt and the current alt is removed?

Seems like a good fix.  In general not having "AltN" (for N > 1) if we can help it is also good.

Yes.  The try alt code seems reasonable too.

**Comment by xexyl** [comment]
> > What do you think of my thought about the alt code? Do you agree that the alt2 should become the alt and the current alt is removed?
> 
> Seems like a good fix. In general not having "AltN" (for N > 1) if we can help it is also good.
> 
> Yes. The try alt code seems reasonable too.

Done. See 8ad90e157e96d263bfd12786d00ddef3a3ee1733. Off to do other things for the day .. will continue either a bit tomorrow or else Tuesday though I'm sure to say something else tomorrow too: well you know what I mean. Good day!

**Pull request merged**
