### PR TITLE
Add my GitHub handle to my json file

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
🥌 😄 @xexyl

**Comment by xexyl** [comment]
> 🥌 😄 @xexyl

I unfortunately cannot for the life of me figure out what that emoji is .. but I gather that it's amusing somehow given the second one! What is it please if you get a chance ?

**Comment by lcn2** [comment]
> > 🥌 😄 @xexyl
> 
> 
> 
> I unfortunately cannot for the life of me figure out what that emoji is .. but I gather that it's amusing somehow given the second one! What is it please if you get a chance ?

Curling 🥌 stone with a handle

**Comment by xexyl** [comment]
> > > 🥌 😄 @xexyl
> > 
> > 
> > I unfortunately cannot for the life of me figure out what that emoji is .. but I gather that it's amusing somehow given the second one! What is it please if you get a chance ?
> 
> Curling 🥌 stone with a handle

Ah ... because of 'handle' in the log summary. Thanks.

**Pull request merged**
