### PR TITLE
Add script primes.sh to 1985/august for fun

### PR DESCRIPTION
**Pull request by xexyl**
The inspiration of the script is based on a 'try' command I added to the README.md a while back to have more fun with the entry. The difference is that it allows you to specify the number of lines to print (or up to the number of lines).

There might be some misleading output in a way but this is a mystery for users to solve.

### CODE REVIEW

**Comment by xexyl** [comment]
I am sure you know what the misleading thought is but it's only misleading if you look at it in a way. In other ways it's not misleading at all so the statement is also misleading. But I think this is fun to ponder.

**Comment by xexyl** [comment]
I have a zoom meeting soon but I hope to return to this later on. I need a break before the meeting though and I might break longer than that as well as I've been doing this for a long time today. If I don't return to it today I will continue tomorrow but I hope that I can do a bit more. Unfortunately I'm struggling on consistency in the entry I'm working on atm so it's better to stop for now as I'm sure you'd agree.

**Comment by lcn2** [comment]
👍 @xexyl

**Comment by xexyl** [comment]
> 👍 @xexyl

Given the reaction to my other comment I guess you do know what the misleading thing is? But if not it's of course how can it be both decimal and binary at the same time? And yet .. it is :-) .. at least to the `primes` program. Then again it's also NOT both to the program :-)

So is it decimal and binary or is it just binary? Or maybe it's just decimal? Or perhaps it's neither? Maybe I put a hex on the mystery? :-)

**Pull request merged**
