### PR TITLE
Remove erroneous line in winner-handles.csv

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
> !winner-handle @xexyl

!twitter

**Comment by lcn2** [comment]
> > !winner-handle @xexyl
> 
> !twitter .. though maybe that should be twitter for not a winner handle? :-) That was the idea anyway ...

You may note that in files such as `tmp/winners.csv` we refer to "_deprecated twitter handle_" and "_deprecated_twitter_".

We do not want to have any association with twitter.    We do plan to maintain historic twitter information in the JSON files, so the "_deprecated twitter handle_" information will not be lost.

Nevertheless we are reluctant to include twitter information in easily accessed files (such as `README.md` and the eventual HTML files that will be generated from the markdown).   By "_reluctant_" we mean that while a final decision has not been reached, we are inclined to keep author twitter information in JSON files and not use it to generate `README.md` data.

As a reminder: we plan to use JSON files to generate the `README.md` lines from the 1st "_# award_" line up until the "_## To build:_" line.  Please don't edit `README.md` to remove twitter information now.  Let the tool that will generate those `README.md` lines do the job.  Besides, using a tool to generate those lines means that should we choose to public twitter handles in the future, a simple code change is all that is needed.

**Comment by xexyl** [comment]
> > > !winner-handle @xexyl
> > 
> > 
> > !twitter .. though maybe that should be twitter for not a winner handle? :-) That was the idea anyway ...
> 
> You may note that in files such as `tmp/winners.csv` we refer to "_deprecated twitter handle_" and "_deprecated_twitter_".
> 
> We do not want to have any association with twitter. We do plan to maintain historic twitter information in the JSON files, so the "_deprecated twitter handle_" information will not be lost.
> 
> Nevertheless we are reluctant to include twitter information in easily accessed files (such as `README.md` and the eventual HTML files that will be generated from the markdown). By "_reluctant_" we mean that while a final decision has not been reached, we are inclined to keep author twitter information in JSON files and not use it to generate `README.md` data.
> 
> As a reminder: we plan to use JSON files to generate the `README.md` lines from the 1st "_# award_" line up until the "_## To build:_" line. Please don't edit `README.md` to remove twitter information now. Let the tool that will generate those `README.md` lines do the job. Besides, using a tool to generate those lines means that should we choose to public twitter handles in the future, a simple code change is all that is needed.

Oh that comment had no association with README.md files so much as twitter is a loss now.

I'm only editing the formatting of README.md files and fixing links, not removing twitter, so no worries. I did however in a couple cases change it from twitter to mastodon.

**Comment by xexyl** [comment]
Oh .. just saw your other part about replies. Will do.

**Pull request merged**
