### PR TITLE
Add note about top prio issue 2006 to news

### PR DESCRIPTION
**Pull request by xexyl**
It might be useful to know that the majority of the files should be 
relatively quick to review and that of the three slower files one is 
almost done.

I did not change the date of the news update but this seems like a
useful change (though maybe better wording could be used). If the date 
is changed it would allow to update the status.json and status.html file
news date.

### CODE REVIEW

**Comment by xexyl** [comment]
Perhaps you'd like to take care of the status files? Or maybe you'd like to reword this? It was done quickly and I'm worn out but it felt like it would be good to note (not that I think many will be looking at the news necessarily, unless it's linked to in the index.html file .. not sure right now and must leave again for a bit) that the issue shouldn't take that much more time once the longer files are done.

**Comment by xexyl** [comment]
Another option: I can close this so we can discuss it (or not) and that way it won't cause a problem with other pull requests.

**Comment by xexyl** [comment]
> Another option: I can close this so we can discuss it (or not) and that way it won't cause a problem with other pull requests.

.. though I'm not sure what else I might do today. I'm hoping to look more at that other file but I don't know. I have other things i have to do and that incudes an appointment today and something i have to do before it. But there are other things too.

**Comment by xexyl** [comment]
Okay it seems that was not a problem. That's good .. was not sure with the way it was done due to the date being yesterday's and other things like that. But perhaps if you modify it or update status.json/status.html you could let me know. When I return here I will look at that other file starting at 2011.

**Comment by lcn2** [comment]
> Okay it seems that was not a problem. That's good .. was not sure with the way it was done due to the date being yesterday's and other things like that. But perhaps if you modify it or update status.json/status.html you could let me know. When I return here I will look at that other file starting at 2011.

See commit 87a444c50856e5fb90bc4c164e69cc0d3aa2e5cf

**Comment by xexyl** [comment]
> > Okay it seems that was not a problem. That's good .. was not sure with the way it was done due to the date being yesterday's and other things like that. But perhaps if you modify it or update status.json/status.html you could let me know. When I return here I will look at that other file starting at 2011.
> 
> 
> 
> See commit 87a444c50856e5fb90bc4c164e69cc0d3aa2e5cf

Thanks!

I am trying to hurry with the html files and I am just thankful that I am able to get anything done at all. Sleep has been incredibly awful. 

Waking up so many times. I believe that the sutures are still there. Symptoms still suggest it. Whether I will sleep better when that is resolved is unknown but I am pretty sure that this has been worse since the surgery. 

Not that I ever sleep well but it is amazing that I am able to function at all. 

Anyway I have been trying to prioritise the issue over other free time things. Hopefully I can get the long files done soon so that I can get the others done soon. 

Anyway that's an update. I will be back tomorrow. 

Have a great night!

**Pull request merged**
