### PR TITLE
Get all 1989 entries to compile

### PR DESCRIPTION
**Pull request by xexyl**
There were some which cannot be compiled under clang. One entry we used
    a patch from Yusuke Endoh to get the entry to compile; thank you Yusuke
    for your assistance! Another one we used a patch from Yusuke (thank
    you!) but I further fixed it so that it would work with clang. It had to
    be done: IOCCC Tetris has to work! This was done by changing the
    environment arg to main() to be a char * in main() itself rather than a
    char **. Using a char ** in main() third arg got it to compile but only
    one key worked with clang so I changed it to be not the third argument
    but a regular char * in main(). **a (third arg) evaluated correctly but
    *a[1] and onward was actually part of the environment. Again IOCCC
    Tetris has to work!
    
    I also fixed fubar to work which took a few tweaks.
    
    README.md files were also updated.

### CODE REVIEW

**Comment by xexyl** [comment]
> There were some which cannot be compiled under clang. One entry we used
> a patch from Yusuke Endoh to get the entry to compile; thank you Yusuke
> for your assistance! Another one we used a patch from Yusuke (thank
> you!) but I further fixed it so that it would work with clang. It had to
> be done: IOCCC Tetris has to work! This was done by changing the
> environment arg to main() to be a char * in main() itself rather than a
> char **. Using a char ** in main() third arg got it to compile but only
> one key worked with clang so I changed it to be not the third argument
> but a regular char * in main(). **a (third arg) evaluated correctly but
> *a[1] and onward was actually part of the environment. Again IOCCC
> Tetris has to work!

But then again ... can you blame me ? :-)

**Comment by xexyl** [comment]
Did you forget to merge this one ?

**Comment by lcn2** [comment]
Thank you for this completion of the compiling of the 1989 winners, @xexyl 

This whole request, as far as files changed, according to GitHub, includes the previous to pull requests to made. 

It is possible that this is just a GitHub reporting problem. When such seemingly compound, pull requests are merged, it doesn't seem to matter. It is possible that GitHub doesn't correctly repot what the pull request changed and is naively doing a simple diff with whatever it the top of the master branch. It is possible that the pull requests you submit are compact and precise and that GitHub fails to determine what actually changed in the individual pull request. 

We will be careful to process each pull request in the exact order they were submitted, just is case that matters.

**Comment by xexyl** [comment]
> Thank you for this completion of the compiling of the 1989 winners, @xexyl
> 
> This whole request, as far as files changed, according to GitHub, includes the previous to pull requests to made.
> 
> It is possible that this is just a GitHub reporting problem. When such seemingly compound, pull requests are merged, it doesn't seem to matter. It is possible that GitHub doesn't correctly repot what the pull request changed and is naively doing a simple diff with whatever it the top of the master branch. It is possible that the pull requests you submit are compact and precise and that GitHub fails to determine what actually changed in the individual pull request.
> 
> We will be careful to process each pull request in the exact order they were submitted, just is case that matters.

Sure. Is there a problem with merging this one or did you just not get to it yet ?

I guess it's the latter but I'll worry about that tomorrow if it's not done already. Hopefully the problem is resolved though yes it seems there is an issue with GitHub in some cases.

**Comment by xexyl** [comment]
I should say this is what it looks like normally - the commits from the previous pull requests. That's nothing new so it wasn't that. I think that must be a reporting issue like you say.

Anyway I'll check back tomorrow. Good day!

**Comment by lcn2** [comment]
By the way, we will delay the processing of this specific 
pull request, and push a small change to something else "completely different" (but in a same directory) later today, and then processes pull request. It will be a simple gratuitous change to a different file, just to test the "naive GitHub diff theory". 

We mention this so you don't become concerned that this pull request is being left pending for a bit longer.

**Comment by xexyl** [comment]
> By the way, we will delay the processing of this specific pull request, and push a small change to something else "completely different" (but in a same directory) later today, and then processes pull request. It will be a simple gratuitous change to a different file, just to test the "naive GitHub diff theory".
> 
> We mention this so you don't become concerned that this pull request is being left pending for a bit longer.

Ah thanks. You just caught me.

Leaving now for real. Enjoy your afternoon!

**Comment by xexyl** [comment]
...ironically If just noticed a problem so it's all good. Well not a problem but since tromp can compile now .. it shouldn't say it can't in some systems.

Good day!

**Comment by xexyl** [comment]
Hope you're okay .. since you said you planned on making some commits and then merge this.

I have not felt up to working on this repo today. I did start 1990 yesterday but I think I'll have to delay it until tomorrow - with the exception of a question about it in another thread which I'll add next.

**Comment by lcn2** [comment]
Pushing commits to the master branch, even a commit that conflicted with this pull request did not change what GitHub reports as "Files changed".

Thanks for your patience @xexyl while we tested this.

**Comment by xexyl** [comment]
> Pushing commits to the master branch, even a commit that conflicted with this pull request did not change what GitHub reports as "Files changed".
> 
Great! I'm pretty sure the problem was as I noted the other day.

> Thanks for your patience @xexyl while we tested this.

You are welcome for the pull request and the patience too which is no problem.

**Comment by xexyl** [comment]
BTW you might find this amusing:


```sh
$ diff xexyl-temp-test-ioccc/1989/tromp/tromp /usr/local/bin/tetris 
$
```

As in yes I installed it so I can play Tetris at my leisure! :-)

**Pull request merged**
