### PR TITLE
Many updates/fixes to 2018/burton2

### PR DESCRIPTION
**Pull request by xexyl**
This is a big commit but it should complete this entry and 2018 unless I
have missed something.

The make test rule was fixed. A script was not +x.

Renamed freqcount -> freqcount.sh (for browser/display).

Renamed mkkeywords -> mkkeywords.sh (for browser/display).

Renamed runtest -> runtest.sh (for browser/display).

Renamed spotcheck -> spotcheck.sh (for browser/display).

Renamed spotdiff -> spotdiff.sh (for browser/display).

Made tac.man proper man format and renamed tac.1.

Added tokcount.sh - a script that the author included in the remarks but
not in a script.

The renaming of files should be okay including the manifest (it is
believed this is true anyway).

Add try.sh script.

The READ_ME.txt was deleted as it had been renamed to author-README.txt
but the former was never deleted. This file was typo/format checked.

Format/typo check README.md file.

### CODE REVIEW

**Comment by xexyl** [comment]
I believe that 2018 is now done!

I have other things I must take care of but I might be able to do a bit more later on. That's not yet known. Depends on a number of factors.

**Comment by lcn2** [comment]
Excellent @xexyl thanks

**Comment by xexyl** [comment]
> Excellent @xexyl thanks

Thank you as well my good friend! I'm hoping in a bit (hopefully first a rest but that's not certain .. kind of a difficult situation right now) to start working on 2019. I have a (surprise :-) :-) ) typo fix in the ioccc_status.sh script to add too (I only saw it because I was downstairs at the server waiting for the dogs to want to come in and I  pulled recent changes - hadn't done so in quite some while - and opened it for some reason or another). But of course it's just that I don't like typos esp my own (okay any typos but you know :-) ).

**Comment by xexyl** [comment]
BTW: this was pull request 1697: a fine number for its prime property!

**Comment by xexyl** [comment]
> BTW: this was pull request 1697: a fine number for its prime property!

Well okay: 1697 have been closed (which includes merged) .. it's actually a higher number for the `#[0-9]+`.

**Pull request merged**
