### PR TITLE
Fix a fix in 1998/schnitzi

### PR DESCRIPTION
**Pull request by xexyl**
In particular arg check was invalid. This was one of the programs that 
was thought it should be checked as it's such a beautiful program.

### CODE REVIEW

**Comment by xexyl** [comment]
I've not done anything else with this entry. I have to go afk now .. might do more of 1998 later on today but not sure. Anyway I got through 1996 which is great progress even if I don't get through 1998. I'm going faster than I anticipated. Today was a kind of slow day though. I hope tomorrow I make more progress than today but even so I feel like I did make good progress today.

**Comment by xexyl** [comment]
Did you by accident not merge this one ? I'll hold off on doing a pull until it is merged but wanted to make sure you didn't forget it. I presume you got pulled away but just in case ...

**Comment by lcn2** [comment]
Merged

**Comment by xexyl** [comment]
> Merged

Yep .. thanks!

I'm indeed done for the day but I'll do more tomorrow. Have a great rest of your day!

**Pull request merged**
