### PR TITLE
Update 1991/fine/README.md + add mastodon handle

### PR DESCRIPTION
**Pull request by xexyl**
Undo rot13 and fix formatting.

Added mastodon handle. This was done in the author/Thomas_A_Fine.json file too.

### CODE REVIEW

**Comment by xexyl** [comment]
I'll be afk again .. might be able to do a bit more but that's unclear. Otherwise I should be able to do some tomorrow before things get hectic.

**Comment by lcn2** [comment]
👍🙏@xexyl

**Comment by lcn2** [comment]
👍🙏@xexyl

**Comment by xexyl** [comment]
> 👍🙏@xexyl

You're very welcome!

> 👍🙏@xexyl

You're very welcome!

:-)

**Pull request merged**
