### PR TITLE
Add FAQs about the mkiocccentry tools

### PR DESCRIPTION
**Pull request by xexyl**
Several new FAQ entries have been added to discuss some of the details of chkentry, txzchk, fnamchk, jparse and maybe others that are related to the rules and guidelines (and in particular rule 17 and how to package submission tarballs). As there are new FAQ entries on these (which is much of what was in the guidelines) the guidelines have been shortened for these additions.

Looking over the rendered html files it seems okay but I believe that these entries are works in progress and not complete.

For reference the new FAQ version is 28.0.3 2024-07-27 and the new guidelines version is 28.11 2024-07-27.

### CODE REVIEW

**Comment by xexyl** [comment]
I think this is a good step in the direction of improving both the FAQ and the guidelines. I will note however (and will note it in the other issue too) that the rules still do state a lot on the mkiocccentry tool. I'm not really sure how to best integrate this content into the FAQ and I'm not sure if it should be. I think it probably should but that can wait for later.

Of course I made an error again so I'll quickly fix it - then doing other things for the rest of the day (most likely).

**Review by lcn2 — APPROVED** [review]
Thanx @xexyl

**Comment by xexyl** [comment]
... leaving for the day now.

**Comment by xexyl** [comment]
> Thanx @xexyl

You are most welcome. It seems like we replied at the same time so I missed it.

**Pull request merged**
