### PR TITLE
Format fixes in 1993/dgibson/README.md

### PR DESCRIPTION
**Pull request by xexyl**
.. I'll stop now .. wanted 45 as it's a prettier number for me than 44.

### CODE REVIEW

**Comment by lcn2** [comment]
multi/fmt!

**Comment by xexyl** [comment]
> multi/fmt!

```sh
$ fmt -c README.md |head ; head README.md 
               # Best Abuse of the C Preprocessor:
                                 
                           David Gibson
                     University of Cape Town
                       1 Sweet Valley Road
                            Bergvliet
                               7945
                           South Africa
                                 
                           ## To build:
# Best Abuse of the C Preprocessor:

David Gibson  
University of Cape Town  
1 Sweet Valley Road  
Bergvliet  
7945  
South Africa  

## To build:
```

Now it certainly has multi formats!

**Comment by xexyl** [comment]
> multi/fmt!

Another form of mutual/fmt:

```sh
$ head README.md| fmt -c|head|wc -l
      10
$ head README.md| fmt |head|wc -l
       6
```

... funny that!

**Comment by xexyl** [comment]
> multi/fmt!

> multi/fmt!

Another form of multi/fmt:

```sh
$ head README.md| fmt -c|head|wc -l
      10
$ head README.md| fmt |head|wc -l
       6
```

... funny that!

**Pull request merged**
