### PR TITLE
Fix 2004/sds/try.sh for README.md changes

### PR DESCRIPTION
**Pull request by xexyl**
Commit cbc022d864bdc069f0c98fedb4031ab1eb95019b which edited 2004/sds/README.md broke the functionality of one of the features of the code so the previous revision of README.md was copied to README_sds.md and the script now uses that file.

This does mean the manifest is out of date and that will have to be fixed another time but now the script works okay. Without this one of the files to be compiled does not compile at all and it seems better this way than to tamper with the code especially given what the entry does and because it would take more time to fix anyway.

### CODE REVIEW

**Comment by xexyl** [comment]
You're welcome to fix the manifest but if not I'll do it tomorrow or the next day I think. Can't do it today. Off now and won't be back until tomorrow at the earliest.

**Comment by lcn2** [comment]
This fix creates other problems. We will look into the some more.

**Comment by xexyl** [comment]
> This fix creates other problems. We will look into the some more.  

Okay. If it helps: without this some of the program functionality is broken. 

Would making it a text file be better?

Well I will let you figure out what is needed. 

Gone for the day most likely.

**Comment by lcn2** [comment]
> > This fix creates other problems. We will look into the some more.  
> 
> Okay. If it helps: without this some of the program functionality is broken. 
> 
> Would making it a text file be better?
> 
> Well I will let you figure out what is needed. 
> 
> Gone for the day most likely. 

The new file used by the should not end in '.md' if it can help it.  The fix should not require the `README.md` file to add a copyright into the markdown file, if it can help it.

**Comment by xexyl** [comment]
> > > This fix creates other problems. We will look into the some more.
> > 
> > 
> > Okay. If it helps: without this some of the program functionality is broken.
> > Would making it a text file be better?
> > Well I will let you figure out what is needed.
> > Gone for the day most likely.
> 
> The new file used by the fix should not end in '.md' if it can help it. 

I'll make it .txt.

The fix should not require the `README.md` file to have a copyright in markdown form, if it can help it.

It doesn't. Nor did this fix do that. But I'll rename it to .txt. Then if you need to do something else you can. But then I must go for the day.

**Comment by xexyl** [comment]
> > > > This fix creates other problems. We will look into the some more.
> > > 
> > > 
> > > Okay. If it helps: without this some of the program functionality is broken.
> > > Would making it a text file be better?
> > > Well I will let you figure out what is needed.
> > > Gone for the day most likely.
> > 
> > 
> > The new file used by the fix should not end in '.md' if it can help it.
> 
> I'll make it .txt.
> 
> The fix should not require the `README.md` file to have a copyright in markdown form, if it can help it.
> 
> It doesn't. Nor did this fix do that. But I'll rename it to .txt. Then if you need to do something else you can. But then I must go for the day.

Made it .txt. Not sure what you mean by the other part but at least this file now does not end in .md.

Away until at least tomorrow.

**Comment by lcn2** [comment]
We recommend this pull request be withdrawn so that a fix using a file ending in ".txt" be written, and so that the `README.md` not be required to have a copyright in markdown form, if possible.

**Comment by lcn2** [comment]
What about removing the copyright in markdown form that was added to `README.md`?  Will that correction to the pull request allow this fix to work?

**Comment by lcn2** [comment]
> > What about removing the copyright in markdown form that was added to `README.md`? Will that correction to the pull request allow this fix to work?
> 
> 
> 
> Undoing that commit is indeed what the new text file is. Do you want that done instead and not have the new file? I can do that but probably not until later today or tomorrow. In that case you can keep this open and I'll proceed at that point.

The new use of `README_sds.txt` is OK. 

Just restore the previous content of `README.md` if that is possible.

**Comment by xexyl** [comment]
Oh my mistake. I accidentally did touch it but did not realise it. Now I know why the problem and the confusion. Fixed!

**Comment by lcn2** [comment]
Thank you 🙏 @xexyl

**Comment by xexyl** [comment]
> Thank you 🙏 @xexyl

Happy to help.

**Pull request merged**
