### PR TITLE
Update FAQ about make diff rules

### PR DESCRIPTION
**Pull request by xexyl**
I have provided some examples as well and included how to use other diff
programs like colordiff. Checking formatting (including how it looks on
GitHub) and typo checks notwithstanding this entry is in good condition.

### CODE REVIEW

**Comment by lcn2** [comment]
Should we add a diff_prog_alt and/or maybe diff_alt_prog rule set, @xexyl ?

**Comment by xexyl** [comment]
> Should we add a diff_prog_alt and/or maybe diff_alt_prog rule set, @xexyl ?

Please do. I think that's a great idea!

**Comment by lcn2** [comment]
> > Should we add a diff_prog_alt and/or maybe diff_alt_prog rule set, @xexyl ?
> 
> Please do. I think that's a great idea!

Done, see commit 00c9d602661d343ad91b83166998aa1c7bda14a1

The FAQ for these diff rukles needs to be updated as we have 6 types of diffs now, @xexyl 

As you are working on the FAQ, we will leave it up to you to explain the 6 diff rules.

**Comment by lcn2** [comment]
> > Should we add a diff_prog_alt and/or maybe diff_alt_prog rule set, @xexyl ?
> 
> Please do. I think that's a great idea!

Done, see commit 00c9d602661d343ad91b83166998aa1c7bda14a1

The FAQ for these diff rukles needs to be updated as we have 6 types of diffs now, @xexyl 

As you are working on the FAQ, we will leave it up to you to explain the 6 diff rules.

**Comment by xexyl** [comment]
> > > Should we add a diff_prog_alt and/or maybe diff_alt_prog rule set, @xexyl ?
> 
> > 
> 
> > Please do. I think that's a great idea!
> 
> 
> 
> Done, see commit 00c9d602661d343ad91b83166998aa1c7bda14a1
> 
> 
> 
> The FAQ for these diff rukles needs to be updated as we have 6 types of diffs now, @xexyl 
> 
> 
> 
> As you are working on the FAQ, we will leave it up to you to explain the 6 diff rules.

Thanks!

I will do that. 

Maybe add it to the todo list? I am away from the computer right now and I have a zoom call in half an hour. 

Thanks.

**Pull request merged**
