### PR TITLE
Add FAQs about .auth.json and .info.json

### PR DESCRIPTION
**Pull request by xexyl**
These are very detailed as they are very important parts of the mkiocccentry toolkit. The guidelines will likely refer to these for those who want to know more details but that is for another commit.

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Looks like a good draft of these 2 new FAQs, @xexyl

**Comment by lcn2** [comment]
There is a bug in the `faq.md` that `make test` did not catch, but `make faq` did.

We are taking this opportunity to try to modify the pull request before merging, as well as to make a few other minor tweaks.

Stay tuned for how this test goes ...

**Comment by xexyl** [comment]
> There is a bug in the `faq.md` that `make test` did not catch, but `make faq` did.
> 
> We are taking this opportunity to try to modify the pull request before merging, as well as to make a few other minor tweaks.
> 
> Stay tuned for how this test goes ...

Weird because I ran `make faq` ... wonder what it is.

**Review by lcn2 — APPROVED** [review]
approved as modified

The PR is approved as modified (we hope).  Thanks, @xexyl, for the opportunity to test
how to modify a PR before it goes into the master branch.

What we did was:

```sh
gh pr list
gh pr checkout 2568

make faq

vi faq.md

make faq

open faq.html

git add faq.md faq.html
git commit -m'a comment or no comment :-)'
git push

vi faq.md    # to test even more edits on a PR

make faq
make test
make quick_www

git status

open faq.html

git add faq.md faq.html
git commit -m'yet another comment or no comment :-)'
git push

gh pr review
```

At this point we enter "approved as modified" review.

If all goes well we will finish by doing:

```sh
gh pr merge
```

**Comment by lcn2** [comment]
The above process worked well from our perspective.

# QUESTION

How does this look from your repo?     We suspect that if you update you will be in sync.

Here is what we see:

Screenshot 2024-07-14 at 13 37 36

**Comment by xexyl** [comment]
> The above process worked well from our perspective.
> 
> # QUESTION
> How does this look from your repo? We suspect that if you update you will be in sync.
> 
> Here is what we see:
> 
> Screenshot 2024-07-14 at 13 37 36

Seems fine to me .. and perhaps that answers the question you asked the other day?

**Comment by xexyl** [comment]
Also I enjoyed your additions to the `no_comment`! Well played.

**Comment by lcn2** [comment]
Observation:

The heading "Additional fields in ..." might not be the best way to present the fields.  They are not "additional" per-se.

We also suspect that people might be looking at an actual `.info.json` and `.auth.json` files.  It might be better and easier for people to follow if the fields were presented in the "common order" that `mkiocccentry(1)` generates them in.

**Comment by xexyl** [comment]
> Observation:
> 
> The heading "Additional fields in ..." might not be the best way to present the fields. They are not "additional" per-se.

Depends on definition of additional I think. They are there in addition to the array. But if you wish to offer an alternative that's fine.

> 
> We also suspect that people might be looking at an actual `.info.json` and `.auth.json` files. It might be better and easier for people to follow if the fields were presented in the "common order" that `mkiocccentry(1)` generates them in.

Well that's interesting because I thought of that and I did it in part .. just did the arrays first. Certainly it could be moved to be in the precise order that mkiocccentry does though.

**Pull request merged**
