### PR TITLE
Typo (missing ')') in bugs.md, regen bugs.html

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Will do more tomorrow.

**Comment by lcn2** [comment]
Good catch)) @xexyl ((thanks 🤓

**Comment by lcn2** [comment]
> > Good catch)) @xexyl ((thanks 🤓
> 
> ```c
> int main(void)
> {
>     return (((((((('n'+'p'-180))))))));
> }
> ```
> 
> .. and you no doubt know the .. ah .. answer .. to the problem!

0b101010 🤓

**Comment by xexyl** [comment]
> > > Good catch)) @xexyl ((thanks 🤓
> > 
> > 
> > ```c
> > int main(void)
> > {
> >     return (((((((('n'+'p'-180))))))));
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > .. and you no doubt know the .. ah .. answer .. to the problem!
> 
> 0b101010 🤓

Indeed! The answer to so much more too ... and according to some astronomers they really do believe it is the answer to the universe (not sure if they think it's also the answer to life and everything). I am not making that up. They spent years to come to this conclusion! [Yes the answer to the universe really is 42](https://www.independent.co.uk/news/yes-the-answer-to-the-universe-really-is-42-1351201.html).

This is also amusing: https://www.independent.co.uk/life-style/history/42-the-answer-to-life-the-universe-and-everything-2205734.html.

**Pull request merged**
