### PR TITLE
Add missing 'p' in pull_request link in FAQ

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]

**Comment by lcn2** [comment]
hank ou @xexyl 😁

**Comment by xexyl** [comment]
> hank ou xexyl 😁

our're elcome cn2 😁

**Comment by xexyl** [comment]
At first I wondered why the lack of the '@' .. now I know why. It was not adding up to me: I figured it was a typo. But now I know why: it's like the others but not a letter and rather a symbol.

I have a funny story about symbols but that can be another time .. maybe.

**Comment by xexyl** [comment]
The funny story about symbols. 

My mum worked in telecommunications for 45 years. She knew things that nobody else knew and she fixed problems that nobody else could. Even after she retired she was sometimes called for help. That was more than 9 years ago now. She had something amazing she came up with taken (credit), too, by a guy - when she was on maternity leave. After the guy mocked her for it. He got praised in the company newspaper. To this day that angers me so much. If she had complained she would have been belittled and nothing would have happened anyway. It was the early 1980s and if women have a hard time in telecom and IT today it was as you know much much worse in those days. Anyway never mind that.

Years later she had kids come in who were just out of college (she never had any college education) and they thought they knew everything there was to know. She had to help them understand they did not. Some amusing stories with that too but this one is not so much a problem with the job (she trained engineers actually) but simply ignorance of a symbol name. She would tell them they needed to hit the ampersand and they would 'ask what's that?' She would point to it and they would try and correct her by saying 'oh you mean the AND symbol?' 'Yes that's called the ampersand' 'No it's not' etc.

And it's not like it's even new for computers. It's 18th century, that word. She has a lot of funny stories but that's a classic one.

**Pull request merged**
