### PR TITLE
Minor note added to 2018/endoh2/README.md

### PR DESCRIPTION
**Pull request by xexyl**
The try section actually triggers a long (or infinite? .. didn't check) loop so I note this and also say how to break out of it (though most would probably know how).

### CODE REVIEW

**Comment by xexyl** [comment]
... leaving for the day .. will do more tomorrow.

Have a great afternoon!

BTW: when do you leave on holiday ?

**Comment by lcn2** [comment]
> ... leaving for the day .. will do more tomorrow.
> 
> 
> 
> Have a great afternoon!
> 
> 
> 
> BTW: when do you leave on holiday ?

Late next week with decreasing Internet access as time goes on.

**Comment by xexyl** [comment]
> > ... leaving for the day .. will do more tomorrow.
> > Have a great afternoon!
> > BTW: when do you leave on holiday ?
> 
> Late next week with decreasing Internet access as time goes on.

Thanks! I hope you have fun but please stay safe!

No worries on the decreasing Internet access. Don't even worry about replying on the phone. I know it's a huge burden to do so! I can wait on the queries / concerns / issues until you're back home.

**Comment by xexyl** [comment]
BTW: I know you leave late this week but when approximately do you come home? Thanks!

**Comment by lcn2** [comment]
> BTW: I know you leave late this week but when approximately do you come home? Thanks!

After mid May .. perhaps as late as 2023 May 20.

As for now, soon access will be come less frequent and pull requests will sit for days and sometimes limited access will cause replies to be seen more succinct due to even more limited windows of access.

**Comment by xexyl** [comment]
> > BTW: I know you leave late this week but when approximately do you come home? Thanks!
> 
> After mid May .. perhaps as late as 2023 May 20.
> 
> As for now, soon access will be come less frequent and pull requests will sit for days and sometimes limited access will cause replies to be seen more succinct due to even more limited windows of access.

Thanks .. no worries on delays. It's fine by me. And no need to reply at all if it's inconvenient! I understand.

I just hope you stay safe and have a great time!

**Pull request merged**
