### PR TITLE
Removed non-bug of 2006/toledo2 and non-used files

### PR DESCRIPTION
**Pull request by nanochess**
After the latest changes I noticed the 2006/toledo2 bug as re-added so I removed it. The HALT.COM and IMPORT.COM are autogenerated by the included C.BIOS file.

I've also noticed the comment about the link to retroarchive.org and how the binary files shouldn't be included, so I removed all the uncompressed binary files taken from that link.

### CODE REVIEW

**Comment by lcn2** [comment]
Well, @nanochess, from the _Author's remarks_ section of `2006/toledo2/README.md` we read:

```
The extracted files in the various subdirectories originally came from
[http://www.retroarchive.org/cpm/os/KAYPROII.ZIP](http://www.retroarchive.org/cpm/os/KAYPROII.ZIP)
but we do not provide the zip file here.
```

Our experience with such externally linked files is problematic: over the years things go away, change, etc.
We have and to chase down missing files form internal archives, web searches, from the original authors, and
in some cases the internet archives.  We would prefer to **NOT** depend on
[http://www.retroarchive.org/cpm/os/KAYPROII.ZIP](http://www.retroarchive.org/cpm/os/KAYPROII.ZIP) sticking around.

To stand the test of time, we suggest that the `KAYPROII.ZIP` file be included.

An alternative to not including those files would be to just include the `2006/toledo2/KAYPROII.ZIP` file, to unzip file file as part of the `make all` and `make alt` process, and to remove those unzipped files as part of the `make clobber`.

If this is done, then the `2006/toledo2/README.md` file be re-written to something along the lines of:

```
The extracted files in the various subdirectories originally came from
[http://www.retroarchive.org/cpm/os/KAYPROII.ZIP](http://www.retroarchive.org/cpm/os/KAYPROII.ZIP).
For your convenience we have included a copy that ZIP file.
```

Let us consider that alternative approach.  As such we will accept your pull request as is, and then make the above mentioned modifications.

**Comment by lcn2** [comment]
Hello @nanochess,

See commit 545f808335c531ed9f4aa7e5b27e20c043523a7a

These changes were make as per [comment 1886045640](https://github.com/ioccc-src/temp-test-ioccc/pull/1846#issuecomment-1886045640).

Comments and corrections welcome.

**Comment by xexyl** [comment]
The problem I have with removing the status missing files is this zip file does not have the file `IMPORT.COM`. That is why I added it back. Unless I misunderstand something that file IS missing which is why I had it in the bugs.md in the first place.

So which is it?

**Comment by xexyl** [comment]
> Well, @nanochess, from the _Author's remarks_ section of `2006/toledo2/README.md` we read:
> 
> ```
> The extracted files in the various subdirectories originally came from
> [http://www.retroarchive.org/cpm/os/KAYPROII.ZIP](http://www.retroarchive.org/cpm/os/KAYPROII.ZIP)
> but we do not provide the zip file here.
> ```
> 
> Our experience with such externally linked files is problematic: over the years things go away, change, etc. We have and to chase down missing files form internal archives, web searches, from the original authors, and in some cases the internet archives. We would prefer to **NOT** depend on http://www.retroarchive.org/cpm/os/KAYPROII.ZIP sticking around.
> 
> To stand the test of time, we suggest that the `KAYPROII.ZIP` file be included.
> 
> An alternative to not including those files would be to just include the `2006/toledo2/KAYPROII.ZIP` file, to unzip file file as part of the `make all` and `make alt` process, and to remove those unzipped files as part of the `make clobber`.
> 
> If this is done, then the `2006/toledo2/README.md` file be re-written to something along the lines of:
> 
> ```
> The extracted files in the various subdirectories originally came from
> [http://www.retroarchive.org/cpm/os/KAYPROII.ZIP](http://www.retroarchive.org/cpm/os/KAYPROII.ZIP).
> For your convenience we have included a copy that ZIP file.
> ```
> 
> Let us consider that alternative approach. As such we will accept your pull request as is, and then make the above mentioned modifications.
> 
> ## UPDATE 0
> We are making these changes now, please stand by ...

Actually I had removed the zip file yesterday because I extracted everything and had it in the repo like was discussed a while back. Has this changed? But now the user must have `unzip` in order to make this entry work okay whereas before this was not necessary. It's likely they do have it but not every system does so `make` would fail when it otherwise would not.

**Comment by xexyl** [comment]
> Hi @xexyl I had no space inside toledo2.c to create an import file utility to bootstrap CP/M, so instead I used the initial memory image C.BIOS to contain 8080 code to initialize the hard drives A and B, >and< creates automatically the HALT.COM and IMPORT.COM utilities.
> 
> So there's no missing IMPORT.COM or HALT.COM files, both are embedded inside C.BIOS and written in the virtual hard disks when the emulator is first run.

Aha. That explains it. I thought I tried it but it didn't work. Maybe I remember wrong or I was (as often is the case) too tired.

Sorry for the going back and forth and thanks for the explanation! I'll take a look at the README.md file and see if anything might be cleaned up (wrt the situation). Maybe I can add what you just wrote to me.

**Comment by xexyl** [comment]
Okay I see it's even documented already. So all that has to be done is remove the bug status from the README.md file. I am often very tired and I was trying to get through the format/typo check and adding bug statuses so I just missed that detail.

Thanks! I'll fix the bug status in the README.md file and then commit.

**Pull request merged**
