### PR TITLE
Fix technical details with rules (esp 17)

### PR DESCRIPTION
**Pull request by xexyl**
There were numerous things that had to be fixed and there will likely have to be some discussion as well.

Some formatting fixes and additional links were also added.

This commit involves some updates to the FAQ and while I was at it I fixed some references of 'entry'/'entries' to 'submission'/'submissions' (those that should not be 'entry' or 'entries').

### CODE REVIEW

**Comment by xexyl** [comment]
Please take a look when it's on the site .. some things might need to be discussed but there were quite a few fixes: some text duplication removed and many other things.

This took a fair amount of time but I hope that guidelines will be easier (I guess they will be). That has to be another time - maybe today, maybe tomorrow. Will be afk shortly.

**Comment by xexyl** [comment]
It seems like you undid some things to the Makefile.

**Comment by xexyl** [comment]
> It seems like you undid some things to the Makefile.

Oh .. no. It's just you did a bit more to them and they're further down in the file. Okay all good then.

**Comment by lcn2** [comment]
Approved the pull request with modifications

**Comment by xexyl** [comment]
> Approved the pull request with modifications

That caused problems unfortunately. I'm hoping that what I have just done will solve it.

**Pull request merged**
