### PR TITLE
Remove extra thank yous + links in thanks file

### PR DESCRIPTION
**Pull request by xexyl**
As there already are thanks at the top there seems to be no reason to have the extra thanks for each entry. This was due to yank paste from the README.md files which naturally made the change much more efficient.

I also removed the links to both Yusuke and myself in the entries themselves as they're at the top of the file.

I also (because I am very proud) added some other things I did at the top of the honour list.

### CODE REVIEW

**Comment by lcn2** [comment]
[<A HREF="thank.you">@xexyl</A>](<A HREF="thank.you">@xexyl</A>)

**Comment by xexyl** [comment]
> [[@xexyl](thank.you)]([@xexyl](thank.you))


 [[@lcn2](you.are.welcome)]([@lcn2 ](you.are.welcome))!

**Comment by xexyl** [comment]
Incidentally I am aware of several fixes that have to be made to this file but I will do that later on ... still waking up and I want to look at the comments in all the threads. Not sure if this will happen right now though .. might be less productive today. It feels like that but we'll see.

**Comment by xexyl** [comment]
> Incidentally I am aware of several fixes that have to be made to this file but I will do that later on ... still waking up and I want to look at the comments in all the threads. Not sure if this will happen right now though .. might be less productive today. It feels like that but we'll see.

Actually going through this file real quick .. with some changes to some other files related to the fixes. I will look at the other comments later when I'm more clear headed.

**Pull request merged**
