### PR TITLE
Remove useless use of cat in 1987/biggar/README.md

### PR DESCRIPTION
**Pull request by xexyl**
This was in the 'Try' section but as a ailurophile (cat lover) I have to 
say that if one removes a useless use of cat then literally speaking if
there were any cats left then they would be useful. I utterly object,
therefore, that there is no longer a cat here because cats most
certainly are useful. For instance if Earth was flat cats would have
pushed everything off it by now which is proof to those not in the Flat
Earth Society that the Earth is not flat. It's not proof to the Flat
Earthers but that's because they think it's flat regardless when in
reality the only related thing that might be flat is their brain, kind
of like a battery that's gone flat. And that's flat :-) But I digressed; 
the point is that there was no need for the cat command here even if 
there's always a use for cats. :-)

### CODE REVIEW

**Comment by xexyl** [comment]
I'm afraid that this is all I can do today .. at least for now .. but I have another question about the one I'll start next as well as the issue you brought up about diffs. I'll bring them up in issue #3 and then I'll probably not end up doing anything here until tomorrow though tomorrow is rather .. uncertain.

**Comment by lcn2** [comment]
🐈 @xexyl

**Comment by xexyl** [comment]
> 🐈 @xexyl 

Cats are great. I hope you had a chance to read the log but if you didn't I hope you do get a chance.

**Comment by xexyl** [comment]
> > 🐈 @xexyl 
> 
> Cats are great. I hope you had a chance to read the log but if you didn't I hope you do get a chance. 

... although it could be considered kind of mean. But only just. And it is true. If the Earth was truly flat cats would have knocked everything off it by now. 

Even so Flat Earthers are really funny to watch. My brother actually follows them for the hilarity.

**Pull request merged**
