### PR TITLE
Updates and fixes to 2013/dlowe

### PR DESCRIPTION
**Pull request by xexyl**
Added fun.c and make make all compile it: this is what the judges
suggested one try compiling with different compilers and checking the
results. I added how to specify the compiler.

Added slen.sh script, corrected for shellcheck, which runs the command
the author suggested (and which the judges added to their remarks), to
make it simpler for viewers of the entry.

Added INABIAF section to README.md: if no args are specified it will
very likely crash or do something funny. A similar such thing is in
bugs.md as well.

Updated .gitignore.

Format fix README.md.

### CODE REVIEW

**Comment by xexyl** [comment]
Apologies for this duplicate pull request (well it has some of the previous one and then more). I forgot the I had already opened the pull request. I did do `git status` and didn't see anything that indicated it wasn't pushed but I'm tired enough that it did not register. It doesn't seem to show any conflicts and it only shows the commit once due to (I guess) `git commit -va --amend` but hopefully it's fine: it doesn't show any conflicts anyway.

But with that said it's time to rest. I hope to do more later on but it's possible I won't be able to until tomorrow.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by lcn2** [comment]
> Apologies for this duplicate pull request (well it has some of the previous one and then more). I forgot the I had already opened the pull request. I did do git status and didn't see anything that indicated it wasn't pushed but I'm tired enough that it did not register. It doesn't seem to show any conflicts and it only shows the commit once due to (I guess) git commit -va --amend but hopefully it's fine: it doesn't show any conflicts anyway.

Something went wrong with this pull request:

image

As a result until the conflicts are resolved this and all future pull requests are "hung". 

With an iPhone it may be rather difficult to fix: having to wait a god while until a laptop and Internet connection allow. 

Stay tuned ..

**Comment by lcn2** [comment]
With the iPhone interface we seem to have no obvious was to resolve conflicts.

Stay tuned ...

**Comment by lcn2** [comment]
We are going to try an close this pull requests instead.

Stay tuned...

**Comment by lcn2** [comment]
Apparently the other pill requests relayed to 2013 are now impacted.

Stay tuned ..

**Comment by lcn2** [comment]
Looks like we will be forced to close future pull requests related to files that were impacted. 

Stay tuned...

**Comment by xexyl** [comment]
Sigh. 

I don't know even how to go about making sure that the files will be committed again. If I checkout master it will change the files back. 

Maybe better to not try doing it with the phone though it's too late now. 

I will maybe try sorting it out tomorrow but if it happened once why shouldn't it happen again?

So I am not really sure what to do. I just know that I don't have the faculties to deal with much right now. 

Please advise what you want.

**Comment by xexyl** [comment]
Also even if I commit again it's going to take effort to figure out what changed and what to write.

**Comment by lcn2** [comment]
No it is even worse.  We will have to reject the current pull request stack. 

You will need to revert to pull request #1026 and then reissue pull requests. 

Never seen a pull request stack go this bad, but looks like nothing forward of pull request is going to work until you revert and reapply. Not sure what happened in [comment 1752820810](https://github.com/ioccc-src/temp-test-ioccc/pull/1027#issuecomment-1752820810).

But short of our waiting 2+ weeks to use a laptop to try and untangle the mess, the only way forward from whatever happens is a pull request flush. 

Sorry (tm Canada 🇨🇦).

Again, it looks like pull request #1026 is the last valid request and is how the master branch is now.  Perhaps you need to revert to that state and then issue a pull requests to move forward.

**Comment by xexyl** [comment]
Well I don't even know how to go about it. I'll maybe wait until you have come up with a solution as I'm too tired and overwhelmed to figure these things out. I can format fix and such but it's too much right now to sort through messes like this.

Sorry.

**Comment by xexyl** [comment]
I can undo that pull request easy enough by opening a new pull request to undo it but how can I reissue these that are closed? I don't know how. I might know what happened but I don't know how to fix it without a lot of work.

I can't deal with this today anyway. Off to get food.

**Comment by xexyl** [comment]
Oh that pull request is closed too so I can't undo it. I don't know what to do. Nor do I know what happened. Please advise what has to happen and I'll try fixing it but it might be that it ends up with a large commit of different kinds. Anyway I'm leaving for the day.

**Comment by lcn2** [comment]
If you feel like it, stash the current state. Revert to commit f6b5a4919df69e51cbdcbb1a9419e4d2b506c910 and the to a single pull request to forward up to pull request #1040 or whatever your last pull request was. 

You can call the new full-update pull request as to reply from pull request #1027 thru pull request #1040.

**Comment by xexyl** [comment]
> If you feel like it, stash the current state. Revert to commit [f6b5a49](https://github.com/ioccc-src/temp-test-ioccc/commit/f6b5a4919df69e51cbdcbb1a9419e4d2b506c910) and the to a single pull request to forward up to pull request #1040 or whatever your last pull request was.
> 
> You can call the new full-update pull request as to reply from pull request #1027 thru pull request #1040.

There's nothing to stash though since it's all committed. I guess I can tar up the entire directory and extract after checking out master. That's what I'm doing. But I have no idea how to even go about getting all the log entries correct.

I'll do it tomorrow if I can. I have to go get food. Sorry this happened.

**Comment by lcn2** [comment]
> Oh maybe you can stash a repo that has everything committed. Well I'm too tired to even think about it. Tomorrow hopefully.

Just to be clear, it is GitHub that had a problem.  We have nothing to stash. 

Again sorry (tm Canada 🇨🇦) that GitHub failed and ruined the pull request stack and caused you more work. 

Try forming a new single "roll up" pull request to bring the master branch in sync with your current codebase.

You can do not have to try and re-document each change. All of those changes are documents in the closed pull requests.

You can simply document the "roll-up" pull request as "reapply pull requests #1027 thru #1040".

**Comment by xexyl** [comment]
I figured that it was GitHub indeed. 

I am not sure how to go about fixing it all with them reopened because I don't know the conflict. But maybe I will see something at the laptop when I boot it up. 

I had an idea how to redo everything. It would take some effort but I think that it would be better to have the individual pull requests because otherwise the log would be very very long: because I believe that detailed logs are important.

**Comment by xexyl** [comment]
However thanks for reopening them. Maybe it will work out somehow.

**Comment by xexyl** [comment]
Yesterday I crashed before 1600 hours. I could barely keep my eyes open and I had a banging headache (in fact I still have a headache which is quite unusual) and I felt weak. 

I am only still waking up and it's only 20 after 3!

At least I got a lot of sleep. Hopefully today will not end like yesterday and hopefully I can resolve this mess today too though based on how I feel right now I fear that it might be all I get done here. 

We shall see. At least yesterday I got a lot of reading done. It's now The Choices of Master Samwise which of course you know very well is the last chapter of TT (which having read HoMe you also know that that's what Christopher called Two Towers). 

Well we shall see how I do here. I will boot the laptop up soon and then see what I can see.

Since my head is still hurting and I am still very tired I doubt I will be able to do much at least quickly but I do hope to get this bloody mess sorted out. 

I am also sorry about it. You said sorry and I really appreciate it but it's not your fault that GitHub had this annoying problem. Okay: very very very very and I really really really REALLY do mean annoying problem. 

Still I thank you for the suggestions and we will get this worked out one way or another even if it's annoying and kind of stressful (or maybe frustrating is the right word). 

I have a message to send to a dear friend and then I plan on booting up the laptop and then think on how to go about this. 

I have a copy of my fork in the current state of my last commit/pull request so that I can go back and forth to get the log entry for each pull request. Well in some cases it might be more than one log.

**Comment by xexyl** [comment]
Anyway: DON'T WORRY about it. Also I really hope that I didn't sound irritated at you but if I did I am VERY VERY SORRY. It certainly wasn't directed at you: if I sounded irritable it was not at you: I just was very tired and had a banging headache and I put a lot of time and effort (all the more due to the headache and being so tired and also worn out still from being sick for so long plus something else that came up last week that is still affecting me) and I know from experience how this can be difficult to fix. 

THANK YOU! Do not worry about what happened: on my behalf it's nothing to be sorry about even and as you said it is the fault of GitHub though it also happened because I accidentally pushed the same branch more than once after a git commit amendment. Still I don't see how that should be a problem: but I also am not an expert at that and git can indeed be finicky in some ways and it IS complicated!

Anyway no worries and thank you and again I am very sorry if I sounded irritated at you: I most certainly wasn't!

Hope you're having a great time! Stay safe and I hope that I can get this resolved soon even if it is all I manage today which I am afraid is quite likely if I even finish it.

**Comment by xexyl** [comment]
Had to reply to a long time friend who contacted me .. we go back over a quarter of a century. What's great about this being reopened is now that I'm at the laptop I see the conflicts that must be resolved! So I hope that this means I can do it more easily. If I can that would be great: would save time. I probably still won't get much done beyond it (if anything at all) but it would save a lot of effort and time if I can.

Thanks again and again sorry if I sounded irritable: I'm not sure if I did but just in case. It was not directed at you but just frustration at the situation. It's been quite hectic and I've been so exhausted and so on ... but even if not it's always annoying when something like this happens.

I'm glad you reopened the pull requests. Thanks!

**Comment by xexyl** [comment]
Hmm .. trying to do a new pull request here and it says it can't automatically merge :( I have to think of trying another way ... hopefully I can get it sorted.

**Comment by xexyl** [comment]
No more conflicts here now either. I have to check the other pull requests now.

**Comment by lcn2** [comment]
Yea 🎉‼️ Thanks @xexyl

**Comment by xexyl** [comment]
> Yea 🎉‼️ Thanks @xexyl

Yes it's indeed a relief! Once all have been merged I'll do a pull and then I can do more the next time. No rush though .. again thanks for reopening these!

**Pull request merged**
