### PR TITLE
Add original before unseen 1992/nathan/nathan.c

### PR DESCRIPTION
**Pull request by xexyl**
It has been deemed that this should be okay now so we decided to add the code.

This required a minor change in 2020/ferguson2 which I have made here as well in this commit.

### CODE REVIEW

**Comment by lcn2** [comment]
BTW: the convention is to use _make all_ as this rule can trigger multiple dependencies.

Please revert the "How to compile" to use the all rule. 

FYI: only if there is a need for an alternative action or command action would a specific rule be mentioned in `README.md`.

**Comment by lcn2** [comment]
Thanks 🙏 @xexyl

**Comment by xexyl** [comment]
> BTW: the convention is to use _make all_ as this rule can trigger multiple dependencies.
> 
> Please revert the "How to compile" to use the all rule.
> 
> FYI: only if there is a need for an alternative action or command action would a specific rule be mentioned in `README.md`.

True. I Sorry about that. I am not even sure why I changed it in this case. 

I will fix that tomorrow.

**Comment by xexyl** [comment]
> Thanks 🙏 @xexyl

Welcome my friend and good night!

I will hopefully be able to do more tomorrow.

**Pull request merged**
