### PR TITLE
Restore optimiser in 2011/richards

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Okay done with this situation except for one entry I've not reached yet. I have something else today I should do but I will get some entries of 2019 done even if I don't finish it today. I hope I can finish it today but I'm not sure. This task took longer than I anticipated - got distracted by one of the entries for one thing and I found room for improvement in some others as well. Plus other things to do.

**Comment by lcn2** [comment]
Glad things are again Oh Kay 🤓, thanks for the -O updates

**Comment by xexyl** [comment]
> Glad things are again Oh Kay 🤓, thanks for the -O updates

You're very welcome. And it seems like the extra step you had to take turned out fine. Looks good to me. I'm also (I think) done with the other thing I had to do so I hope I can look at 2019 soon. Of course having problems with seeing right now but I'm sure I'll get some entries done today before I have to head off. If I don't though I now have the two important and recent things that were pending done now so I can work on 2019 without having those in the back of my mind.

**Comment by xexyl** [comment]
> Glad things are again Oh Kay 🤓, thanks for the -O updates

Well there is one more entry but as I have not yet had a final look at it that's okay. So we might say it's just Oh Jay instead, one short of Oh Kay.

**Pull request merged**
