### PR TITLE
Simplify how to redefine macros in 2014/birken

### PR DESCRIPTION
**Pull request by xexyl**
Now one can do

    make clobber PORT=31337 TIME=50000 alt

or whatever.

### CODE REVIEW

**Comment by lcn2** [comment]
Now we can clobber time ‼️😎 @xexyl

**Comment by xexyl** [comment]
> Now we can clobber time ‼️😎 @xexyl

Somehow that reminds me of how people think time is an illusion when it's actually just a way to keep track of when something happened, when one should be somewhere/do something and so on.

And then that makes me think of the absurd [simulation hypothesis](https://en.wikipedia.org/wiki/Simulation_hypothesis). The idea that we're a computer simulation! What happened when computers didn't exist then? Were we a simulation of a moron's brain? Or maybe we were only a simulation once computers came into existence? But then what happened to the people who were alive before and during? Are they part simulation part reality? And if we're all a simulation why even bother with what we're doing? Why not give up? There are so many questions we can ask with such ridiculous ideas that it should answer it right away that it's bogus.

**Comment by xexyl** [comment]
> > Now we can clobber time ‼️😎 @xexyl
> 
> Somehow that reminds me of how people think time is an illusion when it's actually just a way to keep track of when something happened, when one should be somewhere/do something and so on.
> 
> And then that makes me think of the absurd [simulation hypothesis](https://en.wikipedia.org/wiki/Simulation_hypothesis). The idea that we're a computer simulation! What happened when computers didn't exist then? Were we a simulation of a moron's brain? Or maybe we were only a simulation once computers came into existence? But then what happened to the people who were alive before and during? Are they part simulation part reality? And if we're all a simulation why even bother with what we're doing? Why not give up? There are so many questions we can ask with such ridiculous ideas that it should answer it right away that it's bogus.

... and looking at that link apparently a lot of people believe in it. Elon Musk included. Well that's not surprising but then you see apparently that Neil deGrasse Tyson believes in it too. But it has so many continuity problems and ultimately if we're a simulation why bother? Why would we choose to play a puppeteer's game if all it takes is for them to shut the computer down? And what about power outages? How do they explain that? That's a good argument against it and not one I have seen (though I've not looked at it much for obvious reasons). No matter how much battery backup one has eventually the power will run out and there have been places where this time has been exceeded in the history of life.

**Comment by xexyl** [comment]
Anyway I'll be back tomorrow. Have a great rest of your day.

**Comment by xexyl** [comment]
Apparently [Elon Musk thinks we are cyborgs and we have superpowers too](https://m.youtube.com/watch?v=ZrGPuUQsDjo). 

Why does this remind me of Terminator 2 when Sarah Connor wants to smash the CPU and even gets upset at John when he stops her? It's not that I think anyone should be harmed but the amount of damage he does is kind of like a Terminator except through ineptitude and a cavalier attitude rather than being programmed to terminate. 

Oh well. Maybe it will amuse you or bemuse you, the video. I am off to get sleep. I will do more tomorrow, starting I think with endoh2. Hope you have a great night.

**Pull request merged**
