### PR TITLE
Minor fixes in README.md

### PR DESCRIPTION
**Pull request by xexyl**
Change './sgit' to just 'sgit'.

Remove space at end of lines.

### CODE REVIEW

**Comment by xexyl** [comment]
Ach! Closing this .. I forgot to specify sgit README.

Will reopen shortly.

**Comment by xexyl** [comment]
Pull request fixed in https://github.com/ioccc-src/temp-test-ioccc/pull/965/commits/e0c82f79a69495fbc3883129dc40af8a6b9a01ac.

Off to do other things for the rest of the day.

**Comment by lcn2** [comment]
Merged @xexyl

**Comment by xexyl** [comment]
> Merged @xexyl

Oh no! Whatever shall I do being merged into the repository? :-)

**Comment by xexyl** [comment]
> > Merged @xexyl
> 
> Oh no! Whatever shall I do being merged into the repository? :-)

... thanks.

**Pull request closed without merging**
