### PR TITLE
Fix links through 2012 in thanks file

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I am done for the day but I noticed something with the last entry ... I'll bring it up in another thread and then leaving for the day. But getting close to being done with this file!

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl 

You are most welcome. 

I am hoping to start more work here in a bit perhaps first with that manifest issue I brought up and then going back to the html files. But I have some other things I need to do first. 

Hope you had a great sleep.

**Comment by lcn2** [comment]
> > Thank you @xexyl
> 
> You are most welcome.
> 
> I am hoping to start more work here in a bit perhaps first with that manifest issue I brought up and then going back to the html files. But I have some other things I need to do first.
> 
> Hope you had a great sleep.

Yes, thank you .. and likewise.

**Comment by xexyl** [comment]
> > > Thank you @xexyl
> 
> > 
> 
> > You are most welcome.
> 
> > 
> 
> > I am hoping to start more work here in a bit perhaps first with that manifest issue I brought up and then going back to the html files. But I have some other things I need to do first.
> 
> > 
> 
> > Hope you had a great sleep.
> 
> 
> 
> Yes, thank you .. and likewise.

Strangely better than it has been but it remains to be seen if that will continue. Hoping for the best but I don't expect it. 

Thanks!

**Pull request merged**
