### PR TITLE
Add 2019/diels-grabsch2/try.sh script

### PR DESCRIPTION
**Pull request by xexyl**
The try.sh script looks for sha512sum and shasum. If either of these are
found it will use the one found (in the order of sha512sum first and 
shasum -a 512 second) and prog. If neither can be found it uses just 
prog. If one of them can be found, however, it shows how the output is 
the same.

The prog.c was restored from prog.orig.c. Like 2019/diels-grabsch1 the 
purpose is no longer valid and even more problematic is the fact that 
the checksum value obviously would not be correct otherwise. Makefile 
updated instead.

The README.md file has been format/typo checked.

.gitignore updated - added files that try.sh script uses (though it does
delete them after use).

### CODE REVIEW

**Comment by xexyl** [comment]
That's five entries of 2019 done today (probably all I'll be doing .. very tired and about to go get food). Need to do 9 more. Then 2020 has 15 but we know that two of them can be mostly glossed over since they're mine (maybe go over them quickly) so let's make it 13. So 13 + 9 is just 22 left! After that I can work on the YYYY/README.md files and the todo file. But we're getting to the point, I think, where the issues can be closed and we can then work on the much more exciting json! :-) (or is that :-( ? :-) .. well it's good because closer to next contest but you know :-) :-) ).

Well anyway I'll do some tomorrow but like I said elsewhere I do have an eye doctor appointment and I have other things going on after that so I'll have less time than I might have otherwise but should still be able to get a few done at least.

**Comment by lcn2** [comment]
Thank you for the 2019 progress @xexyl

**Comment by xexyl** [comment]
> Thank you for the 2019 progress @xexyl

You are most welcome. Been awake since way too early today .. hoping to rest sometime soon and maybe even sleep but I doubt it. That's not good for what's planned today but I am feeling a bit sleepy so maybe I'll luck out. Hope you're sleeping well.

**Comment by lcn2** [comment]
> > Thank you for the 2019 progress @xexyl
> 
> 
> 
> You are most welcome. Been awake since way too early today .. hoping to rest sometime soon and maybe even sleep but I doubt it. That's not good for what's planned today but I am feeling a bit sleepy so maybe I'll luck out. Hope you're sleeping well.

We have a big home remodeling project that has been in the planning stages for a few years that is about to obtain an answer to the question "can we really afford it?" when the selected builder presents a cost and time estimate for the overall project.

Meanwhile we are switching to primarily living off of retirement funds starting in 2024.

All this is a bit "exciting".  Such "excitement" makes it harder to sleep.

**Pull request merged**
