### PR TITLE
Revisit 1990 entries

### PR DESCRIPTION
**Pull request by xexyl**
Although I previously got them to all compile they did not all work. Now
    they do except that jaw does not work properly in macOS (I have noticed
    something odd in linux too but it appears to work mostly if not
    entirely).
    
    Yusuke Endoh pointed out for 1990/theorem that atof() nowadays needs
    include stdlib.h so this was added to the file. As well I added the
    inclusion of string.h for strcmp(). I also fixed some segfaults in this
    entry (even though the judges pointed out that for NULL pointer one
    needs the four '0 0 0 0' it still segfaulted under those conditions) so
    that everything should work now under both linux and macOS. There were
    iirc two parts to this: one the NULL pointer is no longer dereferenced
    but also the type being passed to strcmp() was a int * and not a char *.
    This prevented 1990/theorem/sorter from working at all (segfault) and as
    I recall it there was another segfault I encountered as well.
    
    For 1990/jaw Yusuke Endoh provided a ruby implementation of btoa as it's
    not always available in modern systems. Thank you Yusuke!
    
    In 1990/jaw shark.sh had to be modified as well. This had to do with '.'
    not being in the default PATH.
    
    As well I had previously made a mistake about btoa versus atob as both
    were referenced in 1990/jaw/README.md. I believe I have this correct
    now.
    
    Many if not all the README files were modified with various changes
    including formatting (like turning them into markdown) and section
    titles amongst other things.
    
    I seem to recall I'm missing something here but I can't recall what I
    recall :-) so this will have to suffice this time round (maybe it was
    the btoa/atob issue that I just remembered and added above but I'm not
    sure).

### CODE REVIEW

**Comment by xexyl** [comment]
Somehow I'm proud of fixing `1990/theorem` though I don't know why. Anyway it now works properly without segfaulting. The `sorter` didn't work at all: segfaulted. I think I encountered another segfault too.

Note that `1990/jaw` does not work completely under macOS. Yusuke provided an implementation of `btoa` as it's not in every modern system. I believe I corrected the incorrectly changed references to `btoa`/`atob` (including one by you) but it might want to be looked over again.

This is all I'll do today.

**Comment by xexyl** [comment]
> Note that `1990/jaw` does not work completely under macOS. Yusuke provided an implementation of `btoa` as it's not in every modern system. I believe I corrected the incorrectly changed references to `btoa`/`atob` (including one by you) but it might want to be looked over again.
> 

BTW: ever notice that looking over something is the opposite of overlook? Or put another way if you overlook something you completely miss it but if you look over you won't? Why is it this ? :-) I just noticed this when typing the above comment .. it just popped into my head and it struck me as funny.

**Comment by lcn2** [comment]
These `README.md` files will likely need to be revisited in light of the ideas found in the 2020 set of `README.md` files.

**Comment by xexyl** [comment]
> These `README.md` files will likely need to be revisited in light of the ideas found in the 2020 set of `README.md` files.

True although some at least are following those ideas - though of course it might be that some of those ideas are actually changed in which case we'll have to revisit them for that/those reason/s as well.

**Comment by xexyl** [comment]
And since it was late: just making sure you saw the comment https://github.com/ioccc-src/temp-test-ioccc/pull/47#issuecomment-1464971491 as I think you might find it amusing.

**Comment by lcn2** [comment]
> > Note that `1990/jaw` does not work completely under macOS. Yusuke provided an implementation of `btoa` as it's not in every modern system. I believe I corrected the incorrectly changed references to `btoa`/`atob` (including one by you) but it might want to be looked over again.
> 
> BTW: ever notice that looking over something is the opposite of overlook? Or put another way if you overlook something you completely miss it but if you look over you won't? Why is it this ? :-) I just noticed this when typing the above comment .. it just popped into my head and it struck me as funny. But then there's the question of what literally looking over something is: why is that not overlook? Well the truth is it actually is in one sense of the word overlook! But then this brings up the question of how can it then be the opposite of look over in another meaning?

We are not sure.

**Comment by xexyl** [comment]
> > > Note that `1990/jaw` does not work completely under macOS. Yusuke provided an implementation of `btoa` as it's not in every modern system. I believe I corrected the incorrectly changed references to `btoa`/`atob` (including one by you) but it might want to be looked over again.
> > 
> > 
> > BTW: ever notice that looking over something is the opposite of overlook? Or put another way if you overlook something you completely miss it but if you look over you won't? Why is it this ? :-) I just noticed this when typing the above comment .. it just popped into my head and it struck me as funny. But then there's the question of what literally looking over something is: why is that not overlook? Well the truth is it actually is in one sense of the word overlook! But then this brings up the question of how can it then be the opposite of look over in another meaning?
> 
> We are not sure.

Well I don't know if I did either but it is funny I think. It's not the only instance of things like this I have thought of over the years. As I was writing the comment it just popped into my head. Here's a funny one that I noticed (to show kind of how my mind works ... caveat emptor as they say :-) .. not that you're buying it as such :-) ). I was trying to get a strand of hair off my hand right after a shower and I thought how difficult that can be so it became one of my many quotes:

> Hands: magnets for loose strange of hair.

:-)

**Pull request merged**
