### PR TITLE
Add missing alt subsections to 2013/cable3

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
With the exception of the one in the other thread I brought up (which I have some additions for) I'm all caught up with this problem. Just waiting on your reply. However I'm done for the day. Will resume tomorrow. Enjoy the rest of your day!

**Comment by lcn2** [comment]
> With the exception of the one in the other thread I brought up (which I have some additions for) I'm all caught up with this problem. Just waiting on your reply. However I'm done for the day. Will resume tomorrow. Enjoy the rest of your day!

We presume that the other issue has been addressed.

**Comment by lcn2** [comment]
Thanks for these alternate pull requests @xexyl

**Comment by xexyl** [comment]
> > With the exception of the one in the other thread I brought up (which I have some additions for) I'm all caught up with this problem. Just waiting on your reply. However I'm done for the day. Will resume tomorrow. Enjoy the rest of your day!
> 
> We presume that the other issue has been addressed.

My guess is that it is indeed.

**Comment by xexyl** [comment]
> Thanks for these alternate pull requests @xexyl

Here are my alternative 'you're welcome's!

**Pull request merged**
