### PR TITLE
Format fix in 1990/pjr

### PR DESCRIPTION
**Pull request by xexyl**
A code block was erroneously stated to be C due to the -> operator being there but actually it's not any operator but rather a transition from one to the next.

### CODE REVIEW

**Comment by xexyl** [comment]
Off for the day .. will resume with 1996 tomorrow.

**Comment by lcn2** [comment]
👁️ 🌊 @xexyl

**Comment by xexyl** [comment]
> 👁️ 🌊 @xexyl

An eyeball and something else.... what though? Well anyway: ➛ 👁️

**Comment by xexyl** [comment]
> > 👁️ 🌊 @xexyl
> 
> An eyeball and something else.... what though? Well anyway: ➛ 👁️

I am reminded of a story where a person had to go to emergency because they were wondering what they would look like with a bow and arrow aimed at their face (or maybe eye?) and so they did it in the mirror and accidentally shot themselves and hit their eye! You might call it a <strike>bull</strike>humanseye.

**Pull request merged**
