### PR TITLE
Typo and format fixes in bin/README.md

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Not sure about some things here though .. what should:


```

The browser context relationship between the HTML content holds the
HTML tag does not extend into the content that the tag includes.
For example, menu bars will not operate as specified by the
[ioccc.css](../ioccc.css).
```
say? In particular the first sentence doesn't seem to flow very well unless I'm missing something.

The other thing adds up to me now that I look at it again so it's just that one though I think that might be repeated. I'd have to check.

**Comment by xexyl** [comment]
The `author_handle` regexp was updated to match what is in the other repo that we discussed not too long ago. The rest was just some flow and format fixes (and some typos fixed too).

**Comment by lcn2** [comment]
> The browser context

Try:

```
HTML tags do not extend into the content that they include.
For example, menu bars [ioccc CSS](../ioccc.css) will not operate
under an HTML tag.
```

**Comment by lcn2** [comment]
thanks @xexyl

**Comment by xexyl** [comment]
> > The browser context
> 
> Try, @xexyl :
> 
> ```
> HTML tags do not extend into the content that they include.
> For example, menu bars [ioccc CSS](../ioccc.css) will not operate
> under an HTML tag.
> ```

I believe the term is element. I also changed `ioccc CSS` to `ioccc.css` so I'll do:

```
HTML elements do not extend into the content that they include.
For example, menu bars [ioccc.css](../ioccc.css) will not operate
under an HTML element.
```

Though on a side note of interest to you, maybe: I'd like to actually change it to 'a HTML' but that's due to the [different pronunciation of H and both are valid](https://www.bbc.co.uk/news/magazine-11642588) so I won't.

**Pull request merged**
