### PR TITLE
Update years.html from make www

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
If there is a problem with `bin/gen-years.sh`, then that needs to be fixed.  While the same is cosmetic, it suggest that the `make gen_years` does not produce a stable change.  This will be addressed in the porting of the actions of `make gen_years` to Linux.

**Comment by xexyl** [comment]
> If there is a problem with `bin/gen-years.sh`, then that needs to be fixed. While the same is cosmetic, it suggest that the `make gen_years` does not produce a stable change. This will be addressed in the porting of the actions of `make gen_years` to Linux.

Fair enough - though I did look at the output and it seemed fine. But this is indeed why I almost did not do it.

It seems that it might be better for me to hold off on commits until these issues are fixed. That's fine by me as it's been pretty hectic and I have been very tired.

So I'll hold off and just try and reply to comments and then when you've fixed these problems I'll then go for the commits.

**Comment by lcn2** [comment]
We are working on the port of bin tools to Linux.

Our initial port to macOS was an effort to generate all of the HTML files that need to be generated in order to not hold up other things.  We did the offline and did not have access to Linux systems, decided instead to focus on getting the web pages in order.

We were about to go on another edit session when we noticed that there was pull requests that touched in bin related things, and so we chose instead to process this instead.

commit [2b92c89](https://github.com/ioccc-src/temp-test-ioccc/commit/2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613) was a missive commit that, while not yet ported to Linux, did a lot of things and established new requirements for generated HTML.

We are almost out of time now.  We need to push out a bin tool change, then we need eat, read the local newspaper downtown and then to return to porting bin tools to Linux.

**Comment by lcn2** [comment]
Unlike the code in the _mkiocccentry_ repo, the primary users of the bin tools are for those IOCCC judges who will maintain the official IOCCC web site.  We put them into the same repo as the winners for our convenience, and to satisfy the curiosity of others, to help whomever we hire to improve the style of the web site, and to show off the wizardry tools such a `bin/md2html.sh` (which we think even folks such as David Korn might be impressed with) and to have fun!  :-)

**Comment by xexyl** [comment]
> We are working on the port of bin tools to Linux.
> 
Thanks. I ran into a new problem though ... will make a new comment though not sure if this thread or not.

> Our initial port to macOS was an effort to generate all of the HTML files that need to be generated in order to not hold up other things. We did the offline and did not have access to Linux systems, decided instead to focus on getting the web pages in order.

That makes sense.
> 
> We were about to go on another edit session when we noticed that there was pull requests that touched in bin related things, and so we chose instead to process this instead.
> 
Sorry about that!

> commit [2b92c89](https://github.com/ioccc-src/temp-test-ioccc/commit/2b92c89be8c4c8014d7c5bf497c3d2a7f0e2b613) was a missive commit that, while not yet ported to Linux, did a lot of things and established new requirements for generated HTML.
> 
I think it happens to everyone. Or at least those who push out changes. And those who don't have other things that they had to rush and [it] ends up being incomplete or not enough or ...

> We are almost out of time now. We need to push out a bin tool change, then we need eat, read the local newspaper downtown and then to return to porting bin tools to Linux.

Hope you had a good time!

**Pull request closed without merging**
