### PR TITLE
Fix author json file for 1991/brnstnd

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
.. well fix means adding the country code and name ...

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

You're very welcome .. I hope to do more soon but I'm feeling kind of off. I just got back so it might be that I just need a few minutes. Hopefully there will be more pull requests soon. Hope you have a great day!

**Comment by xexyl** [comment]
> > Thank you @xexyl
> 
> 
> 
> You're very welcome .. I hope to do more soon but I'm feeling kind of off. I just got back so it might be that I just need a few minutes. Hopefully there will be more pull requests soon. Hope you have a great day!

So much for 'feeling off' yesterday! Got so much more done and some really great fixes too!

I am hoping that I can rest again soon and after that I will start doing work on the repo. 

I do already have some commits ready but I have to run something by you too .. even so I hope to finish 1990 today and it would be nice if I could do 1991 too. 

Something occurred to me that I should do after I am done with testing in macOS: test in linux but not just with gcc but also clang: as you know I have found problems when doing this with some entries already so it is possible that there are more. I know clang in linux has an additional defect with args of main() and at least one entry is extremely unlikely to be fixed. But I haven't tried to truly understand it either. 

Anyway I am going to try resting now and when I am back I will start working on the repo!

Hope you are sleeping well!

**Pull request merged**
