### PR TITLE
Rules/Guidelines: link all references to 'judges'

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
The real question is should the references to JUST 'judges' be changed to 'IOCCC judges' (or 'IOCCC Judges') to match the other ones?

Anyway they should all be linked to `../judges.html` now.

**Review by lcn2 — APPROVED** [review]
We judge 👨‍⚖️ this pull request to be useful, @xexyl 😁

**Comment by lcn2** [comment]
> The real question is should the references to JUST 'judges' be changed to 'IOCCC judges' (or 'IOCCC Judges') to match the other ones?
> 
> 
> 
> Anyway they should all be linked to `../judges.html` now.

Good question.  We do not know.  What do you think, @xexyl ?

**Comment by xexyl** [comment]
> > The real question is should the references to JUST 'judges' be changed to 'IOCCC judges' (or 'IOCCC Judges') to match the other ones?
> > Anyway they should all be linked to `../judges.html` now.
> 
> Good question. We do not know. What do you think, @xexyl ?

I have no idea either. Maybe remove the `IOCCC` part as it's longer and anyone reading the guidelines/rules to the contest will know what judges are being referred to? That seems reasonable to me.

**Comment by xexyl** [comment]
As I have to make another change to these files for the pull request change in the other repo I will hold off on this too. Maybe you will get back to me on this at the same time.

**Pull request merged**
