### PR TITLE
Rename 2019/burton/on.one.liners

### PR DESCRIPTION
**Pull request by xexyl**
Added .txt to help with browsers/GitHub etc. in how to manage it. Also
link to it in the README.md file.

### CODE REVIEW

**Comment by xexyl** [comment]
Rediscovered the file and thought I should take care of it. Off to do other things for the day. Will look back tomorrow to figure out what to do - probably start working on the top level README.md files. But that might require some discussion again. Or I might look at the todo list or todo file and start tackling those things. We shall see I guess!

**Comment by xexyl** [comment]
Actually as far as the todo file some of the things can be removed now but I'll worry about that another time - maybe tomorrow.

**Comment by lcn2** [comment]
> Actually as far as the todo file some of the things can be removed now but I'll worry about that another time - maybe tomorrow. 

No worries 😉 you can update the TODOs later.

**Comment by xexyl** [comment]
> > Actually as far as the todo file some of the things can be removed now but I'll worry about that another time - maybe tomorrow.
> 
> No worries 😉 you can update the TODOs later.

As always I appreciate the understanding: even though I know you would.

**Pull request merged**
