### PR TITLE
Some fixes in next/register.html

### PR DESCRIPTION
**Pull request by xexyl**
I have not looked at everything but some fixes have been made.

### CODE REVIEW

**Comment by xexyl** [comment]
Leaving now ... happy Christmas!

**Review by lcn2 — APPROVED** [review]
Thanks, @xexyl 

We will probably modify the "**IMPORTANT NOTE FOR APPLE DEVICES**" to become more generic so that it may both better "stand the test of time" (as the expression goes) and be more generic to be better "future proof" (as the expression also goes)

**Comment by xexyl** [comment]
> Thanks, @xexyl
> 
> We will probably modify the "**IMPORTANT NOTE FOR APPLE DEVICES**" to become more generic so that it may both better "stand the test of time" (as the expression goes) and be more generic to be better "future proof" (as the expression also goes)

As you see fit .. and hopefully it'll be not for ever that they do it. It's pretty amusing that their own emails have triggered it before (have a screenshot of this).

I'll do more tomorrow.

**Comment by lcn2** [comment]
> > Thanks, @xexyl
> > We will probably modify the "**IMPORTANT NOTE FOR APPLE DEVICES**" to become more generic so that it may both better "stand the test of time" (as the expression goes) and be more generic to be better "future proof" (as the expression also goes)
> 
> As you see fit .. and hopefully it'll be not for ever that they do it. It's pretty amusing that their own emails have triggered it before (have a screenshot of this).
> 
> I'll do more tomorrow.

See commit 12f3e46413c365b9615c1fa3382978a8cee8c59d

**Pull request merged**
