### PR TITLE
Fixes in html files and manifest from 2000

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
Oops, we approved the PR instead of asking for a modification.  

The changes of the form:

image

where the `OK_to_edit` JSON member value was changed to `false` are not correct. 

As noted in the FAQ:

image

A false value only applies to files that cannot be edited.

We will issue a correction to the 2 `.entry.json` files that were so edited, look for similar mistakes and update the FAQ with additional information.

**Comment by xexyl** [comment]
> Oops, we approved the PR instead of asking for a modification.
> 
> The changes of the form:
> 
> image
> 
> where the `OK_to_edit` JSON member value was changed to `false` are not correct.
> 
> As noted in the FAQ:
> 
> image
> 
> A false value only applies to files that cannot be edited.
> 
> We will issue a correction to the 2 `.entry.json` files that were so edited, look for similar mistakes and update the FAQ with additional information.

Images should surely not be modified? That's why I changed it to false. Do you really want it to be true?

**Comment by lcn2** [comment]
> Images should surely not be modified? That's why I changed it to false. Do you really want it to be true?

It is perfectly fine for someone to update an image, say by replacing it with another image.

**Comment by xexyl** [comment]
> > Images should surely not be modified? That's why I changed it to false. Do you really want it to be true?
> 
> It is perfectly fine for someone to update an image, say by replacing it with another image.

I suppose that's true in most cases. But is it here? Nobody should update that lava bus picture, surely? For one example. Same (maybe more so?) with Lenna. Unsure about the other one.

I can see it on some cases. I have even updated a picture in 2020/ferguson1. But these seem more static. Still it's true I didn't think of this in a more general way. Thanks for fixing it - whichever way you see it.

**Comment by lcn2** [comment]
> > > Images should surely not be modified? That's why I changed it to false. Do you really want it to be true?
> 
> > 
> 
> > It is perfectly fine for someone to update an image, say by replacing it with another image.
> 
> 
> 
> I suppose that's true in most cases. But is it here? Nobody should update that lava bus picture, surely? For one example. Same (maybe more so?) with Lenna. Unsure about the other one.
> 
> 
> 
> I can see it on some cases. I have even updated a picture in 2020/ferguson1. But these seem more static. Still it's true I didn't think of this in a more general way. Thanks for fixing it - whichever way you see it.

If someone had a better cropped image, better image format, or better image brightness, or better noise reduction, or better color saturation, or ... they are welcome to propose a replacement file. 

A `false` value of `OK_to_edit` is needed to special cases such as the `prog.orig.c` special case and for files that are generated such as HTML files that are generated by tools from
markdown and JSON content. 

The former because it is a historical file that needs to remain as is.  The latter because modifications would be overridden by a later tool run.

**Comment by xexyl** [comment]
> > > > Images should surely not be modified? That's why I changed it to false. Do you really want it to be true?
> > 
> > 
> > > 
> > 
> > 
> > > It is perfectly fine for someone to update an image, say by replacing it with another image.
> > 
> > 
> > I suppose that's true in most cases. But is it here? Nobody should update that lava bus picture, surely? For one example. Same (maybe more so?) with Lenna. Unsure about the other one.
> > I can see it on some cases. I have even updated a picture in 2020/ferguson1. But these seem more static. Still it's true I didn't think of this in a more general way. Thanks for fixing it - whichever way you see it.
> 
> If someone had a better cropped image, better image format, or better image brightness, or better noise reduction, or better color saturation, or ... they are welcome to propose a replacement file.
> 
> A `false` value of `OK_to_edit` is needed to special cases such as the `prog.orig.c` special case and for files that are generated such as HTML files that are generated by tools from markdown and JSON content.
> 
> The former because it is a historical file that needs to remain as is. The latter because modifications would be overridden by a later tool run.

Those are certainly valid points that I did not think about. In my mind it was because they are important parts of the entry. I seemed to recall that the entry actually acted on those files so it would be not good to have them modified.

On the other hand I think another entry had data files that needed to be marked 'false'. But I don't remember. It's been long days and I made a lot of changes the last few days (though not commits).

Have to go now .. back tomorrow.

**Comment by lcn2** [comment]
With commit 460cc40ffc1684473ca0151c194c20088eb52842 the problems with `OK_to_edit` have been corrected.

With commit e83cd61baf7297dfe2a4bacb983a2653e0013709, the FAQ has been updated to explain why `OK_to_edit` might be set to `false`.

**Pull request merged**
