### PR TITLE
Improve bin/status2html.sh, update news + status

### PR DESCRIPTION
**Pull request by xexyl**
For the improvements to the script, besides a typo, a link to the FAQ (for submitting entries) has been added and a link to the GitHub issues page (the new issue page) has been added in the case where an unknown status appears in the status.json file.

The news update is that more progress has been made in that one of the longer files to check for invalid links is done (thanks file) and that two long files are left but that instead of looking at those two first the other html files will be looked at first as it's quite possible that both will have to be updated in some way or another as the other files are being edited. Indeed this has happened numerous times already. This way will save time and prevent having to look at those files a second time. It also notes that some of the top level html files have also been reviewed (see below) and a link was fixed (added a <div id="news"> for a link that was linked to). I am fairly certain that I also fixed some formatting problems and some links were fixed as well.

The status.md/status.html file has been updated with some links added, more div blocks (for each section describing the status.json file), which are used, slight formatting updates and possibly some other things as well. As for some of the links we might say that it's 'statuses all the way down' :-)

With this commit I am happy to report that some other top level files have also been verified for invalid links:

	judges.html
	news.html
	status.html

As the news.html file will be updated it is entirely possible that some fixes will have to be made but the links up to and including 08 June 2024 (unless more changes are made today of course) need not be checked again.

More top level html files (which include those in next/ and other subdirectories that are not of the entries) also have to be checked but these should also go relatively quickly.

Regenerated status.json file as the news has been updated.

### CODE REVIEW

**Comment by xexyl** [comment]
I am **NOT** sure if I will make link checks in more top level html files today so the problem I mentioned in the other thread might want to wait to be fixed just in case. 

I must leave for a while, likely at least an hour or two, and it's quite possible that I will not do more today but at least a number of files have now been checked and improved! I will report whether I am done today or not when that becomes more clear.

I know I have a comment I have not replied to too and I think that's what I'll do next but very shortly I will have to be away for some time. If I don't get more done today I expect I will tomorrow.

**Comment by xexyl** [comment]
> I am **NOT** sure if I will make link checks in more top level html files today so the problem I mentioned in the other thread might want to wait to be fixed just in case.
> 
> I must leave for a while, likely at least an hour or two, and it's quite possible that I will not do more today but at least a number of files have now been checked and improved! I will report whether I am done today or not when that becomes more clear.
> 
> I know I have a comment I have not replied to too and I think that's what I'll do next but very shortly I will have to be away for some time. If I don't get more done today I expect I will tomorrow.

I am done for the day as I noted elsewhere so the problem I brought up can be looked at when you get a chance if you want. I guess it's probably better that you do it anyway so I can focus on the other things - but for me not until tomorrow.

**Comment by lcn2** [comment]
Please keep in mind that `news.md` is **NOT** a `CHANGES.md` file like we have for the `mkiocccentry` repo. 

This is intended to be a high level description whose target audience is a user of the web site, not a developer. 

We will probably edit `news.md` to thin out some of the details before the **Great Fork Merge**.

BTW: We are still pondering how to manage old news: to delete it off the bottom or archive it elsewhere. That's TBD which is why we have not yet gone into a thinning operation on the `news.md` file.

**Comment by lcn2** [comment]
Nice progress @xexyl, thank you 🙏

**Comment by xexyl** [comment]
> Please keep in mind that `news.md` is **NOT** a `CHANGES.md` file like we have for the `mkiocccentry` repo. 
> 
> This is intended to be a high level description whose target audience is a user of the web site, not a developer. 
> 
> We will probably edit `news.md` to thin out some of the details before the **Great Fork Merge**.
> 
> BTW: We are still pondering how to manage old news: to delete it off the bottom or archive it elsewhere. That's TBD which is why we have not yet gone into a thinning operation on the `news.md` file.
> 
> ## UPDATE 0
> 
> Added `news.md` related TODO items to the **Great Form Merge** issue. 

Oh I know that it's not like a changelog but this in particular felt like it should be noted especially the part where the order of the files are going to be looked at. I only did it even so because I was fixing other things in it. I don't imagine that I will end up editing this file again unless it's a typo fix or something like that. 

I will see about looking at your other comments later. Just wanted to clarify here though maybe you were already aware of what I was doing and it was just a reminder just in case. 

Will be able to reply to the other comments in a bit I think.

**Comment by xexyl** [comment]
> Nice progress @xexyl, thank you 🙏 

Welcome. Good progress yes though not as much as I should like.

**Comment by xexyl** [comment]
> Please keep in mind that `news.md` is **NOT** a `CHANGES.md` file like we have for the `mkiocccentry` repo.
> 
> This is intended to be a high level description whose target audience is a user of the web site, not a developer.
> 
> We will probably edit `news.md` to thin out some of the details before the **Great Fork Merge**.
> 
> BTW: We are still pondering how to manage old news: to delete it off the bottom or archive it elsewhere. That's TBD which is why we have not yet gone into a thinning operation on the `news.md` file.
> 
> ## UPDATE 0
> Added `news.md` related TODO items to the **Great Form Merge** issue.

It seems like some thinning might be useful at times but I don't see why it's as necessary as it once was (if it ever was). I like seeing a the long list of news when there is some. Of course another option is to thin it out for the main page but then have the archive available unlike the past. This especially is useful and interesting when you have announcements of the winners and other things like that.

That's just my thoughts there. If you would rather I bring it up in the other issue I will and then we can discuss it. Would you like me to do that?

**Comment by lcn2** [comment]
> That's just my thoughts there. If you would rather I bring it up in the other issue I will and then we can discuss it. Would you like me to do that?

Sure 👍

**Pull request merged**
