### PR TITLE
Use canonicalised 4 spaces in .entry.json files

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Waiting for make quick_readme2index to finish ... then 2005/toledo should be done. After that one more entry I think in 2005. But I am not sure when I have to leave. If I do have to leave before that then at least I should be done the next time I work on it. It's already been too long with 2005 but I guess we have got other things done too so that's good.

**Comment by xexyl** [comment]
In fact I believe I might even be done with the last entry's index.html file but I have to wait and see once pandoc finishes its work.

**Review by lcn2 — COMMENTED** [review]
Changing code from:

```json
{
            "author_handle" : "Anonymous_1984"
}
```

to:

```json
{ "author_handle" : "Anonymous_1984" }
```

is wrong and will be fixed as soon as we get around to processing other PRs.

We will let this slide through.

Please be aware that this change is away from canonical.   For a sample of why, see what `bin/jfmt-wrapper.sh YYYY/dir/.entry.json` does.

In the interest of PR work flow, instead of rejecting this PR, we will let this mistake go though and correct it later on .. after the build stuff with mkiocccentry and relate repos has settled down.

**Comment by lcn2** [comment]
We plan to fix this soon ...

**Comment by lcn2** [comment]
While we don't yet have a tool so format all `.entry.json` files, for now we will use `bin/jfmt-wrapper.sh` to fix things.

Before we do that we are checking to be sure the current HTML state for the repo is OK using `make www`.  Not that er expected problems but rather just to verify.  FYI: All is well with the HTML state (as expected but it doesn't hurt to verify once in a while).

In absence of a tool (one that we have written but not tested), we will do:

```sh
find [12][90][89012][0-9] -name .entry.json -print | xargs -n 1 bin/jfmt-wrapper.sh -v 1
```

BTW: The fix shows that whatever tool you used to perform JSON changes with PR #2662 also introduced TAB characters into the `.entry.json` files.

# QUESTION

What tool, @xexyl did that?

# The fix

To restore canonical JSON formatting, we did:

```sh
find [12][90][89012][0-9] -name .entry.json -print | xargs -n 1 bin/jfmt-wrapper.sh -v 1
```

BTW: We have written a tool, currently untested, to do this.  We plan to also add a new fix JSON format rule to the top level `Makefile`.

With commit d981aa2a04c9f1e08858dda7d0d7466e28e27eab this problem has been corrected.

**Comment by xexyl** [comment]
I used the Makefile rule csv2entry (I think it is?). So f it's not canonical then it's s problem with the script. 

That is why I thought all was okay. It seems like it's not but I am reading this on the phone and I don't have my reading glasses - just distance glasses. 

Have to get some sleep. Good night!

**Comment by lcn2** [comment]
> I used the Makefile rule csv2entry (I think it is?). So f it's not canonical then it's s problem with the script.
> 
> That is why I thought all was okay. It seems like it's not but I am reading this on the phone and I don't have my reading glasses - just distance glasses.
> 
> Have to get some sleep. Good night!

Thank you for that information.  We will investigate what csv2entry is going as it appears that application has a bug.

**PLEASE** understand we are **NOT** blaming you for what happened, and we appreciate you calling our attention to the problem.

**Comment by xexyl** [comment]
> > I used the Makefile rule csv2entry (I think it is?). So f it's not canonical then it's s problem with the script.
> > That is why I thought all was okay. It seems like it's not but I am reading this on the phone and I don't have my reading glasses - just distance glasses.
> > Have to get some sleep. Good night!
> 
> Thank you for that information. We will investigate what csv2entry is going as it appears that application has a bug.

Yes it seems odd and if it's wrong then it must be a bug.

> 
> **PLEASE** understand we are **NOT** blaming you for what happened, and we appreciate you calling our attention to the problem.

I understand .. thanks for saying that though, just in case! I appreciate it.

**Comment by lcn2** [comment]
With commit db67bf8a37eac4bd5fb402106b3d89735ffc40a9 the bug that produced non-canonical JSON formatted files in `bin/csv2entry.sh` has been fixed.

**Comment by xexyl** [comment]
> With commit [db67bf8](https://github.com/ioccc-src/temp-test-ioccc/commit/db67bf8a37eac4bd5fb402106b3d89735ffc40a9) the bug that produced non-canonical JSON formatted files in `bin/csv2entry.sh` has been fixed.

Thanks! Sorry for the problem (even though it was not my fault). But I didn't see any .entry.json files modified. Did you already do that or does it need to be done? Well maybe I'll run a quick test and see and if necessary commit ...

**Comment by lcn2** [comment]
> > With commit [db67bf8](https://github.com/ioccc-src/temp-test-ioccc/commit/db67bf8a37eac4bd5fb402106b3d89735ffc40a9) the bug that produced non-canonical JSON formatted files in `bin/csv2entry.sh` has been fixed.
> 
> Thanks! Sorry for the problem (even though it was not my fault). But I didn't see any .entry.json files modified. Did you already do that or does it need to be done? Well maybe I'll run a quick test and see and if necessary commit ...

There is a bit more ti be worked on with the tools, something we hope to get to today.

**Pull request merged**
