### PR TITLE
Reword the recent deobfuscation changes

### PR DESCRIPTION
**Pull request by xexyl**
In most cases the word was changed to 'obfuscation' as it was about
obfuscation, not deobfuscation. In some cases like 1995/leo since the
file was (in 1995/leo) about a secret switch it was changed to
'secret.md' (and 'secret.html') but there were others like that as well.

One entry had the words 'spoiling the size rule' but this had been
changed to 'deobfuscating the size rule' which was obviously wrong.

In the latter YYYY/README.md files the judges had written after some
entries (brief summaries) '...

    ...We'll stop spouting spoilers now. Have fun exploring all the
    entries! 
    
but that was changed to:

    ...We'll stop spouting deobfuscation information now. Have fun
    exploring all the entries!
    
which wasn't really about deobfuscation but just a brief summary of what
the entries did.

And in the most problematic case (at least for me :-), 2018/ferguson) I
had put a joke in:

    ... but it's the only Easter egg I won't spoil
    
but it was changed to 'won't deobfuscate' which not only is not what it
is but it spoilt the joke.

In some cases the word was changed back to 'SPOILER' (or similar) but in
most cases not. I believe it should be better now. There are some
caveats, however, as below.

Although make find_missing_links is okay I do not remember if this will
catch links that refer to '%%REPO_URL%%' or other pandoc tokens. This
means I might have to go back to some earlier years to verify links are
okay. That should not take that much time I hope.

It might also be that some wording can still be improved some but it is
hoped this will be discovered when checking links and looking over the
manifest (which obviously changed).

### CODE REVIEW

**Comment by xexyl** [comment]
I believe this is much better and now I can look at the files mentioned in #2513. I am not sure if that is happening today or not. It might be good to do that next before reviewing the changes but of course it will require another manifest update.

**Review by lcn2 — COMMENTED** [review]
Not sure that the reintroduction the term "_spoiler_" helps. Will
this about this pull request some more.

**Comment by xexyl** [comment]
> Not sure that the reintroduction the term "_spoiler_" helps. Will this about this pull request some more.

It's rarely there but I can fix it if you want. And in one case it has to be there: the joke I referred to. I can remove the other references if you wish but the other words do not work well.

Anyway if you want me to change the other ones to something else I can. But the one in 2018/ferguson has to stay the same (the others in there I changed to 'obfuscation').

**Comment by xexyl** [comment]
Here's an example where deobfuscation/obfuscation does not work to give you an idea:

> ### GAME STRATEGY SPOILER


The other words do not work well. It has nothing to do with obfuscation and it has nothing to do with the opposite. And games do have spoilers too.

**Comment by xexyl** [comment]
> Here's an example where deobfuscation/obfuscation does not work to give you an idea:
> 
> > ### GAME STRATEGY SPOILER
> 
> The other words do not work well. It has nothing to do with obfuscation and it has nothing to do with the opposite. And games do have spoilers too.

For further context it says:

--

### GAME STRATEGY SPOILER

The trick, of course, is to drop items in empty rooms to mark them.  That way
you usually know if you're in a room you've seen before.  It greatly aids
mapping.

--

There is no way obfuscation or deobfuscation fits that. Spoiler, however, does work quite well.

**Comment by lcn2** [comment]
Fair points to ponder, @xexyl

**Review by lcn2 — COMMENTED** [review]
We will let this pull request go thru now
as we think this is something we can build and
improve on.

Thanks @xexyl

**Comment by xexyl** [comment]
> We will let this pull request go thru now
> as we think this is something we can build and
> improve on.
> 
> Thanks @xexyl
> 

Yes it is easier that way. I don't think we need to worry too much about the word spoiler but there might be a few more cases where it could be reworded if necessary. 

But the filenames are now good and the wording is much better too. That's expected as I went over them manually. Some I initially had one way and then I reconsidered it and thought maybe spoiler would be better. 

But if a better word can be thought of it would work except for a very few cases like those I already cited. 

I already said I was going to sleep but now I really am going to bed. 

Good night! We can discuss these things tomorrow. Sleep well!

**Comment by xexyl** [comment]
> Fair points to ponder, @xexyl 

Thank you. Good night!

**Pull request merged**
