### PR TITLE
Typo fix in thanks file

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I do hope to do more today and if so I might do more in this file but I have something else here I want to look at too. Not sure how easy it will be to do quickly in which case I might not do it now but whether I can do more in this file or not remains to be seen. Today more problems than I have had (to do with surgery I mean). Still every day is better over all but having not the best luck today.

**Comment by xexyl** [comment]
.. fortunately the task was very easy to do .. will be running `make quick_www` and then will do a pull request. Unsure if I'll do beyond that though ... we'll see.

**Comment by xexyl** [comment]
.. actually I was going to change the '../../bugs.html' to `%%REPO_URL%%/bugs.html` but that's a problem as it doesn't link to the website it's at but rather the GitHub one. So I'll just do the first part and say in log what I would have done for that change. That change can be made later on. So I have to backtrack a bit and right now I have to go afk a bit so I will be a while longer.

**Comment by lcn2** [comment]
> .. actually I was going to change the '../../bugs.html' to `%%REPO_URL%%/bugs.html` but that's a problem as it doesn't link to the website it's at but rather the GitHub one. So I'll just do the first part and say in log what I would have done for that change. That change can be made later on. So I have to backtrack a bit and right now I have to go afk a bit so I will be a while longer.

As mentioned awhile ago, there are several cases where `%%REPO_URL%%` is **NOT** used but instead a direct relative link is used:

- html files
- files that end in .txt
- image files
- files that need to be downloaded (tarballs, compressed files, binary data files,etc.)

Anything that can be rendered directly in the browser (and for which viewing the content via GitHub is not needed) and anything whose content cannot be viewed but instead should be downloaded to the viewer's computer instead: those cases a relative file link without `%%REPO_URL%%` needs to be used. 

We will repeat this **IMPORTANT** message in the relevant issue.

**Comment by xexyl** [comment]
> > .. actually I was going to change the '../../bugs.html' to `%%REPO_URL%%/bugs.html` but that's a problem as it doesn't link to the website it's at but rather the GitHub one. So I'll just do the first part and say in log what I would have done for that change. That change can be made later on. So I have to backtrack a bit and right now I have to go afk a bit so I will be a while longer.
> 
> As mentioned awhile ago, there are several cases where `%%REPO_URL%%` is **NOT** used but instead a direct relative link is used:
> 
> * html files
> * files that end in .txt
> * image files
> * files that need to be downloaded (tarballs, compressed files, binary data files,etc.)
> 
> Anything that can be rendered directly in the browser (and for which viewing the content via GitHub is not needed) and anything whose content cannot be viewed but instead should be downloaded to the viewer's computer instead: those cases a relative file link without `%%REPO_URL%%` needs to be used.
> 
> We will repeat this **IMPORTANT** message in the relevant issue.

Yes ... I remember. But it slipped my mind at first. But yes good idea to put it in again. Thanks.

**Pull request merged**
