### PR TITLE
Move inc/md2html.cfg to bin/

### PR DESCRIPTION
**Pull request by xexyl**
This is a very large commit not only because I forgot to run make www
after updating the menus but I also forgot to do that after the update
to some of the award titles (only quick-readme2index.sh was used).

There is a typo fix in bin/README.md.

This commit does mean that md2html.cfg has to be added to bin/README.md
but that can be done later.

The steps run to verify this works okay:

    make www
    git status
    git diff
    git add -u
    make update
    git status
    git restore $(git check)

The last is important as it is not time for make update. 'git check' is
an alias:

    git diff --name-only

### CODE REVIEW

**Comment by xexyl** [comment]
See the other pull request for how this would have to be fixed if:

```
<!-- no thank you -->

```

does not stand out in a way that you want. Attached a screenshot showing how it does stand out. It's not in rendered as a comment but as a code block so it is there. I don't know why that would not suffice as the text still is there and visible but I can change it back if you want. But since it does stand out and I have to go I will leave it at this. If you want to delay this I can fix it tomorrow.

I don't want to have to do this all over (and I think it would be a waste of time too) but if you want it to look different I can fix it. Just let me know.

**Comment by xexyl** [comment]
Fixed the format to a way you like it better.

**Review by lcn2 — APPROVED** [review]

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

You are most welcome ... hopefully everything went okay with it. It does seem to. I'll do more tomorrow but I don't really know what that might be. I would like to believe I have no more top level html files besides the FAQ and bugs file but I would guess I have two or three more. But what is good is that most of the are good if not all of them.

It's unfortunate it will take some time to go through clicking on links in all the entry index.html files but most likely that's all that has to be done - with perhaps a few fixes in format here and there.

**Pull request merged**
