### PR TITLE
Update remarks about pootify scripts in 1998/dlowe

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I will be going afk shortly and when back I hope to look at more things here but I'm having a very slow day so I don't know what will be done or not. I know where I can resume but not sure how far I'll get from that point.

**Comment by xexyl** [comment]
I am very sorry but my brain right now is scattered: not really able to focus on this. I hope that changes in a bit but I'm not sure if it will. I'm sure tomorrow will be better if not later today.

**Comment by lcn2** [comment]
Poot 🐠💨 😀 @xexyl

**Comment by xexyl** [comment]
> Poot 🐠💨 😀 @xexyl

Funny thing: there are other words that start with POOT. Pooterish is a fun one but most resembling what this is (though I did not know it until I worked on one of the POOT entries) is pootle: British English: move/travel in a leisurely way. So the question is does the wind move them along?

**Pull request merged**
