### PR TITLE
Typo fixes in several bin/ files

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Okay that's really all for today. Back tomorrow.

**Comment by lcn2** [comment]
thanks @xexyl

**Comment by lcn2** [comment]
Much of the changes in this pull request will be lost because of ongoing edits to bin files as part of the current work.

**Comment by xexyl** [comment]
> Much of the changes in this pull request will be lost because of ongoing edits to bin files as part of the current work.

I can fix them again .. no problem.

**Comment by lcn2** [comment]
Well some of them .. TBD

**Pull request merged**
