### PR TITLE
Make 1987/heckbert examples work

### PR DESCRIPTION
**Pull request by xexyl**
That is the examples have been changed to not break. See the README.md file for details (including some fun details).

### CODE REVIEW

**Comment by lcn2** [comment]
It is a mistake to remove the alt rule altogether.  All lower level Makefiles should have all of the rules that are callable from the upper Makefile.

Please restore an empty alt rule:

```make
# alternative executable
#
alt: data ${ALT_TARGET}
	@${TRUE}
```

Via another pull request.

**Comment by lcn2** [comment]
Thanks for fixing the examples, @xexyl

**Comment by xexyl** [comment]
> It is a mistake to remove the alt rule altogether. All lower level Makefiles should have all of the rules that are callable from the upper Makefile.
> 
> Please restore an empty alt rule:
> 
> ```makefile
> # alternative executable
> #
> alt: data ${ALT_TARGET}
> 	@${TRUE}
> ```
> 
> Via another pull request, @xexyl

Oh sorry about that. I'll do that now before I reply to other comments (in other threads).

**Comment by xexyl** [comment]
> > It is a mistake to remove the alt rule altogether. All lower level Makefiles should have all of the rules that are callable from the upper Makefile.
> > Please restore an empty alt rule:
> > ```makefile
> > # alternative executable
> > #
> > alt: data ${ALT_TARGET}
> > 	@${TRUE}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Via another pull request, @xexyl
> 
> Oh sorry about that. I'll do that now before I reply to other comments (in other threads).

Oh I can't do that just yet as it depends on the file that no longer exists. Or is this okay? Just let me know and I'll be happy to fix. But that's why I deleted it.

**Comment by xexyl** [comment]
> It is a mistake to remove the alt rule altogether. All lower level Makefiles should have all of the rules that are callable from the upper Makefile.
> 
> Please restore an empty alt rule:
> 
> ```makefile
> # alternative executable
> #
> alt: data ${ALT_TARGET}
> 	@${TRUE}
> ```
> 
> Via another pull request, @xexyl

That pull request or rather commit is at https://github.com/ioccc-src/temp-test-ioccc/pull/26/commits/cb16df37004754f4e5992fe1740726a5b5e0e183 (pull request is https://github.com/ioccc-src/temp-test-ioccc/pull/26).

I'll keep the alt rules from now on even if the .orig file is no longer there. Sorry about that!

**Comment by xexyl** [comment]
> Thanks for fixing the examples, @xexyl

You are most welcome my good friend!

**Pull request merged**
