### PR TITLE
Add ioccc_status.sh to quickly update status.json

### PR DESCRIPTION
**Pull request by xexyl**
This was done quickly to give me something to do but if it's useful in
any form then so much the better but it seems it's more ideal to update
the status.json file automatically rather than having to do it manually.

The script does not have to update every field in the status.json file.
It doesn't even have to update any for that matter. The usage is:

    usage: ioccc_status [-h] [-V] [-v level] [-s status] [-d] [-n] [-I status_ver] status.json

        -h                          print help and exit
        -V                          print version and exit
        -v level                    set verbosity level
        -s statue                   set contest status to open or closed
        -d                          update status_date
        -n                          update latest_news date
        -I status_ver               update IOCCC_status_version

                                        NOTE: status_ver must be one of "open" or "closed"

        status.json                 the file to update

    status version: 0.0.1-0 2023-10-02

Again if this is not useful that's perfectly okay: it gave me something
to do and it seems useful but there certainly are other ways that it
could be done, better, worse or just different.

Obviously this script does not first verify that it is valid json or the
correct format. If the format is incorrect it will not be updated.

Added to tmp/src/ioccc_status and updated the tmp/src/Makefile.

Added to tmp/src/ioccc_status/.gitignore ioccc_status: the file in the
repo is ioccc_status.sh.

### CODE REVIEW

**Comment by xexyl** [comment]
Again to reiterate: I don't mind if this is merged or not. It's just one way that it could be done and perhaps you already have a thought on how it might be done in a way that fits the needs better. It gave me something to do and that is good enough for me!

I'll be afk a while .. not sure if I'll get anything else done today. We'll have to see I guess. Hope you're sleeping well.

Good day!

**Comment by xexyl** [comment]
Something I forgot to mention is that the status must be `closed` or `open`; otherwise it's an error.

Of course if you wanted it to be something else or even not merge it that's fine. It's just one way to go about it!

**Comment by xexyl** [comment]
The flaw btw: if the value for the version has a `/` in it then there will be a sed syntax error. 

Perhaps that is not an issue but I will play with it a bit later on. If it's not feasible to fix then since it shouldn't have that character anyway it can be filtered or else reported as an invalid value. 

These are tbd later on.

**Comment by xexyl** [comment]
Too tired to do it now ... unless you think that it's not a problem I'll have to look at it another time - maybe not until tomorrow. I think that filtering out the characters is not the best idea because it should be able to support other characters if they're truly desired.

... but it was done quickly and can be worried about later - or not - as it's not like it's urgent ...

**Comment by lcn2** [comment]
FYI: GitHub reports: "This pull request is still a work in progress" and so we will ignore this for now.

**Comment by xexyl** [comment]
Trying to figure out how to close this one with the app but I would say just hold off until tomorrow. I will fix it then.

**Comment by xexyl** [comment]
Opening this again. Will open a new pull request with a slight change. We can then discuss if the version of the IOCCC status should have a specific format. If so that'd solve the problem outright I think. I'll open this and then do that quick change (little importance though it might seem) and then will try resting. I'll update the thanks file later on and work on sgit after that I hope. Have to rest soon or try to.

**Comment by xexyl** [comment]
See commit https://github.com/ioccc-src/temp-test-ioccc/pull/990/commits/64459249c76eb6fbf0d07414f722471a758ca7c0 for some minor updates and fixes. We can discuss the question I have over there.

**Pull request merged**
