### PR TITLE
Remove 2012/kang alt code

### PR DESCRIPTION
**Pull request by xexyl**
This code is based on a 'fix' that causes another issue, and could
potentially be 'wrong' to have. It is better, I think, to pose the 
challenge to the viewer to see if they can solve the problem themselves,
and if so if there are any issues with such a fix.

### CODE REVIEW

**Comment by xexyl** [comment]
Great. The other fix that should be done (I thought) was not done. So this cannot be merged yet either `*sigh*`

Have to go afk for a bit ...

**Comment by xexyl** [comment]
Hopefully that will solve the problem until they are merged into master. Seems a mess was caused all because a different branch had to be created :(

Well afk now ... back in a bit. Will work on 2013 then.

**Comment by xexyl** [comment]
Nope, checks failed. Ugh.

**Comment by xexyl** [comment]
Oh manifest issues.

**Comment by xexyl** [comment]
Fixing .. while the task is processing I'll be afk ... when back I'll c commit.

**Comment by xexyl** [comment]
.. and until the test.yml issue is resolved (merged is all it takes I hope) I'll not make new pull requests.

**Comment by xexyl** [comment]
I just committed the fix to manifest and it's not showing up .. weird.

**Comment by xexyl** [comment]
Oh because the push is not working right. Which means that I need yet another branch which likely means having to fix the test.yml file again.

**Comment by xexyl** [comment]
Okay got it here. Hopefully al is good. Now afk anyway.

**Review by lcn2 — APPROVED** [review]
--alt

**Comment by xexyl** [comment]
> --alt

C--: the honest name for C++.

**Comment by xexyl** [comment]
> > --alt
> 
> --C: the honest name for C++. 

I read a joke years ago that is kind of similar although my comment is based on a quote of mine. Anyway something like: 

In many respects, Java is like C--.

**Comment by xexyl** [comment]
> > > --alt
> > 
> > --C: the honest name for C++. 
> 
> I read a joke years ago that is kind of similar although my comment is based on a quote of mine. Anyway something like: 
> 
> In many respects, Java is like C--. 
> 
> 

Personally I like certain parts of Java like the graphics API but I can't stand C++. I tried really hard to like it but I didn't manage. I just started C-ifying (my word for it) the C++ I had written. But that project has long been more or less abandoned although I would actually like to get back to it someday. It was a rewrite of the MUD.

**Pull request merged**
