### PR TITLE
Add to FAQ about seeing fix changes

### PR DESCRIPTION
**Pull request by xexyl**
It seems to me that it is a good idea to show people how to see what
changed in order to get an entry to work in modern systems. I gave an
example where it's harder to tell because it's a very long line and an
example where it's easier to tell as it's not long lines but rather
shorter lines. Well it's easier to see on a line-by-line basis ..
whether it's easy to see what actually changed is probably another
matter entirely (especially since it's easier to see when you have
compiler errors in front of you) :-)

### CODE REVIEW

**Comment by lcn2** [comment]
Please modify as per the suggested 2 new rules as discussed in [comment 1766839666](https://github.com/ioccc-src/temp-test-ioccc/pull/1075#issuecomment-1766839666).

**Comment by xexyl** [comment]
> Please modify as per the suggested 2 new rules as discussed in [comment 1766839666](https://github.com/ioccc-src/temp-test-ioccc/pull/1075#issuecomment-1766839666).

Does it relate to this commit? Well I'll take a look and either let you know that I'll get it it [when] or else that I don't understand what you mean.

**Comment by xexyl** [comment]
.. ah, I see now. Okay. That'll take some time to do but I can do it.

**Comment by xexyl** [comment]
> Please modify as per the suggested 2 new rules as discussed in [comment 1766839666](https://github.com/ioccc-src/temp-test-ioccc/pull/1075#issuecomment-1766839666).

Done in commit https://github.com/ioccc-src/temp-test-ioccc/pull/1112/commits/55d09331d7737351b7f2ce46a044de859e924032!

**Pull request merged**
