### PR TITLE
Fix format of table in 1992/buzzard.1

### PR DESCRIPTION
**Pull request by xexyl**
This took some careful editing but it now looks nice on an iPhone 14 Pro Max and it also looks nice on a laptop (16"). In Safari responsive mode at 500 x 100 it also looks okay which I think is pretty good. For some macros the function line had to be split up and it might look like the formatting is wrong in a few cases but this took trial and error to get it to align right (or very close if not completely).

### CODE REVIEW

**Comment by xexyl** [comment]
Let me know how this looks on your end too.

... and I really am doing other things now, again. This was just annoying me and I wanted it resolved.

**Review by lcn2 — APPROVED** [review]
Will review this change when it show up on the website

**Comment by lcn2** [comment]
[1992/buzzard.1/index.html](https://ioccc-src.github.io/temp-test-ioccc/1992/buzzard.1/index.html) looks to good 👍 @xexyl

**Comment by xexyl** [comment]
> [1992/buzzard.1/index.html](https://ioccc-src.github.io/temp-test-ioccc/1992/buzzard.1/index.html) looks to good 👍 @xexyl 

I thought so too. Thanks for confirming it on your end also!

It took some tinkering but as long as the spacing is not changed it should be good. Unless something changes in pandoc I guess. But that's another matter entirely.

**Comment by xexyl** [comment]
A question of whether other code blocks should be changed like this is maybe something to consider but it might not be worth it - especially not for years already looked at?

Of course it might also not be possible to fix all and in many cases it might actually not be desirable or even a good idea but since this file also has code blocks that don't look good on phones I thought I should bring it up for you to ponder (or not).

**Pull request merged**
