### PR TITLE
Fixes in 2019/burton/Makefile and README.md

### PR DESCRIPTION
**Pull request by xexyl**
The Makefile had a bad character, a '%' instead of a '$' which caused a
rule to fail.

Format fixes in README.md.
 
There is one thing I'm not sure about. It appears to be a mistake but 
I'm not sure if there is some meaning. Line 66:

    Input should be less than ten million octets toavoidthisproblem.

But the last 'word' should be, at least if it is a mistake, four words.
I have not changed it as the context was not clear enough to be sure it
was incorrect. This can be dealt with another time.

### CODE REVIEW

**Comment by xexyl** [comment]
Question for you Landon. See the log for this pull request. Is this a mistake?

    There is one thing I'm not sure about. It appears to be a mistake but
    I'm not sure if there is some meaning. Line 66:
    
        Input should be less than ten million octets toavoidthisproblem.
    
    But the last 'word' should be, at least if it is a mistake, four words.
    I have not changed it as the context was not clear enough to be sure it
    was incorrect. This can be dealt with another time.

**Comment by xexyl** [comment]
.. leaving for the day .. will do more tomorrow.

**Comment by lcn2** [comment]
${thanks}

**Comment by xexyl** [comment]
> ${THANKS}

${NP}

What about the typo concern in comment https://github.com/ioccc-src/temp-test-ioccc/pull/264#issuecomment-1493417968? Is it a typo or do you think or believe it is intentional ?

**Comment by lcn2** [comment]
> Question for you Landon. See the log for this pull request. Is this a mistake?
> 
> ```
> There is one thing I'm not sure about. It appears to be a mistake but
> I'm not sure if there is some meaning. Line 66:
> 
>     Input should be less than ten million octets toavoidthisproblem.
> 
> But the last 'word' should be, at least if it is a mistake, four words.
> I have not changed it as the context was not clear enough to be sure it
> was incorrect. This can be dealt with another time.
> ```

We think this is intentional.  We suggest that you put the word within double quotes.

**Comment by xexyl** [comment]
> > Question for you Landon. See the log for this pull request. Is this a mistake?
> > ```
> > There is one thing I'm not sure about. It appears to be a mistake but
> > I'm not sure if there is some meaning. Line 66:
> > 
> >     Input should be less than ten million octets toavoidthisproblem.
> > 
> > But the last 'word' should be, at least if it is a mistake, four words.
> > I have not changed it as the context was not clear enough to be sure it
> > was incorrect. This can be dealt with another time.
> > ```
> 
> We think this is intentional. We suggest that you put the word within double quotes.

I thought it might be too.

Thank you.

**Pull request merged**
