### PR TITLE
Many manifest improvements and fixes

### PR DESCRIPTION
**Pull request by xexyl**
This is a large update that modifies every .entry.json file and fixes
many others. The changes of every .entry.json file are as follows:

- change 'entry source' to 'entry source code' [0]
- change 'original source' to 'original source code' [0]
- change 'directory path from top directory' to 'directory path from top
  level directory'

[0] This is for consistency purposes. Other options were pondered but as
the index.html files refer to 'Alternate code' this was the simplest way
to go about it and it also feels more natural. A question was whether to
have 'entry code' and 'original entry code' or to have the word 'source'
added to it but I decided upon including the word 'source'. Another
question has occurred to me is whether or not 'original source code'
should instead be 'original entry source code' but that can be decided
upon later as that occurred to me after much of the files were already
rebuilt. The consistency that this commit has made is for the README.md
sections and in particular 'Alternate code'. One might wonder if that
should be changed to 'Alternate source code' as now the manifest
includes 'source' in the 'entry code' and 'original code' but the
manifest itself is what was actually updated and having 'source' feels
more natural for submitted files. After all not all entries have
alternate code. These questions can be decided on when looking at the
index.html files that have been rebuilt.

Changed 'alt code' to 'alternate code' where this was not already done
(in the manifest). It is questionable whether this should be done in
markdown files or not (in the README.md files section it already is done
but not necessarily in other places).

Many files had incorrect descriptions that have been checked.

Renamed 2020/endoh2/spoiler/spoiler.{md,html} to index.{md,html} so one
can go to just 2020/endoh2/spoiler and see the web page. Although the
manifest of 2 020/endoh2/index.html will link to it and that's probably
how most people will notice it it seems useful especially as the web
page links to the different files in spoiler/ or at least refers to
them, giving a description (kind of like the manifest in
2020/endoh2/index.html).

Due to the above changes all the entries had their index.html files
regenerated too.

There were likely other changes and fixes as well.

What has NOT been done is a check over all items, typos or otherwise,
though some typos have been fixed. Nonetheless this commit goes a long
way to resolving issue #1933.

Updated thanks file both with a missing `<div>` id and added a manifest
improvements section as the manifest is quite important.

### CODE REVIEW

**Comment by xexyl** [comment]
I hope the detailed log is helpful in parsing the manifest updates. We can look at the questions I have posed in the html files and discuss them if necessary. I was unsure about some and even now I am a bit unsure on some but I think it's an improvement anyway even if it can be further refined.

I am going to do other things for the rest of the day. Maybe tomorrow I can start looking at every line itself and fix anything there.

**Comment by xexyl** [comment]
> I hope the detailed log is helpful in parsing the manifest updates. We can look at the questions I have posed in the html files and discuss them if necessary. I was unsure about some and even now I am a bit unsure on some but I think it's an improvement anyway even if it can be further refined.
> 
> I am going to do other things for the rest of the day. Maybe tomorrow I can start looking at every line itself and fix anything there.

I forgot that GitHub would render the html I included. Let me try that again:

```
Updated thanks file both with a missing `<div>` id and added a manifest
improvements section as the manifest is quite important.

**Comment by lcn2** [comment]
Thank you and well done @xexyl

**Comment by xexyl** [comment]
> Thank you and well done @xexyl 

You are most welcome. 

We can look at and discuss how the descriptions can be further improved. 

Tomorrow maybe I can try and go through all items. I still am not sure about the best way to do that but I will figure something out.

**Comment by xexyl** [comment]
> > Thank you and well done @xexyl
> 
> You are most welcome.
> 
> We can look at and discuss how the descriptions can be further improved.
> 
> Tomorrow maybe I can try and go through all items. I still am not sure about the best way to do that but I will figure something out.

As I took care of things at the other repo I will not be doing this today I'm afraid. But tomorrow I hope to start looking at every entry in the manifest for typos and other things. I am off for the rest of the day now. That being said if you look at how the changes in this commit look and you have thoughts please let me know in that issue and I might be able to reply today. Otherwise tomorrow.

Have a great day!

**Pull request merged**
