### PR TITLE
Fix in 2019/ciura/README.md

### PR DESCRIPTION
**Pull request by xexyl**
Move author information to first column.

### CODE REVIEW

**Comment by lcn2** [comment]
fmt

**Comment by xexyl** [comment]
> fmt

And therein lies one of the problems with some fixes. Nevertheless this one will be undone but not sure if there should be an alt version or not. I'm not quite awake enough to do these things just yet.

But I am happy to help!

**Comment by xexyl** [comment]
Happy to help!

**Comment by xexyl** [comment]
Irony: writing a comment saying you're going to do this or that but not quite awake enough yet ... but then writing it in the wrong thread! Well I'll be doing some fixes soon anyway when I'm more awake.

**Pull request merged**
